import express from "express";

const externalPort=Number(process.env.PORT||3000);
const v24Port=Number(process.env.DELILAH_V24_PORT||4900);
const SYARAH_CACHE_TTL=10*60_000;
process.env.PORT=String(v24Port);
await import("./server-v24.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const bodyById=new Map(),syarahCache=new Map();
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
function humanNumbers(s=""){let q=digits(s);q=q.replace(/(\d+(?:\.\d+)?)\s*(?:ألف|الف)(?=\s|$|ريال|ر\.?س|كم|كيلو)/gi,(_,x)=>String(Math.round(Number(x)*1000)));q=q.replace(/(\d+(?:\.\d+)?)\s*[kK](?=\s|$|SAR|ريال|ر\.?س|km)/g,(_,x)=>String(Math.round(Number(x)*1000)));return q}
function norm(s=""){return humanNumbers(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim()}
function money(v){const n=Number(String(v||'').replace(/[^0-9.]/g,''));return Number.isFinite(n)&&n>=1000&&n<=5_000_000?n:null}
function canonical(v=""){try{const u=new URL(v);u.hash='';for(const k of[...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}}
function decodeHtml(s=""){return String(s||'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function stripHtml(s=""){return decodeHtml(String(s||'')).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:property|name|itemprop)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name|itemprop)=["']${k}["'][^>]*>`,'i').exec(html);return a?decodeHtml(a[1]):null}
function titleFrom(html=''){const h1=/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1],t=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1];return stripHtml(h1||meta(html,'og:title')||t||'').replace(/\s*\|\s*Syarah.*$/i,'').slice(0,220)}
function isDirectSyarah(v=""){try{const u=new URL(v);return (u.hostname==='syarah.com'||u.hostname.endsWith('.syarah.com'))&&/^\/(?:(?:en|ar)\/)?cardetail\/[^/]+-(?:used|new)-\d+\/?$/i.test(u.pathname)}catch{return false}}

const BRAND_VARIANTS={
 Jeep:['jeep','جيب'],Toyota:['toyota','تويوتا'],Nissan:['nissan','نيسان'],Lexus:['lexus','لكزس'],Mercedes:['mercedes','mercedes benz','مرسيدس'],BMW:['bmw','بي ام','بي ام دبليو'],Porsche:['porsche','بورش'],Ford:['ford','فورد'],Lincoln:['lincoln','لينكون'],Hyundai:['hyundai','هيونداي'],Kia:['kia','كيا'],Volkswagen:['volkswagen','vw','فولكس','فولكس واجن'],Chevrolet:['chevrolet','chevy','شفروليه'],GMC:['gmc','جي ام سي'],Mazda:['mazda','مازدا'],Honda:['honda','هوندا'],Mitsubishi:['mitsubishi','ميتسوبيشي'],Geely:['geely','جيلي'],Changan:['changan','شانجان'],GAC:['gac','جي ايه سي'],MG:['mg','ام جي'],Genesis:['genesis','جينيسيس','جينيسس'],Jetour:['jetour','جيتور'],Haval:['haval','هافال'],Audi:['audi','اودي'],LandRover:['land rover','لاند روفر'],RangeRover:['range rover','رينج روفر'],Cadillac:['cadillac','كاديلاك'],Dodge:['dodge','دودج'],Suzuki:['suzuki','سوزوكي'],Isuzu:['isuzu','ايسوزو'],Peugeot:['peugeot','بيجو'],Renault:['renault','رينو'],Chery:['chery','شيري'],Hongqi:['hongqi','هونشي'],BYD:['byd','بي واي دي'],Tesla:['tesla','تسلا'],Lucid:['lucid','لوسيد']
};
const MODEL_VARIANTS={
 Compass:['compass','كومباس'],Wrangler:['wrangler','رانجلر'],Cherokee:['cherokee','شيروكي'],'Grand Cherokee':['grand cherokee','جراند شيروكي'],Renegade:['renegade','رينيجيد'],Gladiator:['gladiator','جلادياتور'],
 Patrol:['patrol','باترول'],Sunny:['sunny','صني'],Altima:['altima','التيما'],'X-Trail':['x trail','x-trail','اكس تريل'],
 'Land Cruiser':['land cruiser','landcruiser','لاند كروزر','لاندكروزر'],Prado:['prado','برادو'],Camry:['camry','كامري'],Corolla:['corolla','كورولا'],Yaris:['yaris','يارس'],Fortuner:['fortuner','فورتشنر'],Hilux:['hilux','هايلوكس'],'RAV4':['rav4','راف فور'],
 X5:['x5'],X3:['x3'],X1:['x1'],C200:['c200'],E200:['e200'],GLC:['glc'],GLE:['gle'],
 Tucson:['tucson','توسان'],'Santa Fe':['santa fe','سنتافي'],Sonata:['sonata','سوناتا'],Accent:['accent','اكسنت'],Elantra:['elantra','النترا'],
 Sportage:['sportage','سبورتاج'],Sorento:['sorento','سورينتو'],K5:['k5'],Pegas:['pegas','بيجاس'],Seltos:['seltos','سيلتوس'],
 Territory:['territory','تيريتوري'],Explorer:['explorer','اكسبلورر'],Expedition:['expedition','اكسبديشن'],Tahoe:['tahoe','تاهو'],
 Accord:['accord','اكورد'],Civic:['civic','سيفيك'],City:['honda city','سيتي'],'CR-V':['cr v','cr-v'],
 'CX-5':['cx 5','cx-5','cx5'],'Mazda 6':['mazda 6','مازدا 6'],H6:['h6'],Jolion:['jolion','جوليون'],Coolray:['coolray','كولراي'],Emgrand:['emgrand','امجراند'],CS75:['cs75','cs 75','سي اس 75'],CS35:['cs35','cs 35','سي اس 35'],Alsvin:['alsvin','السفن'],T2:['t2'],T1:['t1'],X70:['x70'],Dashing:['dashing','داشينج']
};
const STOP=new Set(norm('i want show me find search looking for need car cars vehicle vehicles used new second hand preowned pre owned مستعمل مستعمله مستعملة جديد جديده جديدة ابي ابغى اريد ابحث دور لي سيارة سياره سيارات موديل model year years سنة سنه from to between and or newer older above over under below less more max maximum minimum min budget price سعر ميزانية ميزانيه ريال sar km kilometer kilometers mileage ممشى الممشى كيلو كم in at near الرياض riyadh جدة جده jeddah الدمام dammam الخبر khobar مكة مكه makkah المدينة المدينه madinah saudi arabia ksa suv sedan coupe hatchback pickup family luxury reliable clean cheap cheapest best good automatic manual gasoline petrol diesel hybrid electric').split(' '));
const CITY_WORDS=new Set(['riyadh','الرياض','jeddah','جده','جدة','dammam','الدمام','khobar','الخبر','makkah','مكه','madinah','المدينه','المدينة']);
function phraseIn(text,phrase){const a=` ${norm(text)} `,b=` ${norm(phrase)} `;return a.includes(b)}
function findBrand(q){let best=null;for(const[brand,vs]of Object.entries(BRAND_VARIANTS))for(const v of vs){const nv=norm(v);if(phraseIn(q,nv)&&(!best||nv.length>best.variant.length))best={brand,variant:nv}}return best}
function findKnownModel(q){let best=null;for(const[model,vs]of Object.entries(MODEL_VARIANTS))for(const v of vs){const nv=norm(v);if(phraseIn(q,nv)&&(!best||nv.length>best.variant.length))best={model,variant:nv,variants:vs}}return best}
function genericModelAfterBrand(q,brandHit){if(!brandHit)return null;const x=norm(q),p=x.indexOf(brandHit.variant);if(p<0)return null;const tail=x.slice(p+brandHit.variant.length).trim().split(' '),out=[];for(const t of tail){if(!t||STOP.has(t)||CITY_WORDS.has(t)||/^\d+(?:\.\d+)?$/.test(t)||/^20\d{2}$/.test(t))break;if(/^(sar|km|ريال|كيلو|كم)$/.test(t))break;out.push(t);if(out.length>=4)break}return out.length?out.join(' '):null}
function cityOf(q=''){const x=norm(q);if(/\briyadh\b|الرياض/.test(x))return'Riyadh';if(/\bjeddah\b|جده|جدة/.test(x))return'Jeddah';if(/\bdammam\b|الدمام/.test(x))return'Dammam';if(/\bkhobar\b|الخبر/.test(x))return'Khobar';if(/\bmakkah\b|\bmecca\b|مكه/.test(x))return'Makkah';if(/\bmadinah\b|\bmedina\b|المدينه|المدينة/.test(x))return'Madinah';return null}
function parseIntent(body={}){const f=body.filters&&typeof body.filters==='object'?body.filters:{},raw=humanNumbers(String(body.query||'')),x=norm(raw),brandHit=findBrand(x),known=findKnownModel(x),generic=known?null:genericModelAfterBrand(x,brandHit);const years=[...raw.matchAll(/\b(20\d{2})\b/g)].map(m=>Number(m[1]));let minYear=Number(f.minYear)||null,maxYear=Number(f.maxYear)||null;const between=x.match(/(?:between|من)\s*(20\d{2})\s*(?:and|to|الى|إلى|و)\s*(20\d{2})/i);if(between){minYear=minYear||Math.min(Number(between[1]),Number(between[2]));maxYear=maxYear||Math.max(Number(between[1]),Number(between[2]))}else if(years.length){const y=years[0];if(/(?:and above|or newer|and newer|\+|وفوق|واكثر|وأكثر|فما فوق|من موديل)/i.test(raw))minYear=minYear||y;else if(/(?:and below|or older|and older|وتحت|واقل|وأقل|حتى موديل)/i.test(raw))maxYear=maxYear||y;else minYear=minYear||y}const km=x.match(/(?:under|below|less than|max(?:imum)?|تحت|اقل|أقل)\s*(\d{2,7})\s*(?:km|كيلو|كم)/i),price=x.match(/(?:under|below|less than|max(?:imum)?|budget|تحت|اقل|أقل|ميزانيه|ميزانية)\s*(\d{4,7})(?!\s*(?:km|كيلو|كم))/i);const model=known?.model||(generic?generic.split(' ').map(w=>w.length<=3?w.toUpperCase():w[0].toUpperCase()+w.slice(1)).join(' '):null),modelVariants=known?.variants||(generic?[generic]:[]);return{query:String(body.query||''),condition:body.condition==='new'?'new':'used',brand:brandHit?.brand||null,model,modelVariants,minYear,maxYear,maxPrice:Number(f.maxPrice)||(price?Number(price[1]):null),maxMileage:Number(f.maxMileage)||(km?Number(km[1]):null),city:String(f.city||cityOf(raw)||'').trim()||null,seller:String(f.seller||'').trim()||null,sourceType:String(f.sourceType||'').trim()||null,confidence:model?0.99:brandHit?0.9:0.72}}
function brandMatches(evidence,brand){if(!brand)return true;return (BRAND_VARIANTS[brand]||[brand]).some(v=>phraseIn(evidence,v))}
function modelMatches(evidence,intent){if(!intent.model)return true;return (intent.modelVariants?.length?intent.modelVariants:[intent.model]).some(v=>phraseIn(evidence,v))}
function evidence(c={}){let path='';try{path=decodeURIComponent(new URL(c.url||'').pathname.replace(/[-_]+/g,' '))}catch{}return `${c.title||''} ${path} ${c.brand||''}`}
function semanticMatch(c,intent){if(!c?.url||c.saleVerified!==true||c.condition!==intent.condition)return false;const e=evidence(c);if(intent.brand&&!brandMatches(e,intent.brand))return false;if(intent.model&&!modelMatches(e,intent))return false;if(intent.minYear&&(!c.year||Number(c.year)<intent.minYear))return false;if(intent.maxYear&&(!c.year||Number(c.year)>intent.maxYear))return false;if(intent.maxPrice&&(!c.priceVerified||c.price==null||Number(c.price)>intent.maxPrice))return false;if(intent.maxMileage&&(c.mileage==null||Number(c.mileage)>intent.maxMileage))return false;if(intent.city&&norm(c.city||'')!==norm(intent.city))return false;if(intent.seller&&norm(c.seller||c.source||'')!==norm(intent.seller))return false;if(intent.sourceType&&String(c.sourceType||'')!==intent.sourceType)return false;return true}

function parseSyarahPricing(text=''){const x=digits(text).replace(/\s+/g,' ');let m=x.match(/Cash\s*Price\s*(?:\(\s*Includes\s*VAT\s*\))?[^0-9]{0,80}([0-9][\d,]*)\s*SAR(?:\s+([0-9][\d,]*)\s*SAR)?/i);if(!m)m=x.match(/السعر\s*النقدي[^0-9]{0,80}([0-9][\d,]*)\s*(?:ر\.?س|ريال)(?:\s+([0-9][\d,]*)\s*(?:ر\.?س|ريال))?/i);const discounted=m?money(m[1]):null,second=m&&m[2]?money(m[2]):null,original=second&&discounted&&second>discounted?second:discounted;return{discounted,original,discountAmount:original&&discounted&&original>discounted?original-discounted:null}}
async function exactSyarah(car){if(!car||car.source!=='Syarah'||!isDirectSyarah(car.url))return car;const key=canonical(car.url),hit=syarahCache.get(key);if(hit&&Date.now()-hit.at<SYARAH_CACHE_TTL)return{...car,...hit.exact};try{const r=await fetch(key,{redirect:'follow',signal:AbortSignal.timeout(7500),headers:{'User-Agent':'Mozilla/5.0 (compatible; DelilahSyarahVerifier/5.0)',Accept:'text/html,application/xhtml+xml'}});if(!r.ok||!isDirectSyarah(r.url||key))throw new Error(`HTTP ${r.status}`);const html=(await r.text()).slice(0,3_200_000),text=stripHtml(html).slice(0,180000),pricing=parseSyarahPricing(text),title=titleFrom(html),exact={url:canonical(r.url||key),syarahExactVerified:true,syarahVerifiedAt:new Date().toISOString()};if(title)exact.title=title;if(pricing.original){exact.price=pricing.original;exact.originalPrice=pricing.original;exact.discountedPrice=pricing.discounted;exact.discountAmount=pricing.discountAmount;exact.priceVerified=true;exact.priceSource='syarah_original_pre_discount_price'}else{exact.price=null;exact.priceVerified=false;exact.priceSource=null;exact.originalPrice=null;exact.discountedPrice=null;exact.discountAmount=null}syarahCache.set(key,{at:Date.now(),exact});return{...car,...exact}}catch{const exact={price:null,priceVerified:false,priceSource:null,originalPrice:null,discountedPrice:null,discountAmount:null,syarahExactVerified:false};syarahCache.set(key,{at:Date.now(),exact});return{...car,...exact}}}
async function enrichSyarah(d={},phase='full'){if(!Array.isArray(d.listings))return d;const out=[...d.listings],limit=phase==='fast'?10:36,targets=out.map((c,i)=>c?.source==='Syarah'&&i<limit?i:-1).filter(i=>i>=0);let cursor=0;async function worker(){for(;;){const p=cursor++;if(p>=targets.length)return;const i=targets[p];out[i]=await exactSyarah(out[i])}}await Promise.all(Array.from({length:Math.min(8,targets.length||1)},worker));return{...d,listings:out}}
function explain(intent,count){const bits=[intent.condition==='new'?'New':'Used'];if(intent.brand)bits.push(intent.brand);if(intent.model)bits.push(intent.model);if(intent.minYear&&intent.maxYear)bits.push(`${intent.minYear}–${intent.maxYear}`);else if(intent.minYear)bits.push(`${intent.minYear}+`);else if(intent.maxYear)bits.push(`≤ ${intent.maxYear}`);if(intent.maxPrice)bits.push(`≤ ${intent.maxPrice.toLocaleString('en-US')} SAR`);if(intent.maxMileage)bits.push(`≤ ${intent.maxMileage.toLocaleString('en-US')} km`);if(intent.city)bits.push(intent.city);return `Understood: ${bits.join(' · ')}. ${count} verified exact-match listing${count===1?'':'s'} found.`}
function finalize(d={},body={}){const intent=parseIntent(body),listings=(Array.isArray(d.listings)?d.listings:[]).filter(c=>semanticMatch(c,intent));const counts=listings.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{});return{...d,listings,counts,answer:explain(intent,listings.length),understanding:intent,aiSearchUnderstanding:true,exactModelIdentity:true,syarahOriginalPricePolicy:true,product:{...(d.product||{}),version:'v25',verifiedListings:listings.length,verifiedPrices:listings.filter(x=>x.priceVerified).length,verifiedImages:listings.filter(x=>x.imageVerified).length,sources:Object.keys(counts).length,syarahExact:listings.filter(x=>x.source==='Syarah'&&x.syarahExactVerified).length}}}
async function upstream(pathname,opts={}){const r=await fetch(`http://127.0.0.1:${v24Port}${pathname}`,{...opts,signal:opts.signal||AbortSignal.timeout(40000)});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text.slice(0,500)}}return{r,d}}
app.post('/api/search',async(req,res)=>{const body=req.body||{};try{let{r,d}=await upstream('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(body.phase==='fast'?20000:40000)});if(!r.ok)return res.status(r.status).json(d);if(d.searchId)bodyById.set(d.searchId,{...body,_at:Date.now()});d=await enrichSyarah(d,body.phase||'full');return res.json(finalize(d,body))}catch(e){return res.status(502).json({error:e?.message||'Delilah semantic search unavailable'})}});
app.get('/api/search/progress/:id',async(req,res)=>{try{let{r,d}=await upstream(`/api/search/progress/${encodeURIComponent(req.params.id)}`,{signal:AbortSignal.timeout(22000)});if(!r.ok)return res.status(r.status).json(d);const body=bodyById.get(req.params.id)||{};d=await enrichSyarah(d,'full');return res.json(finalize(d,body))}catch(e){return res.status(502).json({error:e?.message||'Search progress unavailable'})}});
app.post('/api/understand',(req,res)=>res.json({ok:true,understanding:parseIntent(req.body||{}),engine:'semantic-intent-v25'}));
app.get('/api/health',async(req,res)=>{try{const{r,d}=await upstream('/api/health',{signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('health');return res.json({...d,edge:'product-v25',logic:'semantic-intent-exact-identity-v25',fullProduct:true,aiSearchUnderstanding:true,exactModelIdentity:true,syarahOriginalPricePolicy:true,frontend:'product-v24'})}catch{return res.status(503).json({ok:false,edge:'product-v25'})}});
app.get('/',async(req,res)=>{try{const r=await fetch(`http://127.0.0.1:${v24Port}/`,{signal:AbortSignal.timeout(8000)}),html=await r.text();res.setHeader('cache-control','no-store');return res.type('html').send(html.replace('</body>','<script src="/hotfix-v25.js"></script></body>'))}catch{return res.status(502).send('Delilah frontend unavailable')}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','content-length','connection'].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(','):String(v);let body;if(!['GET','HEAD'].includes(req.method)&&req.is('application/json')){body=JSON.stringify(req.body||{});headers['content-type']='application/json'}const r=await fetch(`http://127.0.0.1:${v24Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:'manual',signal:AbortSignal.timeout(40000)}),buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:'Delilah upstream unavailable'})}}
app.use(proxy);
setInterval(()=>{const now=Date.now();for(const[k,b]of bodyById)if(!b?._at||now-b._at>60*60_000)bodyById.delete(k);for(const[k,v]of syarahCache)if(now-v.at>SYARAH_CACHE_TTL)syarahCache.delete(k)},10*60_000).unref();
app.listen(externalPort,()=>console.log(`Delilah semantic product-v25 running at http://localhost:${externalPort}`));
