import express from "express";
import path from "path";
import {readFile} from "fs/promises";

const externalPort=Number(process.env.PORT||3000);
const v23Port=Number(process.env.DELILAH_V23_PORT||4800);
process.env.PORT=String(v23Port);
await import("./server-v23.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const bodyById=new Map();
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
const n=v=>{const x=Number(v);return Number.isFinite(x)&&x>0?x:null};
const norm=s=>digits(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim();
function humanNumbers(s=""){let q=digits(s);q=q.replace(/(\d+(?:\.\d+)?)\s*(?:ألف|الف)(?=\s|$|ريال|ر\.?س)/gi,(_,x)=>String(Math.round(Number(x)*1000)));q=q.replace(/(\d+(?:\.\d+)?)\s*[kK](?=\s|$|SAR|ريال|ر\.?س)/g,(_,x)=>String(Math.round(Number(x)*1000)));return q}
function cityOf(q=""){const x=norm(q);if(/\briyadh\b|الرياض/.test(x))return"Riyadh";if(/\bjeddah\b|جده/.test(x))return"Jeddah";if(/\bdammam\b|الدمام/.test(x))return"Dammam";if(/\bkhobar\b|الخبر/.test(x))return"Khobar";if(/\bmakkah\b|\bmecca\b|مكه/.test(x))return"Makkah";if(/\bmadinah\b|\bmedina\b|المدينه/.test(x))return"Madinah";return null}
function effectiveFilters(body={}){const f=body.filters&&typeof body.filters==='object'?body.filters:{},q=humanNumbers(String(body.query||'')),x=norm(q),years=[...q.matchAll(/\b(20\d{2})\b/g)].map(m=>Number(m[1]));const km=x.match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{2,7})\b\s*(?:km|كم|كيلو)/i);const price=x.match(/(?:under|below|less than|budget|تحت|اقل|أقل|ميزانيه|ميزانية)\s*(\d{4,7})\b(?!\s*(?:km|كم|كيلو))/i);return{minYear:n(f.minYear)||(years.length?Math.min(...years):null),maxYear:n(f.maxYear),maxPrice:n(f.maxPrice)||(price?n(price[1]):null),maxMileage:n(f.maxMileage)||(km?n(km[1]):null),city:String(f.city||cityOf(q)||'').trim()||null,seller:String(f.seller||'').trim()||null,sourceType:String(f.sourceType||'').trim()||null,sort:String(f.sort||'best')}}
function canonical(v=""){try{const u=new URL(v);u.hash='';for(const k of[...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}}
function strictMatch(c,body,f){if(!c?.url||c.saleVerified!==true)return false;const condition=body.condition||'used';if(c.condition!==condition)return false;if(f.minYear&&(!c.year||Number(c.year)<f.minYear))return false;if(f.maxYear&&(!c.year||Number(c.year)>f.maxYear))return false;if(f.maxPrice&&(!c.priceVerified||c.price==null||Number(c.price)>f.maxPrice))return false;if(f.maxMileage&&(c.mileage==null||Number(c.mileage)>f.maxMileage))return false;if(f.city&&norm(c.city||'')!==norm(f.city))return false;if(f.seller&&norm(c.seller||c.source||'')!==norm(f.seller))return false;if(f.sourceType&&String(c.sourceType||'')!==f.sourceType)return false;return true}
function productize(d={},body={}){const f=effectiveFilters(body),seen=new Map();for(const raw of Array.isArray(d.listings)?d.listings:[]){if(!strictMatch(raw,body,f))continue;const c={...raw};c.url=canonical(c.url);if(!c.priceVerified)c.price=null;if(!c.imageVerified){c.image=null;c.displayImage=null}c.seller=c.seller||c.source||'Seller';c.source=c.source||c.seller||'Source';c.productCompleteness=[c.year!=null,c.priceVerified===true,c.imageVerified===true,c.city,c.mileage!=null].filter(Boolean).length;c.productScore=Number(c.score||0)+c.productCompleteness*1.5;const old=seen.get(c.url);if(!old||c.productScore>old.productScore)seen.set(c.url,c)}let listings=[...seen.values()];const unknownLast=(a,b,key,dir=1)=>{const av=a[key],bv=b[key];if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return-1;return(Number(av)-Number(bv))*dir};if(f.sort==='price_asc')listings.sort((a,b)=>unknownLast(a,b,'price',1));else if(f.sort==='price_desc')listings.sort((a,b)=>unknownLast(a,b,'price',-1));else if(f.sort==='year_desc')listings.sort((a,b)=>unknownLast(a,b,'year',-1));else if(f.sort==='mileage_asc')listings.sort((a,b)=>unknownLast(a,b,'mileage',1));else listings.sort((a,b)=>b.productScore-a.productScore);const sources={};for(const c of listings)sources[c.source]=(sources[c.source]||0)+1;return{...d,listings,counts:sources,effectiveFilters:f,product:{version:'v24',verifiedListings:listings.length,verifiedPrices:listings.filter(x=>x.priceVerified).length,verifiedImages:listings.filter(x=>x.imageVerified).length,sources:Object.keys(sources).length,officialDealers:listings.filter(x=>x.sourceType==='official_dealer').length,certifiedUsed:listings.filter(x=>x.sourceType==='certified_used').length,marketplaces:listings.filter(x=>x.sourceType==='marketplace').length},strictVerifiedFilters:true}}
async function jsonUpstream(pathname,opts={}){const r=await fetch(`http://127.0.0.1:${v23Port}${pathname}`,{...opts,signal:opts.signal||AbortSignal.timeout(30000)});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text.slice(0,400)}}return{r,d}}
app.post('/api/search',async(req,res)=>{const body=req.body||{};try{const{r,d}=await jsonUpstream('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(body.phase==='fast'?15000:32000)});if(!r.ok)return res.status(r.status).json(d);if(d.searchId)bodyById.set(d.searchId,{...body,_at:Date.now()});return res.json(productize(d,body))}catch(e){return res.status(502).json({error:e?.message||'Delilah search unavailable'})}});
app.get('/api/search/progress/:id',async(req,res)=>{try{const{r,d}=await jsonUpstream(`/api/search/progress/${encodeURIComponent(req.params.id)}`,{signal:AbortSignal.timeout(15000)});if(!r.ok)return res.status(r.status).json(d);return res.json(productize(d,bodyById.get(req.params.id)||{}))}catch(e){return res.status(502).json({error:e?.message||'Search progress unavailable'})}});
app.get('/api/health',async(req,res)=>{try{const{r,d}=await jsonUpstream('/api/health',{signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error('health');return res.json({...d,edge:'product-v24',logic:'verified-search-product-v24',fullProduct:true,strictVerifiedFilters:true,frontend:'product-v24'})}catch{return res.status(503).json({ok:false,edge:'product-v24'})}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','content-length','connection'].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(','):String(v);let body;if(!['GET','HEAD'].includes(req.method)&&req.is('application/json')){body=JSON.stringify(req.body||{});headers['content-type']='application/json'}const r=await fetch(`http://127.0.0.1:${v23Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:'manual',signal:AbortSignal.timeout(35000)});const buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:'Delilah upstream unavailable'})}}
app.use(express.static('public',{index:false,maxAge:'5m'}));
app.get('/',async(req,res)=>{try{const html=await readFile(path.resolve('public/product-v24.html'),'utf8');res.setHeader('cache-control','no-store');return res.type('html').send(html.replace('</body>','<script src="/hotfix-v24.js"></script></body>'))}catch{return res.sendFile(path.resolve('public/product-v24.html'))}});
app.use('/api',proxy);
app.use((req,res)=>res.redirect('/'));
setInterval(()=>{const now=Date.now();for(const[k,b]of bodyById)if(!b?._at||now-b._at>60*60_000)bodyById.delete(k)},10*60_000).unref();
app.listen(externalPort,()=>console.log(`Delilah product-v24 running at http://localhost:${externalPort}`));
