import express from "express";

const externalPort=Number(process.env.PORT||3000);
const v11Port=Number(process.env.DELILAH_V11_PORT||3600);
const MAX_PAGES=30;
const REFRESH_MS=20*60_000;
const FETCH_TIMEOUT=7000;
const MAX_RESULTS=200;
const motory=new Map();
let refreshing=false,lastRefreshStarted=null,lastRefreshFinished=null,lastRefreshError=null,pagesFetched=0;

process.env.PORT=String(v11Port);
await import("./server-v11.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
function humanNumbers(s=""){let q=digits(s);q=q.replace(/(\d+(?:\.\d+)?)\s*(?:ألف|الف)(?=\s|$|ريال|ر\.?س)/gi,(_,n)=>String(Math.round(Number(n)*1000)));q=q.replace(/(\d+(?:\.\d+)?)\s*[kK](?=\s|$|SAR|ريال|ر\.?س)/g,(_,n)=>String(Math.round(Number(n)*1000)));return q}
function norm(s=""){return humanNumbers(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim()}
function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u:null}catch{return null}}
function absolute(v,b){try{return new URL(String(v||"").replace(/&amp;/g,"&"),b).href}catch{return null}}
function decodeHtml(s=""){return String(s).replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
function strip(s=""){return decodeHtml(String(s)).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function directMotory(url){try{const u=new URL(url);if(!(u.hostname==="motory.com"||u.hostname.endsWith(".motory.com")))return null;const p=decodeURIComponent(u.pathname);const m=p.match(/^\/en\/cars-for-sale\/(?:(.+?)-haraj\/)?([^/]+)\/([^/]+)\/(20\d{2})\/(\d+)\/?$/i);return m?{citySlug:m[1]||null,brandSlug:m[2],modelSlug:m[3],year:Number(m[4]),id:m[5]}:null}catch{return null}}
function titleCase(s=""){return s.split(/[-_]+/).filter(Boolean).map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" ")}
function cityOf(text=""){const t=norm(text);if(/\briyadh\b|الرياض/.test(t))return"Riyadh";if(/\bjeddah\b|جده/.test(t))return"Jeddah";if(/\bdammam\b|الدمام/.test(t))return"Dammam";if(/\bkhobar\b|الخبر/.test(t))return"Khobar";if(/\bmakkah\b|\bmecca\b|مكه/.test(t))return"Makkah";if(/\bmadinah\b|\bmedina\b|المدينه/.test(t))return"Madinah";if(/\babha\b|ابها/.test(t))return"Abha";if(/\btaif\b|الطايف/.test(t))return"Taif";return null}
function cashPrice(text=""){const t=digits(text);const m=t.match(/Cash\s*Price(?:\s*with\s*VAT)?[^0-9]{0,35}([0-9][\d,]*)/i)||t.match(/السعر\s*النقدي[^0-9]{0,40}([0-9][\d,]*)/i);if(!m)return null;const n=Number(m[1].replace(/,/g,""));return Number.isFinite(n)&&n>=1000&&n<=5_000_000?n:null}
function mileageOf(text=""){const t=digits(text);if(/[0-9][\d,]*\s*-\s*[0-9][\d,]*\s*(?:km|kilometers?)/i.test(t))return null;const m=t.match(/([0-9][\d,]{0,8})\s*(?:km|kilometers?)/i);if(!m)return null;const n=Number(m[1].replace(/,/g,""));return Number.isFinite(n)&&n>=0&&n<=1_500_000?n:null}
function attr(tag,name){const m=new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,`i`).exec(tag);return m?decodeHtml(m[1]):null}
function imageOkay(url=""){const u=safeUrl(url);if(!u)return false;return !/(logo|favicon|icon|placeholder|sprite|social|share|banner|brandmark|default[-_]?image|nitrous)/i.test(u.href)}
function bestImage(segment,base){const a=[];for(const m of String(segment).matchAll(/<(?:img|source)\b[^>]*>/gi)){const tag=m[0];for(const k of["src","data-src","data-lazy-src","data-original","data-image"]){const u=absolute(attr(tag,k),base);if(u&&imageOkay(u))a.push(u)}const ss=attr(tag,"srcset")||attr(tag,"data-srcset");if(ss)for(const p of ss.split(",")){const u=absolute(p.trim().split(/\s+/)[0],base);if(u&&imageOkay(u))a.push(u)}}return a.find(Boolean)||null}
function cardCandidates(html,base){const raw=[];for(const m of String(html).matchAll(/<a\b([^>]*href=["'][^"']+["'][^>]*)>([\s\S]*?)<\/a>/gi)){const href=/href=["']([^"']+)["']/i.exec(m[1])?.[1],url=absolute(href,base),d=directMotory(url);if(d)raw.push({m,url,d,index:m.index||0})}const out=[],seen=new Set();for(let i=0;i<raw.length;i++){const r=raw[i];if(seen.has(r.d.id))continue;seen.add(r.d.id);const next=raw[i+1]?.index||Math.min(String(html).length,r.index+7500),seg=String(html).slice(r.index,Math.min(next,r.index+7500)),anchor=strip(r.m[2]),context=strip(seg).slice(0,2400),text=`${anchor} ${context}`.trim();out.push({id:r.d.id,url:r.url,condition:"used",brand:titleCase(r.d.brandSlug),model:titleCase(r.d.modelSlug),year:r.d.year,city:cityOf(`${r.d.citySlug||""} ${text}`),mileage:mileageOf(text),price:cashPrice(text),image:bestImage(seg,base),title:anchor.length>4?anchor.slice(0,500):`${titleCase(r.d.brandSlug)} ${titleCase(r.d.modelSlug)} ${r.d.year}`,text,indexedAt:Date.now()})}return out}
async function fetchText(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),FETCH_TIMEOUT);try{const r=await fetch(url,{signal:c.signal,redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 (compatible; DelilahCatalogIndexer/1.0)",Accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ct=(r.headers.get("content-type")||"").toLowerCase();if(!ct.includes("text/html"))throw new Error(`Unexpected ${ct}`);return{html:(await r.text()).slice(0,3_000_000),url:r.url||url}}finally{clearTimeout(t)}}
async function crawlPage(page){const u=new URL("https://ksa.motory.com/en/cars-for-sale/");if(page>1)u.searchParams.set("page",String(page));const d=await fetchText(u.href),cards=cardCandidates(d.html,d.url);for(const c of cards){const old=motory.get(c.id);motory.set(c.id,old?{...old,...c,image:old.image||c.image,price:old.price||c.price}:{...c})}pagesFetched++;return cards.length}
async function refresh(){if(refreshing)return;refreshing=true;lastRefreshStarted=new Date().toISOString();lastRefreshError=null;pagesFetched=0;try{let noNew=0,previous=motory.size;for(let p=1;p<=MAX_PAGES;p++){try{await crawlPage(p)}catch(e){lastRefreshError=`page ${p}: ${e?.message||e}`};const now=motory.size;if(now===previous)noNew++;else noNew=0;previous=now;if(p>=6&&noNew>=3)break;await sleep(250)}lastRefreshFinished=new Date().toISOString()}catch(e){lastRefreshError=e?.message||String(e)}finally{refreshing=false}}

const STOP=new Set(norm("ابي ابغى أبغى اريد أريد سيارة سياره سيارات cars car vehicle vehicles used مستعمل مستعملة مستعمله موديل model سنة سنه years year وفوق فوق واكثر وأكثر تحت اقل أقل من الى إلى في بالرياض الرياض بجدة بجده جدة جده بالدمام الدمام السعودية السعوديه saudi arabia ksa riyadh jeddah dammam under below less than above over more than around about budget ريال sar km كيلو كم").split(" "));
function queryTerms(q=""){return[...new Set(norm(q).split(" ").filter(t=>t.length>=2&&!STOP.has(t)&&!/^\d+$/.test(t)))].slice(0,8)}
function intent(query="",filters={}){const q=humanNumbers(query),years=[...q.matchAll(/\b(20\d{2})\b/g)].map(x=>Number(x[1])),p=norm(q).match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{4,7})/i),km=norm(q).match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{2,7})\s*(?:km|كم|كيلو)/i);return{terms:queryTerms(q),minYear:Number(filters.minYear)||(years.length?Math.min(...years):null),maxYear:Number(filters.maxYear)||null,maxPrice:Number(filters.maxPrice)||(p?Number(p[1]):null),maxMileage:Number(filters.maxMileage)||(km?Number(km[1]):null),city:filters.city||cityOf(q)}}
function blob(c){return norm(`${c.brand||""} ${c.model||""} ${c.title||""} ${c.text||""} ${c.url||""}`)}
function matches(c,i){const b=blob(c),compact=b.replace(/\s+/g,"");if(!i.terms.every(t=>b.includes(t)||compact.includes(t.replace(/\s+/g,""))))return false;if(i.minYear&&c.year&&c.year<i.minYear)return false;if(i.maxYear&&c.year&&c.year>i.maxYear)return false;if(i.maxPrice&&c.price&&c.price>i.maxPrice)return false;if(i.maxMileage&&c.mileage!=null&&c.mileage>i.maxMileage)return false;if(i.city&&c.city&&c.city!==i.city)return false;return true}
function generic(body={},limit=MAX_RESULTS){const condition=body.condition==="new"?"new":"used",filters=body.filters&&typeof body.filters==="object"?body.filters:{};if(condition!=="used")return[];if((filters.seller&&filters.seller!=="Motory")||(filters.sourceType&&filters.sourceType!=="marketplace"))return[];const i=intent(String(body.query||""),filters);return[...motory.values()].filter(c=>matches(c,i)).sort((a,b)=>(Boolean(b.price)-Boolean(a.price))||(Boolean(b.image)-Boolean(a.image))||(b.indexedAt-a.indexedAt)).slice(0,limit).map(c=>({source:"Motory",sourceType:"marketplace",seller:"Motory",sourceStrict:true,title:c.title,snippet:c.text.slice(0,700),url:c.url,brand:c.brand,model:c.model,year:c.year,mileage:c.mileage,city:c.city,price:c.price,priceVerified:Boolean(c.price),priceSource:c.price?"motory_cash_price_catalog":null,condition:"used",saleVerified:true,image:c.image||null,displayImage:c.image||null,imageVerified:Boolean(c.image),imageSource:c.image?"source_catalog":null,score:Math.min(95,72+i.terms.length*3+(c.price?5:0)+(c.image?5:0)),discovery:"broad_catalog_index"}))}
function merge(a=[],b=[],max=MAX_RESULTS){const out=[],seen=new Set();for(const c of[...a,...b]){if(!c?.url)continue;const k=String(c.url).replace(/\/$/,"");if(seen.has(k))continue;seen.add(k);out.push(c);if(out.length>=max)break}return out}
function counts(xs=[]){return xs.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{})}
async function upstream(path,opts={}){const r=await fetch(`http://127.0.0.1:${v11Port}${path}`,opts),ct=r.headers.get("content-type")||"";return{r,ct}}

app.post("/api/search",async(req,res)=>{const body=req.body||{},fast=body.phase==="fast",extra=generic(body,fast?18:MAX_RESULTS);try{const {r}=await upstream("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({error:`Upstream HTTP ${r.status}`}));if(!r.ok){if(extra.length)return res.json({query:body.query,condition:"used",listings:extra,counts:counts(extra),live:true,partial:fast,phase:fast?"fast":"full",fallback:"motory_broad_catalog",motoryIndexed:motory.size});return res.status(r.status).json(d)}const base=Array.isArray(d.listings)?d.listings:[],listings=merge(base,extra,fast?18:MAX_RESULTS);return res.json({...d,listings,counts:counts(listings),motoryIndexed:motory.size,broadSources:[...new Set([...(d.broadSources||[]),"Syarah","Motory"]) ]})}catch(e){if(extra.length)return res.json({query:body.query,condition:"used",listings:extra,counts:counts(extra),live:true,partial:fast,phase:fast?"fast":"full",fallback:"motory_broad_catalog",motoryIndexed:motory.size});return res.status(502).json({error:e?.message||"Delilah upstream unavailable"})}});

app.get("/api/catalog/stats",async(req,res)=>{let upstreamStats={};try{const {r}=await upstream("/api/catalog/stats");if(r.ok)upstreamStats=await r.json()}catch{}const vals=[...motory.values()],samples=vals.slice(0,10).map(c=>({title:c.title,condition:"used",url:c.url,source:"Motory"}));res.json({...upstreamStats,ok:true,index:"broad-catalog-v2",syarahIndexed:Number(upstreamStats.indexed||0),motoryIndexed:vals.length,totalIndexed:Number(upstreamStats.indexed||0)+vals.length,motoryWithImages:vals.filter(c=>c.image).length,motoryWithPrices:vals.filter(c=>c.price).length,motoryPagesFetched:pagesFetched,motoryRefreshing:refreshing,motoryLastRefreshStarted:lastRefreshStarted,motoryLastRefreshFinished:lastRefreshFinished,motoryLastRefreshError:lastRefreshError,motorySamples:samples})});
app.get("/api/health",async(req,res)=>{try{const {r}=await upstream("/api/health"),d=await r.json();res.json({...d,edge:"inventory-v12",broadCatalogSources:["Syarah","Motory"],motoryIndexed:motory.size,motoryRefreshing:refreshing})}catch{res.status(503).json({ok:false,edge:"inventory-v12",motoryIndexed:motory.size})}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!["host","content-length","connection"].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(","):String(v);let body;if(!["GET","HEAD"].includes(req.method)&&req.is("application/json")){body=JSON.stringify(req.body||{});headers["content-type"]="application/json"}const {r}=await upstream(req.originalUrl,{method:req.method,headers,body,redirect:"manual"}),buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!["content-length","transfer-encoding","connection"].includes(k.toLowerCase()))res.setHeader(k,v);res.status(r.status).send(buf)}catch{res.status(502).json({error:"Delilah upstream unavailable"})}}
app.use(proxy);
app.listen(externalPort,()=>{console.log(`Delilah inventory-v12 running at http://localhost:${externalPort}`);refresh().catch(()=>{});setInterval(()=>refresh().catch(()=>{}),REFRESH_MS).unref()});
