import express from "express";

const externalPort=Number(process.env.PORT||3000);
const v22Port=Number(process.env.DELILAH_V22_PORT||4700);
const FETCH_TIMEOUT=7000;
const PRICE_TTL=15*60_000;
const MODEL_TTL=10*60_000;
process.env.PORT=String(v22Port);
await import("./server-v22.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const priceCache=new Map(),modelCache=new Map(),bodyById=new Map();
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
function norm(s=""){return digits(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim()}
function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u:null}catch{return null}}
function absolute(v,b){try{return new URL(String(v||"").replace(/&amp;/g,"&"),b).href}catch{return null}}
function canonical(v=""){const u=safeUrl(v);if(!u)return v;u.hash="";for(const k of[...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,"")}
function decodeHtml(s=""){return String(s).replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
function strip(s=""){return decodeHtml(String(s)).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function attr(tag,name){return new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,`i`).exec(tag)?.[1]||null}
function number(v,min=0,max=5_000_000){const n=Number(String(v||"").replace(/[^0-9.]/g,""));return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function yearOf(t=""){const m=digits(t).match(/\b(20\d{2})\b/),y=m?Number(m[1]):null;return y&&y>=2000&&y<=2035?y:null}
function cityOf(t=""){const x=norm(t);if(/riyadh|الرياض/.test(x))return"Riyadh";if(/jeddah|جده/.test(x))return"Jeddah";if(/dammam|الدمام/.test(x))return"Dammam";if(/khobar|الخبر/.test(x))return"Khobar";if(/makkah|mecca|مكه/.test(x))return"Makkah";if(/madinah|medina|المدينه/.test(x))return"Madinah";return null}
function imageOkay(u=""){return /^https?:\/\//i.test(u)&&!/(logo|favicon|icon|placeholder|sprite|social|share|banner|brandmark|default[-_]?image|discount|coupon|avatar|profile)/i.test(u)}
function bestImage(seg,base){for(const m of String(seg).matchAll(/<(?:img|source)\b[^>]*>/gi)){const tag=m[0];for(const k of["src","data-src","data-lazy-src","data-original","data-image"]){const u=absolute(attr(tag,k),base);if(u&&imageOkay(u))return u}const ss=attr(tag,"srcset")||attr(tag,"data-srcset");if(ss)for(const p of ss.split(",")){const u=absolute(p.trim().split(/\s+/)[0],base);if(u&&imageOkay(u))return u}}return null}
function directSyarah(u=""){const x=safeUrl(u);return!!x&&(x.hostname==="syarah.com"||x.hostname.endsWith(".syarah.com"))&&/^\/(?:(?:en|ar)\/)?cardetail\/[^/]+-(?:used|new)-\d+\/?$/i.test(x.pathname)}
function directArabNew(u=""){const x=safeUrl(u);return!!x&&(x.hostname==="arabwheels.sa"||x.hostname==="www.arabwheels.sa")&&/^\/(?:en\/)?new-cars-sale\/[^/]+-for-sale-in-[^/]+-\d+\/?$/i.test(x.pathname)}
function cashPrice(t=""){const x=digits(t),m=x.match(/Cash\s*Price\s*(?:\(\s*Includes\s*VAT\s*\))?[^0-9]{0,50}([0-9][\d,]*)\s*SAR/i)||x.match(/السعر\s*النقدي[^0-9]{0,60}([0-9][\d,]*)\s*(?:ر\.?س|ريال)/i);return m?number(m[1],1000):null}
async function html(url){const r=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(FETCH_TIMEOUT),headers:{"User-Agent":"Mozilla/5.0 (compatible; DelilahVerifier/3.0)",Accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ct=(r.headers.get("content-type")||"").toLowerCase();if(!ct.includes("text/html"))throw new Error(`Unexpected ${ct}`);return{html:(await r.text()).slice(0,3_200_000),url:r.url||url}}
async function exactSyarah(url){const key=canonical(url),hit=priceCache.get(key);if(hit&&Date.now()-hit.at<PRICE_TTL)return hit.price;try{const d=await html(key);if(!directSyarah(d.url||key))throw new Error("redirect");const p=cashPrice(strip(d.html));priceCache.set(key,{at:Date.now(),price:p});return p}catch{priceCache.set(key,{at:Date.now(),price:null});return null}}
async function guardPrices(listings=[]){const out=[...listings],targets=[];for(let i=0;i<out.length;i++){const c=out[i];if(c?.source==='Syarah'&&c.price!=null&&(!c.priceVerified||!/^syarah_.*cash.*price$/i.test(String(c.priceSource||''))))targets.push(i)}let next=0;async function worker(){for(;;){const k=next++;if(k>=targets.length)return;const i=targets[k],c={...out[i]},p=await exactSyarah(c.url);if(p){c.price=p;c.priceVerified=true;c.priceSource='syarah_exact_cash_price'}else{c.price=null;c.priceVerified=false;c.priceSource=null;delete c.previousPrice;delete c.discount}out[i]=c}}await Promise.all(Array.from({length:Math.min(4,targets.length||1)},worker));return out}
const alias=new Map([["شانجان","changan"],["تويوتا","toyota"],["نيسان","nissan"],["هوندا","honda"],["هيونداي","hyundai"],["كيا","kia"],["هافال","haval"],["جيلي","geely"],["جيتور","jetour"],["مازدا","mazda"],["فورد","ford"],["جيب","jeep"],["مرسيدس","mercedes-benz"],["بي ام","bmw"],["سي اس 75","cs75"],["كولراي","coolray"],["توسان","tucson"],["باترول","patrol"],["كامري","camry"]]);
const knownBrands=['changan','toyota','nissan','honda','hyundai','kia','haval','geely','jetour','mazda','ford','jeep','mercedes-benz','bmw','audi','lexus','porsche','volkswagen'];
function identity(q=""){let x=norm(q);for(const[a,b]of[...alias.entries()].sort((m,n)=>n[0].length-m[0].length))x=x.replaceAll(norm(a),b.replace(/-/g,' '));const brand=knownBrands.find(b=>x.includes(b.replace(/-/g,' ')))||null;if(!brand)return{brand:null,model:null};const toks=x.split(' ').filter(Boolean),bw=brand.replace(/-/g,' ').split(' ');for(let i=0;i<=toks.length-bw.length;i++)if(bw.every((w,j)=>toks[i+j]===w)){toks.splice(i,bw.length);break}const stop=new Set(['new','used','car','cars','saudi','arabia','ksa','riyadh','jeddah','dammam','under','below','above','over']);const model=toks.filter(t=>!stop.has(t)&&!/^\d/.test(t)).slice(0,3).join('-')||null;return{brand,model}}
function titleCase(s=""){return String(s||'').split('-').map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(' ')}
async function arabNew(body){if(body.condition!=='new')return[];const f=body.filters&&typeof body.filters==='object'?body.filters:{};if((f.seller&&f.seller!=='ArabWheels')||(f.sourceType&&f.sourceType!=='marketplace'))return[];const id=identity(body.query);if(!id.brand||!id.model)return[];const url=`https://www.arabwheels.sa/en/new-cars/${id.brand}/${id.model}/`,hit=modelCache.get(url);if(hit&&Date.now()-hit.at<MODEL_TTL)return hit.cars;try{const d=await html(url),raw=[];for(const m of String(d.html).matchAll(/<a\b([^>]*href=["'][^"']+["'][^>]*)>([\s\S]*?)<\/a>/gi)){const href=/href=["']([^"']+)["']/i.exec(m[1])?.[1],u=absolute(href,d.url);if(u&&directArabNew(u))raw.push({m,u:canonical(u),i:m.index||0})}const seen=new Set(),cars=[];for(let i=0;i<raw.length;i++){const r=raw[i];if(seen.has(r.u))continue;seen.add(r.u);const next=raw[i+1]?.i||Math.min(d.html.length,r.i+6500),seg=d.html.slice(r.i,Math.min(next,r.i+6500)),a=strip(r.m[2]),text=`${a} ${strip(seg).slice(0,1800)}`,image=bestImage(seg,d.url),year=yearOf(text);cars.push({source:'ArabWheels',sourceType:'marketplace',seller:'ArabWheels',sourceStrict:true,title:a||`${titleCase(id.brand)} ${titleCase(id.model)}`,snippet:text.slice(0,700),url:r.u,brand:titleCase(id.brand),model:titleCase(id.model),year,mileage:null,city:cityOf(text),price:null,priceVerified:false,priceSource:null,condition:'new',saleVerified:true,saleEvidence:['direct_new_car_sale_url','source_model_page'],image,displayImage:image,imageVerified:Boolean(image),imageSource:image?'source_catalog':null,score:88,discovery:'arabwheels_new_source_native'})}modelCache.set(url,{at:Date.now(),cars});return cars}catch{return[]}}
function merge(a=[],b=[]){const map=new Map();for(const c of[...a,...b]){if(!c?.url||c.saleVerified!==true)continue;const k=canonical(c.url),o=map.get(k);if(!o){map.set(k,c);continue}const np=c.priceVerified&&!o.priceVerified,ni=c.imageVerified&&!o.imageVerified;map.set(k,{...o,...c,price:np?c.price:(o.price??c.price??null),priceVerified:Boolean(o.priceVerified||c.priceVerified),priceSource:np?c.priceSource:(o.priceSource||c.priceSource||null),image:ni?c.image:(o.image||c.image||null),displayImage:ni?c.displayImage:(o.displayImage||c.displayImage||null),imageVerified:Boolean(o.imageVerified||c.imageVerified),imageSource:ni?c.imageSource:(o.imageSource||c.imageSource||null)})}return[...map.values()].sort((x,y)=>(y.score||0)-(x.score||0)).slice(0,2000)}
const counts=xs=>xs.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{});
async function upstream(path,opts={}){const r=await fetch(`http://127.0.0.1:${v22Port}${path}`,{...opts,signal:opts.signal||AbortSignal.timeout(25000)}),text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text.slice(0,300)}}return{r,d}}
async function finish(d,body){const extra=await arabNew(body);let listings=merge(d.listings||[],extra);listings=await guardPrices(listings);return{...d,listings,counts:counts(listings),syarahExactPriceGuard:true,arabWheelsNewExact:true}}
app.post('/api/search',async(req,res)=>{const body=req.body||{};try{const{r,d}=await upstream('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(body.phase==='fast'?13000:25000)});if(!r.ok)return res.status(r.status).json(d);if(d.searchId)bodyById.set(d.searchId,body);return res.json(await finish(d,body))}catch(e){return res.status(502).json({error:e?.message||'Delilah search unavailable'})}});
app.get('/api/search/progress/:id',async(req,res)=>{try{const{r,d}=await upstream(`/api/search/progress/${encodeURIComponent(req.params.id)}`,{signal:AbortSignal.timeout(12000)});if(!r.ok)return res.status(r.status).json(d);const body=bodyById.get(req.params.id)||{};return res.json(await finish(d,body))}catch(e){return res.status(502).json({error:e?.message||'Search progress unavailable'})}});
app.get('/api/health',async(req,res)=>{try{const{r,d}=await upstream('/api/health',{signal:AbortSignal.timeout(6000)});if(!r.ok)throw new Error('health');return res.json({...d,edge:'inventory-v23',logic:'progressive-market-scan-v23',syarahExactPriceGuard:true,arabWheelsNewExact:true})}catch{return res.status(503).json({ok:false,edge:'inventory-v23'})}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','content-length','connection'].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(','):String(v);let body;if(!['GET','HEAD'].includes(req.method)&&req.is('application/json')){body=JSON.stringify(req.body||{});headers['content-type']='application/json'}const r=await fetch(`http://127.0.0.1:${v22Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:'manual',signal:AbortSignal.timeout(30000)}),buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:'Delilah upstream unavailable'})}}
app.use(proxy);
setInterval(()=>{const now=Date.now();for(const[k,v]of priceCache)if(now-v.at>PRICE_TTL*2)priceCache.delete(k);for(const[k,v]of modelCache)if(now-v.at>MODEL_TTL*2)modelCache.delete(k)},60000).unref();
app.listen(externalPort,()=>console.log(`Delilah inventory-v23 running at http://localhost:${externalPort}`));
