import express from "express";
import path from "path";
import {readFile} from "fs/promises";

const externalPort=Number(process.env.PORT||3000);
const v23Port=Number(process.env.DELILAH_V23_PORT||4800);
const HAR_CACHE_TTL=5*60_000;
process.env.PORT=String(v23Port);
await import("./server-v23.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const bodyById=new Map(),harajCache=new Map();
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
const n=v=>{const x=Number(v);return Number.isFinite(x)&&x>0?x:null};
const norm=s=>digits(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim();
function humanNumbers(s=""){let q=digits(s);q=q.replace(/(\d+(?:\.\d+)?)\s*(?:ألف|الف)(?=\s|$|ريال|ر\.?س)/gi,(_,x)=>String(Math.round(Number(x)*1000)));q=q.replace(/(\d+(?:\.\d+)?)\s*[kK](?=\s|$|SAR|ريال|ر\.?س)/g,(_,x)=>String(Math.round(Number(x)*1000)));return q}
function cityOf(q=""){const x=norm(q);if(/\briyadh\b|الرياض/.test(x))return"Riyadh";if(/\bjeddah\b|جده/.test(x))return"Jeddah";if(/\bdammam\b|الدمام/.test(x))return"Dammam";if(/\bkhobar\b|الخبر/.test(x))return"Khobar";if(/\bmakkah\b|\bmecca\b|مكه/.test(x))return"Makkah";if(/\bmadinah\b|\bmedina\b|المدينه/.test(x))return"Madinah";return null}
function effectiveFilters(body={}){const f=body.filters&&typeof body.filters==='object'?body.filters:{},q=humanNumbers(String(body.query||'')),x=norm(q),years=[...q.matchAll(/\b(20\d{2})\b/g)].map(m=>Number(m[1]));const km=x.match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{2,7})\b\s*(?:km|كم|كيلو)/i);const price=x.match(/(?:under|below|less than|budget|تحت|اقل|أقل|ميزانيه|ميزانية)\s*(\d{4,7})\b(?!\s*(?:km|كم|كيلو))/i);return{minYear:n(f.minYear)||(years.length?Math.min(...years):null),maxYear:n(f.maxYear),maxPrice:n(f.maxPrice)||(price?n(price[1]):null),maxMileage:n(f.maxMileage)||(km?n(km[1]):null),city:String(f.city||cityOf(q)||'').trim()||null,seller:String(f.seller||'').trim()||null,sourceType:String(f.sourceType||'').trim()||null,sort:String(f.sort||'best')}}
function canonical(v=""){try{const u=new URL(v);u.hash='';for(const k of[...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}}
function strictMatch(c,body,f){if(!c?.url||c.saleVerified!==true)return false;const condition=body.condition||'used';if(c.condition!==condition)return false;if(f.minYear&&(!c.year||Number(c.year)<f.minYear))return false;if(f.maxYear&&(!c.year||Number(c.year)>f.maxYear))return false;if(f.maxPrice&&(!c.priceVerified||c.price==null||Number(c.price)>f.maxPrice))return false;if(f.maxMileage&&(c.mileage==null||Number(c.mileage)>f.maxMileage))return false;if(f.city&&norm(c.city||'')!==norm(f.city))return false;if(f.seller&&norm(c.seller||c.source||'')!==norm(f.seller))return false;if(f.sourceType&&String(c.sourceType||'')!==f.sourceType)return false;return true}
function productize(d={},body={}){const f=effectiveFilters(body),seen=new Map();for(const raw of Array.isArray(d.listings)?d.listings:[]){if(!strictMatch(raw,body,f))continue;const c={...raw};c.url=canonical(c.url);if(!c.priceVerified)c.price=null;if(!c.imageVerified){c.image=null;c.displayImage=null}c.seller=c.seller||c.source||'Seller';c.source=c.source||c.seller||'Source';c.productCompleteness=[c.year!=null,c.priceVerified===true,c.imageVerified===true,c.city,c.mileage!=null].filter(Boolean).length;c.productScore=Number(c.score||0)+c.productCompleteness*1.5+(c.harajExactVerified?2:0);const old=seen.get(c.url);if(!old||c.productScore>old.productScore)seen.set(c.url,c)}let listings=[...seen.values()];const unknownLast=(a,b,key,dir=1)=>{const av=a[key],bv=b[key];if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return-1;return(Number(av)-Number(bv))*dir};if(f.sort==='price_asc')listings.sort((a,b)=>unknownLast(a,b,'price',1));else if(f.sort==='price_desc')listings.sort((a,b)=>unknownLast(a,b,'price',-1));else if(f.sort==='year_desc')listings.sort((a,b)=>unknownLast(a,b,'year',-1));else if(f.sort==='mileage_asc')listings.sort((a,b)=>unknownLast(a,b,'mileage',1));else listings.sort((a,b)=>b.productScore-a.productScore);const sources={};for(const c of listings)sources[c.source]=(sources[c.source]||0)+1;return{...d,listings,counts:sources,effectiveFilters:f,product:{version:'v24',verifiedListings:listings.length,verifiedPrices:listings.filter(x=>x.priceVerified).length,verifiedImages:listings.filter(x=>x.imageVerified).length,sources:Object.keys(sources).length,officialDealers:listings.filter(x=>x.sourceType==='official_dealer').length,certifiedUsed:listings.filter(x=>x.sourceType==='certified_used').length,marketplaces:listings.filter(x=>x.sourceType==='marketplace').length,harajExact:listings.filter(x=>x.source==='Haraj'&&x.harajExactVerified).length},strictVerifiedFilters:true}}

function isDirectHaraj(v=""){try{const u=new URL(v);return (u.hostname==='haraj.com.sa'||u.hostname.endsWith('.haraj.com.sa'))&&/^\/(?:en\/)?\d{8,}(?:\/[^/?#]+)?\/?$/i.test(u.pathname)}catch{return false}}
function decodeHtml(s=""){return String(s||'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function stripHtml(s=""){return decodeHtml(String(s||'')).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:property|name|itemprop)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name|itemprop)=["']${k}["'][^>]*>`,'i').exec(html);return a?decodeHtml(a[1]):null}
function abs(v,b){try{return new URL(String(v||'').replace(/&amp;/g,'&').replace(/\\u002F/gi,'/').replace(/\\\//g,'/'),b).href}catch{return null}}
function titleFrom(html=''){const h1=/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1],t=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1];return stripHtml(h1||meta(html,'og:title')||t||'').replace(/\s*\|\s*(?:Haraj|موقع حراج).*$/i,'').slice(0,240)}
function carYear(text=''){const ys=[...digits(text).matchAll(/\b(20\d{2})\b/g)].map(x=>Number(x[1])).filter(y=>y>=2000&&y<=2035);return ys[0]||null}
function priceNumber(v){const x=Number(String(v||'').replace(/[^0-9.]/g,''));return Number.isFinite(x)&&x>=5000&&x<=5_000_000?x:null}
function harajPrice(html='',text=''){for(const m of String(html).matchAll(/"price"\s*:\s*"?([0-9][\d,.]*)"?/gi)){const p=priceNumber(m[1]);if(p)return p}const d=digits(text);for(const re of[/(?:price|السعر)\s*[:：]?\s*([0-9][\d,]{3,})\s*(?:SAR|ريال|ر\.?س)?/i,/([0-9][\d,]{3,})\s*(?:SAR|ريال|ر\.?س)/i]){const m=d.match(re),p=m?priceNumber(m[1]):null;if(p)return p}return null}
function harajMileage(text=''){const d=digits(text);let m=d.match(/(?:mileage|الممشى|ممشى)\s*[:：]?\s*([0-9][\d,.]*)\s*(?:thousand|ألف|الف)\s*(?:km|kilometers?|كيلو|كم)?/i);if(m){const x=Number(m[1].replace(/,/g,''));if(Number.isFinite(x)&&x>=0&&x<2000)return Math.round(x*1000)}m=d.match(/(?:mileage|الممشى|ممشى)\s*[:：]?\s*([0-9][\d,]{0,8})\s*(?:km|kilometers?|كيلو|كم)/i);if(m){const x=Number(m[1].replace(/,/g,''));if(Number.isFinite(x)&&x>=0&&x<=1_500_000)return x}return null}
function imageOkay(u=''){try{const x=new URL(u);return /^https?:$/.test(x.protocol)&&!/(logo|favicon|icon|sprite|placeholder|avatar|profile|social|share|banner|badge)/i.test(`${x.pathname} ${x.search}`)}catch{return false}}
function harajImage(html='',base=''){for(const k of['og:image','twitter:image']){const u=abs(meta(html,k),base);if(u&&imageOkay(u))return u}for(const m of String(html).matchAll(/<(?:img|source)\b[^>]*>/gi)){const tag=m[0];for(const key of['src','data-src','data-lazy-src','data-original']){const v=new RegExp(`${key}=["']([^"']+)["']`,'i').exec(tag)?.[1],u=abs(v,base);if(u&&imageOkay(u))return u}}return null}
async function exactHaraj(car){if(!car||car.source!=='Haraj'||!isDirectHaraj(car.url))return car;const key=canonical(car.url),hit=harajCache.get(key);if(hit&&Date.now()-hit.at<HAR_CACHE_TTL)return hit.car?{...car,...hit.car}:hit.sold?null:car;try{const r=await fetch(key,{redirect:'follow',signal:AbortSignal.timeout(6500),headers:{'User-Agent':'Mozilla/5.0 (compatible; DelilahHarajVerifier/1.0)',Accept:'text/html,application/xhtml+xml'}});if(!r.ok||!isDirectHaraj(r.url||key)){harajCache.set(key,{at:Date.now(),car:null});return car}const html=(await r.text()).slice(0,3_200_000),title=titleFrom(html),text=stripHtml(html).slice(0,180000),sold=/^(?:sold|تم البيع|مباع)(?:\b|\s|$)/i.test(norm(title));if(sold){harajCache.set(key,{at:Date.now(),sold:true});return null}const exact={url:canonical(r.url||key),saleVerified:true,harajExactVerified:true,harajVerifiedAt:new Date().toISOString()};const year=carYear(`${title} ${text.slice(0,12000)}`),mileage=harajMileage(text),city=cityOf(`${title} ${text.slice(0,15000)}`),price=harajPrice(html,text),image=harajImage(html,r.url||key);if(title)exact.title=title;if(year)exact.year=year;if(mileage!=null)exact.mileage=mileage;if(city)exact.city=city;if(price){exact.price=price;exact.priceVerified=true;exact.priceSource='haraj_exact_listing_price'}if(image){exact.image=image;exact.displayImage=image;exact.imageVerified=true;exact.imageSource='haraj_exact_listing_page'}harajCache.set(key,{at:Date.now(),car:exact});return{...car,...exact}}catch{harajCache.set(key,{at:Date.now(),car:null});return car}}
async function enrichHaraj(d={},phase='full'){if(!Array.isArray(d.listings)||phase==='fast')return d;const list=d.listings,targets=list.map((c,i)=>c?.source==='Haraj'&&i<24?i:-1).filter(i=>i>=0),out=[...list];let cursor=0;async function worker(){for(;;){const p=cursor++;if(p>=targets.length)return;const i=targets[p];out[i]=await exactHaraj(out[i])}}await Promise.all(Array.from({length:Math.min(6,targets.length)},worker));return{...d,listings:out.filter(Boolean)}}

async function jsonUpstream(pathname,opts={}){const r=await fetch(`http://127.0.0.1:${v23Port}${pathname}`,{...opts,signal:opts.signal||AbortSignal.timeout(30000)});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text.slice(0,400)}}return{r,d}}
app.post('/api/search',async(req,res)=>{const body=req.body||{};try{let{r,d}=await jsonUpstream('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(body.phase==='fast'?15000:32000)});if(!r.ok)return res.status(r.status).json(d);if(d.searchId)bodyById.set(d.searchId,{...body,_at:Date.now()});d=await enrichHaraj(d,body.phase||'full');return res.json(productize(d,body))}catch(e){return res.status(502).json({error:e?.message||'Delilah search unavailable'})}});
app.get('/api/search/progress/:id',async(req,res)=>{try{let{r,d}=await jsonUpstream(`/api/search/progress/${encodeURIComponent(req.params.id)}`,{signal:AbortSignal.timeout(15000)});if(!r.ok)return res.status(r.status).json(d);const body=bodyById.get(req.params.id)||{};d=await enrichHaraj(d,'full');return res.json(productize(d,body))}catch(e){return res.status(502).json({error:e?.message||'Search progress unavailable'})}});
app.get('/api/health',async(req,res)=>{try{const{r,d}=await jsonUpstream('/api/health',{signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error('health');return res.json({...d,edge:'product-v24',logic:'verified-search-product-v24',fullProduct:true,strictVerifiedFilters:true,frontend:'product-v24',harajExactPages:true})}catch{return res.status(503).json({ok:false,edge:'product-v24'})}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','content-length','connection'].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(','):String(v);let body;if(!['GET','HEAD'].includes(req.method)&&req.is('application/json')){body=JSON.stringify(req.body||{});headers['content-type']='application/json'}const r=await fetch(`http://127.0.0.1:${v23Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:'manual',signal:AbortSignal.timeout(35000)});const buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:'Delilah upstream unavailable'})}}
app.use(express.static('public',{index:false,maxAge:'5m'}));
app.get('/',async(req,res)=>{try{const html=await readFile(path.resolve('public/product-v24.html'),'utf8');res.setHeader('cache-control','no-store');return res.type('html').send(html.replace('</body>','<script src="/hotfix-v24.js"></script></body>'))}catch{return res.sendFile(path.resolve('public/product-v24.html'))}});
app.use('/api',proxy);
app.use((req,res)=>res.redirect('/'));
setInterval(()=>{const now=Date.now();for(const[k,b]of bodyById)if(!b?._at||now-b._at>60*60_000)bodyById.delete(k);for(const[k,v]of harajCache)if(now-v.at>HAR_CACHE_TTL)harajCache.delete(k)},10*60_000).unref();
app.listen(externalPort,()=>console.log(`Delilah product-v24 running at http://localhost:${externalPort}`));
