import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000);
const BRAVE_KEY=process.env.BRAVE_SEARCH_API_KEY||'';
const OPENAI_KEY=process.env.OPENAI_API_KEY||'';
const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const app=express();
const cache=new Map();
const progress=new Map();
const TTL=8*60_000;
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'public')));

const digits=s=>String(s||'').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const norm=s=>digits(s).toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').replace(/\s+/g,' ').trim();
const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim();
const canonical=v=>{try{const u=new URL(v);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}};
function years(q=''){return[...digits(q).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(m=>Number(m[1])).filter(y=>y>=1980&&y<=2035)}
function hasRange(q=''){return/(?:and above|or newer|and newer|or later|above|from|since|after|to|through|until|between|وفوق|واكثر|وأكثر|احدث|أحدث|من موديل|بعد|الى|إلى|حتى|بين)/i.test(norm(q))}
function exactYear(q=''){const y=years(q);return y.length===1&&!hasRange(q)?y[0]:null}
function yearOf(t=''){return years(t)[0]||null}
function mileageOf(t=''){const m=digits(t).match(/([0-9][\d,]{0,8})\s*(?:km|kilometers?|كيلو|كم)/i);return m?Number(m[1].replace(/,/g,'')):null}
function priceOf(t=''){const x=digits(t);for(const r of[/(?:price|cash price|selling price|السعر)\s*[:：]?\s*(?:sar|ر\.?س)?\s*([0-9][\d,]{3,9})/i,/([0-9][\d,]{3,9})\s*(?:sar|ريال|ر\.?س)/i]){const m=x.match(r);if(m){const n=Number(m[1].replace(/,/g,''));if(n>=1000&&n<=5000000)return n}}return null}
function cityOf(t=''){const n=norm(t);if(/riyadh|الرياض/.test(n))return'Riyadh';if(/jeddah|جده/.test(n))return'Jeddah';if(/dammam|الدمام/.test(n))return'Dammam';if(/khobar|الخبر/.test(n))return'Khobar';if(/makkah|mecca|مكه/.test(n))return'Makkah';if(/madinah|medina|المدينه/.test(n))return'Madinah';if(/taif|الطايف|الطائف/.test(n))return'Taif';if(/abha|ابها/.test(n))return'Abha';return null}
function conditionOf(t='',source=''){const n=norm(t);if(/\bused\b|second hand|pre owned|pre-owned|مستعمل/.test(n))return'used';if(/\bnew\b|brand new|جديد|زيرو/.test(n))return'new';if(source==='Saleh Cars'||source==='Toyota Saudi')return'new';return null}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`<meta[^>]+(?:property|name)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)?.[1]||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${k}["'][^>]*>`,'i').exec(html)?.[1]||null}
function abs(v,b){try{return new URL(String(v||'').replace(/&amp;/g,'&'),b).href}catch{return null}}
function imageOkay(v=''){try{const u=new URL(v);return/^https?:$/.test(u.protocol)&&!/(logo|favicon|icon|placeholder|avatar|banner|sprite)/i.test(u.href)}catch{return false}}
function inferIdentity(title=''){const clean=String(title).replace(/\s*[|–—].*$/,'').trim(),y=yearOf(clean),tokens=clean.replace(/\b(?:19|20)\d{2}\b/g,'').split(/\s+/).filter(Boolean);return{brand:tokens[0]||null,model:tokens.slice(1,5).join(' ')||null,year:y}}
function hostIs(url,domain){try{const h=new URL(url).hostname.replace(/^www\./,'');return h===domain||h.endsWith('.'+domain)}catch{return false}}
function genericCandidate(url,domain){try{const u=new URL(url),p=u.pathname.replace(/\/+$/,'');if(!hostIs(url,domain))return false;if(!p||p==='/')return false;if(/\/(search|cars-for-sale|used-cars|new-cars|cars|vehicles|autos|marketplace|stock)\/?$/i.test(p))return false;if(/(?:\/page\/\d+|[?&]page=)/i.test(u.href))return false;const seg=p.split('/').filter(Boolean);return /\d{4,}|[a-f0-9]{12,}/i.test(p)||seg.length>=3}catch{return false}}
function strictHaraj(url){try{const u=new URL(url);return hostIs(url,'haraj.com.sa')&&/^\/(?:en\/)?\d{8,14}(?:\/|$)/.test(u.pathname)}catch{return false}}
function strictSaleh(url){try{const u=new URL(url);return hostIs(url,'salehcars.com')&&/^\/(?:en\/)?cars\/[A-Za-z0-9_-]{10,40}\/[^/]+\/?$/i.test(u.pathname)}catch{return false}}
function strictMazad(url){try{const u=new URL(url);return hostIs(url,'motorymazad.com')&&/^\/(?:en|ar)\/car\/\d+\/?$/i.test(u.pathname)}catch{return false}}

const SOURCES=[
{name:'Haraj',domain:'haraj.com.sa',site:'haraj.com.sa',type:'marketplace',channel:'classifieds',conditions:['used','new'],candidate:strictHaraj},
{name:'Syarah',domain:'syarah.com',site:'syarah.com',type:'certified_used',channel:'managed_marketplace',conditions:['used','new'],candidate:u=>genericCandidate(u,'syarah.com')},
{name:'OpenSooq',domain:'opensooq.com',site:'sa.opensooq.com/cars/cars-for-sale',type:'marketplace',channel:'classifieds',conditions:['used','new'],candidate:u=>genericCandidate(u,'opensooq.com')},
{name:'Saudi Sale',domain:'saudisale.com',site:'cars.saudisale.com',type:'marketplace',channel:'classifieds',conditions:['used','new'],candidate:u=>genericCandidate(u,'saudisale.com')},
{name:'YallaMotor',domain:'yallamotor.com',site:'ksa.yallamotor.com/used-cars',type:'marketplace',channel:'marketplace',conditions:['used'],candidate:u=>genericCandidate(u,'yallamotor.com')},
{name:'ArabWheels',domain:'arabwheels.sa',site:'arabwheels.sa/en/used-cars',type:'marketplace',channel:'marketplace',conditions:['used','new'],candidate:u=>genericCandidate(u,'arabwheels.sa')},
{name:'CarSwitch',domain:'carswitch.com',site:'ksa.carswitch.com/en',type:'certified_used',channel:'managed_marketplace',conditions:['used'],candidate:u=>genericCandidate(u,'carswitch.com')},
{name:'Motory',domain:'motory.com',site:'ksa.motory.com/en/used-cars',type:'marketplace',channel:'marketplace',conditions:['used','new'],candidate:u=>genericCandidate(u,'motory.com')},
{name:'Mstaml',domain:'mstaml.com',site:'mstaml.com/sa',type:'marketplace',channel:'classifieds',conditions:['used','new'],candidate:u=>genericCandidate(u,'mstaml.com')},
{name:'Saleh Cars',domain:'salehcars.com',site:'salehcars.com/cars',type:'independent_dealer',channel:'dealer_inventory',conditions:['new'],candidate:strictSaleh},
{name:'Dubizzle KSA',domain:'dubizzle.sa',site:'dubizzle.sa/en/vehicles/cars-for-sale',type:'marketplace',channel:'classifieds',conditions:['used','new'],candidate:u=>genericCandidate(u,'dubizzle.sa')},
{name:'Kayishha',domain:'kayishha.com',site:'buy.kayishha.com/en',type:'certified_used',channel:'managed_marketplace',conditions:['used'],candidate:u=>genericCandidate(u,'kayishha.com')},
{name:'CARTAL',domain:'cartal.sa',site:'cartal.sa',type:'marketplace',channel:'marketplace',conditions:['used','new'],candidate:u=>genericCandidate(u,'cartal.sa')},
{name:'Motory Mazad',domain:'motorymazad.com',site:'motorymazad.com/en/car',type:'auction',channel:'auction',conditions:['used'],candidate:strictMazad},
{name:'BMW Saudi CPO',domain:'bmw-saudiarabia.com',site:'bmw-saudiarabia.com/stock/used',type:'official_dealer',channel:'official_cpo',conditions:['used'],candidate:u=>genericCandidate(u,'bmw-saudiarabia.com')},
{name:'Toyota Saudi',domain:'toyota.com.sa',site:'carsales.toyota.com.sa',type:'official_dealer',channel:'official_new',conditions:['new'],candidate:u=>genericCandidate(u,'toyota.com.sa')}
];
const CLOSED_CHANNELS=[
{name:'Lumi Auctions',channel:'rental_fleet_auction',status:'login_required',reason:'Public auction schedule is visible, but vehicle-level participation requires an account.'},
{name:'Theeb Used Car Sales',channel:'rental_fleet_sales',status:'feed_or_showroom',reason:'Used fleet sales exist, but a public vehicle-level web inventory feed was not found.'},
{name:'Facebook Marketplace',channel:'social_marketplace',status:'auth_limited',reason:'Not treated as a public crawl source; requires platform-supported access.'}
];
const FAST=new Set(['Haraj','OpenSooq','YallaMotor','CarSwitch','Dubizzle KSA','Kayishha','Saleh Cars']);
const aliases=new Map(SOURCES.flatMap(s=>[[norm(s.name),s],...(s.name==='Saudi Sale'?[[norm('SaudiSale'),s]]:[]),...(s.name==='Saleh Cars'?[[norm('Saleh'),s]]:[]),...(s.name==='Dubizzle KSA'?[[norm('Dubizzle'),s],[norm('OLX'),s]]:[]),...(s.name==='Motory Mazad'?[[norm('Mazad'),s]]:[])]));

async function brave(q,count=20){if(!BRAVE_KEY)return[];const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',q);u.searchParams.set('count',String(Math.min(20,count)));u.searchParams.set('country','sa');const r=await fetch(u,{headers:{Accept:'application/json','X-Subscription-Token':BRAVE_KEY},signal:AbortSignal.timeout(9000)});if(!r.ok)throw new Error(`Brave ${r.status}`);return(await r.json())?.web?.results||[]}
async function fetchHtml(url){const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; DalelahBot/1.2; +https://www.dalelah.co)','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{html:(await r.text()).slice(0,3000000),url:r.url||url}}
function jsonLd(html){const out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const j=JSON.parse(m[1]);out.push(...(Array.isArray(j)?j:[j]))}catch{}}return out.flatMap(x=>x?.['@graph']||x)}
function ldValue(nodes,keys){for(const n of nodes)for(const k of keys){const v=n?.[k];if(v!=null&&v!=='')return Array.isArray(v)?v[0]:v}return null}
function categoryLike(title,text,url){const n=norm(`${title} ${text.slice(0,1200)}`);if(/\b(?:find|browse|search)\b.*\b(?:cars|vehicles)\b/.test(n))return true;if(/(?:cars for sale|used cars for sale|new cars for sale).*\b(?:saudi|ksa|riyadh|jeddah)\b/.test(n)&&/(showing \d+ results|\d+ used cars|\d+ cars for sale)/.test(n))return true;try{const p=new URL(url).pathname.replace(/\/+$/,'');if(/\/(search|used-cars|new-cars|cars-for-sale|marketplace|stock)$/i.test(p))return true}catch{}return false}
async function parseListing(seed,source){const d=await fetchHtml(seed.url),text=strip(d.html),h1=strip(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i.exec(d.html)?.[1]||''),title=h1||meta(d.html,'og:title')||seed.title||'',nodes=jsonLd(d.html);if(categoryLike(title,text,d.url))throw new Error('category page');const joined=`${title} ${seed.description||''} ${text.slice(0,12000)}`,y=yearOf(joined);if(!y&&!strictHaraj(d.url)&&!strictSaleh(d.url))throw new Error('no vehicle year');const id=inferIdentity(title||seed.title||''),ldImg=ldValue(nodes,['image','thumbnailUrl']),rawImg=typeof ldImg==='object'?ldImg.url:ldImg,img=abs(rawImg||meta(d.html,'og:image')||meta(d.html,'twitter:image'),d.url),offer=nodes.find(x=>x?.offers)?.offers||nodes.find(x=>x?.price)?.price||null,offerPrice=typeof offer==='object'?(offer.price||offer.lowPrice):offer,price=Number(String(offerPrice||'').replace(/[^0-9.]/g,''))||priceOf(joined),mileage=mileageOf(joined),cond=conditionOf(joined,source.name);if(!price&&!mileage&&!img&&!strictHaraj(d.url)&&!strictSaleh(d.url)&&!strictMazad(d.url))throw new Error('weak listing evidence');return{source:source.name,sourceType:source.type,channel:source.channel,seller:source.name,title:(title||seed.title||`${source.name} car`).slice(0,220),snippet:text.slice(0,700)||seed.description||'',url:canonical(d.url),brand:id.brand,model:id.model,year:id.year||y,mileage,city:cityOf(joined),price:price>=1000&&price<=5000000?price:null,priceVerified:Boolean(price>=1000&&price<=5000000),condition:cond,saleVerified:true,image:img&&imageOkay(img)?img:null,displayImage:img&&imageOkay(img)?img:null,imageVerified:Boolean(img&&imageOkay(img)),score:92,discovery:'market_scan_direct'}}
async function sourceSearch(query,source,count=20){const key=`${source.name}|${norm(query)}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL)return hit.value;let rs=[];try{rs=(await brave(`site:${source.site} ${query}`,count)).filter(r=>source.candidate(r.url))}catch{}const out=[];let i=0;async function worker(){for(;;){const n=i++;if(n>=rs.length)return;const r=rs[n];try{out.push(await parseListing(r,source))}catch{}}}await Promise.all(Array.from({length:Math.min(4,rs.length||1)},worker));cache.set(key,{at:Date.now(),value:out});return out}
function merge(...groups){const m=new Map();for(const g of groups)for(const c of g||[]){if(!c?.url)continue;const k=canonical(c.url),old=m.get(k);m.set(k,old?{...c,...old,image:old.image||c.image,displayImage:old.displayImage||c.displayImage,price:old.price||c.price,priceVerified:Boolean(old.priceVerified||c.priceVerified)}:c)}return[...m.values()]}
function hardMatch(c,intent,condition,y){const t=norm(`${c.brand||''} ${c.model||''} ${c.title||''}`);if(condition&&c.condition&&c.condition!==condition)return false;if(y&&Number(c.year)!==y)return false;if(intent.make&&!t.includes(norm(intent.make)))return false;if(intent.model&&!t.includes(norm(intent.model)))return false;if(intent.minYear&&c.year&&c.year<intent.minYear)return false;if(intent.maxYear&&c.year&&c.year>intent.maxYear)return false;if(intent.minPrice&&c.price&&c.price<intent.minPrice)return false;if(intent.maxPrice&&c.price&&c.price>intent.maxPrice)return false;if(intent.maxMileage&&c.mileage!=null&&c.mileage>intent.maxMileage)return false;if(intent.city&&c.city&&norm(c.city)!==norm(intent.city))return false;return true}
function score(c,intent,y){let s=68,t=norm(`${c.brand||''} ${c.model||''} ${c.title||''}`);if(intent.make&&t.includes(norm(intent.make)))s+=8;if(intent.model&&t.includes(norm(intent.model)))s+=10;if(y&&Number(c.year)===y)s+=8;if(c.priceVerified)s+=3;if(c.imageVerified)s+=2;if(c.sourceType==='official_dealer'||c.sourceType==='certified_used')s+=2;return{...c,aiScore:Math.min(100,s),score:Math.min(100,s),aiReason:y&&Number(c.year)===y?'Exact year match':c.priceVerified?'Verified source listing':'Direct source listing'}}
async function aiIntent(query,previousIntent=null){const y=exactYear(query),fallback={make:null,model:null,condition:null,city:null,minYear:y,maxYear:y,minPrice:null,maxPrice:null,maxMileage:null,bodyType:null,fuel:null,transmission:null,color:null,source:null,sellerType:null,sort:null,priorities:[],excluded:[],goal:String(query||''),retrievalQuery:String(query||'')};if(!OPENAI_KEY||!String(query||'').trim())return fallback;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${OPENAI_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,store:false,reasoning:{effort:'none'},instructions:'You are Dalelah, a Saudi car-search intent parser. Interpret Arabic, English and Saudi dialect. A single bare year means that exact year unless the user explicitly specifies a range. Never invent constraints. retrievalQuery must keep make, model and year. source is null unless the user explicitly names a source.',input:JSON.stringify({query,previousIntent}),text:{format:{type:'json_schema',name:'dalelah_market_intent',strict:true,schema:{type:'object',additionalProperties:false,properties:{make:{type:['string','null']},model:{type:['string','null']},condition:{type:['string','null'],enum:['new','used',null]},city:{type:['string','null']},minYear:{type:['integer','null']},maxYear:{type:['integer','null']},minPrice:{type:['integer','null']},maxPrice:{type:['integer','null']},maxMileage:{type:['integer','null']},bodyType:{type:['string','null']},fuel:{type:['string','null']},transmission:{type:['string','null']},color:{type:['string','null']},source:{type:['string','null']},sellerType:{type:['string','null']},sort:{type:['string','null']},priorities:{type:'array',items:{type:'string'}},excluded:{type:'array',items:{type:'string'}},goal:{type:'string'},retrievalQuery:{type:'string'}},required:['make','model','condition','city','minYear','maxYear','minPrice','maxPrice','maxMileage','bodyType','fuel','transmission','color','source','sellerType','sort','priorities','excluded','goal','retrievalQuery']}}}}),signal:AbortSignal.timeout(9000)});if(!r.ok)return fallback;const data=await r.json();let txt='';for(const item of data.output||[])for(const part of item.content||[])if(part.type==='output_text')txt=part.text;const v=txt?JSON.parse(txt):fallback;if(y){v.minYear=y;v.maxYear=y;if(!String(v.retrievalQuery||'').includes(String(y)))v.retrievalQuery=`${v.retrievalQuery||query} ${y}`.trim()}return v}catch{return fallback}}

app.post('/api/search',async(req,res)=>{const started=Date.now(),body=req.body||{},query=String(body.query||''),y=exactYear(query);try{const intent=await aiIntent(query,body.previousIntent||body.aiContext||null),condition=body.condition||intent.condition||'used',rq=intent.retrievalQuery||query,requested=norm(body.filters?.source||body.filters?.seller||intent.source||''),phase=body.phase==='fast'?'fast':'full';let chosen;if(requested){const s=aliases.get(requested);chosen=s?[s]:SOURCES.filter(x=>norm(x.name).includes(requested)||requested.includes(norm(x.name)))}else chosen=SOURCES.filter(s=>phase==='full'||FAST.has(s.name));chosen=chosen.filter(s=>s.conditions.includes(condition));const groups=await Promise.all(chosen.map(s=>sourceSearch(rq,s,phase==='fast'?12:20).catch(()=>[])));let results=merge(...groups).filter(c=>hardMatch(c,intent,condition,y)).map(c=>score(c,intent,y)).sort((a,b)=>(b.aiScore||0)-(a.aiScore||0));const counts=results.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{}),channels=[...new Set(chosen.map(s=>s.channel))],searchId=`scan-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,payload={ok:true,searchId,listings:results,counts,elapsedMs:Date.now()-started,exactYear:y,exactYearSemantics:Boolean(y),answer:`Scanned ${chosen.length} Saudi market sources across ${channels.length} channel types and found ${results.length} matching ${condition} listings.`,ai:{enabled:Boolean(OPENAI_KEY),model:OPENAI_KEY?OPENAI_MODEL:null,intent},understanding:{aiIntent:intent},marketScan:{phase,sourcesScanned:chosen.map(s=>s.name),sourceCount:chosen.length,channelsScanned:channels,totalConnected:SOURCES.length,closedChannels:CLOSED_CHANNELS},product:{version:'1.2',standalone:true,v36Baseline:true,legacyBoot:false,marketWideAggregator:true,exactListingOnly:true}};progress.set(searchId,{at:Date.now(),payload});return res.json(payload)}catch(e){return res.status(502).json({error:e?.message||'Dalelah market scan unavailable'})}});
app.get('/api/search/progress/:id',(req,res)=>{const hit=progress.get(req.params.id);return hit?res.json(hit.payload):res.status(404).json({error:'Search not found'})});
app.post('/api/understand',async(req,res)=>{const intent=await aiIntent(String(req.body?.query||''),req.body?.previousIntent||null);return res.json({ok:true,ai:Boolean(OPENAI_KEY),intent,exactYear:exactYear(req.body?.query||'')})});
app.get('/api/sources',(_req,res)=>res.json({ok:true,total:SOURCES.length,active:SOURCES.map(s=>({name:s.name,type:s.type,channel:s.channel,conditions:s.conditions,active:true,mode:'public-search + direct-listing verification'})),closed:CLOSED_CHANNELS}));
app.get('/api/health',(_req,res)=>res.json({ok:true,product:'Dalelah 1.2 market aggregator',standalone:true,v36Baseline:true,legacyBoot:false,marketWideAggregator:true,totalSources:SOURCES.length,sources:SOURCES.map(s=>s.name),channels:[...new Set(SOURCES.map(s=>s.channel))],closedChannels:CLOSED_CHANNELS,ai:Boolean(OPENAI_KEY),brave:Boolean(BRAVE_KEY)}));
app.get('/',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
setInterval(()=>{const now=Date.now();for(const[k,v]of cache)if(now-v.at>TTL)cache.delete(k);for(const[k,v]of progress)if(now-v.at>60*60_000)progress.delete(k)},10*60_000).unref();
app.listen(PORT,()=>console.log(`Dalelah 1.2 market-wide aggregator running at http://localhost:${PORT} with ${SOURCES.length} active sources across ${new Set(SOURCES.map(s=>s.channel)).size} channel types`));
