import express from "express";

const externalPort=Number(process.env.PORT||3000);
const v21Port=Number(process.env.DELILAH_V21_PORT||4600);
const CACHE_TTL=10*60_000;
const FETCH_TIMEOUT=6500;
process.env.PORT=String(v21Port);
await import("./server-v21.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const nativeCache=new Map(),overlayJobs=new Map(),bodyById=new Map();
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
function humanNumbers(s=""){let q=digits(s);q=q.replace(/(\d+(?:\.\d+)?)\s*(?:ألف|الف)(?=\s|$|ريال|ر\.?س)/gi,(_,n)=>String(Math.round(Number(n)*1000)));q=q.replace(/(\d+(?:\.\d+)?)\s*[kK](?=\s|$|SAR|ريال|ر\.?س)/g,(_,n)=>String(Math.round(Number(n)*1000)));return q}
function norm(s=""){return humanNumbers(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim()}
function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u:null}catch{return null}}
function absolute(v,b){try{return new URL(String(v||"").replace(/&amp;/g,"&"),b).href}catch{return null}}
function canonical(v=""){const u=safeUrl(v);if(!u)return v;u.hash="";for(const k of[...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,"")}
function decodeHtml(s=""){return String(s).replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
function strip(s=""){return decodeHtml(String(s)).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function attr(tag,name){return new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,`i`).exec(tag)?.[1]||null}
function num(v,min=0,max=5_000_000){const n=Number(String(v||"").replace(/[^0-9.]/g,""));return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function yearOf(t=""){const m=digits(t).match(/\b(20\d{2})\b/),y=m?Number(m[1]):null;return y&&y>=2000&&y<=2035?y:null}
function mileageOf(t=""){const m=digits(t).match(/([0-9][\d,]{0,8})\s*(?:km|kilometers?|كيلو|كم)/i);return m?num(m[1],0,1_500_000):null}
function cityOf(t=""){const x=norm(t);if(/\briyadh\b|الرياض/.test(x))return"Riyadh";if(/\bjeddah\b|جده/.test(x))return"Jeddah";if(/\bdammam\b|الدمام/.test(x))return"Dammam";if(/\bkhobar\b|الخبر/.test(x))return"Khobar";if(/\bmakkah\b|\bmecca\b|مكه/.test(x))return"Makkah";if(/\bmadinah\b|\bmedina\b|المدينه/.test(x))return"Madinah";return null}
function imageOkay(u=""){return /^https?:\/\//i.test(u)&&!/(logo|favicon|icon|placeholder|sprite|social|share|banner|brandmark|default[-_]?image|discount|coupon|avatar|profile)/i.test(u)}
function bestImage(seg,base){const out=[];for(const m of String(seg).matchAll(/<(?:img|source)\b[^>]*>/gi)){const tag=m[0];for(const k of["src","data-src","data-lazy-src","data-original","data-image"]){const u=absolute(attr(tag,k),base);if(u&&imageOkay(u))out.push(u)}const ss=attr(tag,"srcset")||attr(tag,"data-srcset");if(ss)for(const p of ss.split(",")){const u=absolute(p.trim().split(/\s+/)[0],base);if(u&&imageOkay(u))out.push(u)}}return out[0]||null}
const A=new Map([["تويوتا","toyota"],["نيسان","nissan"],["جيب","jeep"],["هيونداي","hyundai"],["كيا","kia"],["فورد","ford"],["شفروليه","chevrolet"],["مرسيدس","mercedes-benz"],["لكزس","lexus"],["بورش","porsche"],["مازدا","mazda"],["هوندا","honda"],["جيلي","geely"],["شانجان","changan"],["جيتور","jetour"],["هافال","haval"],["اودي","audi"],["جينيسيس","genesis"],["فولكس","volkswagen"],["بي ام","bmw"],["رانجلر","wrangler"],["باترول","patrol"],["لاندكروزر","land-cruiser"],["لاند كروزر","land-cruiser"],["كامري","camry"],["كورولا","corolla"],["يارس","yaris"],["صني","sunny"],["توسان","tucson"],["سبورتاج","sportage"],["سوناتا","sonata"],["اكسنت","accent"],["النترا","elantra"],["برادو","prado"],["فورتشنر","fortuner"],["سورينتو","sorento"],["سيراتو","cerato"],["جوليون","jolion"],["كولراي","coolray"]]);
const MB=new Map([["wrangler","jeep"],["grand-cherokee","jeep"],["patrol","nissan"],["sunny","nissan"],["land-cruiser","toyota"],["camry","toyota"],["corolla","toyota"],["yaris","toyota"],["prado","toyota"],["fortuner","toyota"],["accent","hyundai"],["elantra","hyundai"],["sonata","hyundai"],["tucson","hyundai"],["pegas","kia"],["cerato","kia"],["sportage","kia"],["sorento","kia"],["k5","kia"],["accord","honda"],["civic","honda"],["city","honda"],["mazda-6","mazda"],["cx-5","mazda"],["h6","haval"],["jolion","haval"],["alsvin","changan"],["cs35","changan"],["cs75","changan"],["coolray","geely"],["emgrand","geely"],["x5","bmw"],["c200","mercedes-benz"],["territory","ford"],["tahoe","chevrolet"]]);
const brands=["mercedes-benz","land-rover","range-rover","volkswagen","chevrolet","mitsubishi","hyundai","toyota","nissan","lexus","porsche","ford","lincoln","kia","mazda","honda","geely","changan","jetour","haval","audi","bmw","gmc","dodge","suzuki","peugeot","renault","chery","tesla","lucid","jeep"];
const STOP=new Set(norm("ابي ابغى اريد سيارة سياره سيارات car cars vehicle vehicles used new مستعمل مستعمله مستعملة جديد جديده جديدة موديل model سنة سنه year years وفوق واكثر تحت اقل أقل من في بالرياض الرياض بجدة بجده جدة جده بالدمام الدمام السعودية السعوديه saudi arabia ksa riyadh jeddah dammam under below less than above over more than budget ريال sar km كيلو كم").split(" "));
function idOf(q=""){let x=norm(q);for(const[a,b]of[...A.entries()].sort((m,n)=>n[0].length-m[0].length))x=x.replaceAll(norm(a),b.replace(/-/g," "));let brand=brands.find(b=>x.includes(b.replace(/-/g," ")))||null;let toks=x.split(" ").filter(t=>t&&!STOP.has(t)&&!/^\d/.test(t)&&![/^riyadh$/, /^jeddah$/, /^dammam$/, /^saudi$/, /^arabia$/].some(r=>r.test(t)));if(brand){const bw=brand.replace(/-/g," ").split(" ");for(let i=0;i<=toks.length-bw.length;i++)if(bw.every((w,j)=>toks[i+j]===w)){toks.splice(i,bw.length);break}}let model=toks.slice(0,3).join("-")||null;if(!brand&&model){const k=[...MB.keys()].sort((a,b)=>b.length-a.length).find(k=>model.includes(k)||x.includes(k.replace(/-/g," ")));if(k){brand=MB.get(k);model=k}}return{brand,model}}
function filters(body={}){const f=body.filters&&typeof body.filters==="object"?body.filters:{},q=humanNumbers(String(body.query||"")),nq=norm(q),ys=[...q.matchAll(/\b(20\d{2})\b/g)].map(x=>Number(x[1])),km=nq.match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{2,7})\s*(?:km|كم|كيلو)/i),p=nq.match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{4,7})(?!\s*(?:km|كم|كيلو))/i);return{minYear:Number(f.minYear)||(ys.length?Math.min(...ys):null),maxYear:Number(f.maxYear)||null,maxPrice:Number(f.maxPrice)||(p?Number(p[1]):null),maxMileage:Number(f.maxMileage)||(km?Number(km[1]):null),city:f.city||cityOf(q),seller:f.seller||null,sourceType:f.sourceType||null}}
function matches(c,f,condition){if(!c?.url||c.saleVerified!==true||c.condition!==condition)return false;if(f.minYear&&c.year&&c.year<f.minYear)return false;if(f.maxYear&&c.year&&c.year>f.maxYear)return false;if(f.maxPrice&&c.price&&c.price>f.maxPrice)return false;if(f.maxMileage&&c.mileage!=null&&c.mileage>f.maxMileage)return false;if(f.city&&c.city&&c.city!==f.city)return false;return true}
async function get(url){const hit=nativeCache.get(url);if(hit&&Date.now()-hit.at<CACHE_TTL)return hit.d;let last;for(let i=0;i<2;i++){try{const r=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(FETCH_TIMEOUT),headers:{"User-Agent":"Mozilla/5.0 (compatible; DelilahSourceAdapter/2.0)",Accept:"text/html,application/xhtml+xml"}});if(r.ok){const d={html:(await r.text()).slice(0,3_200_000),url:r.url||url};nativeCache.set(url,{at:Date.now(),d});return d}last=new Error(`HTTP ${r.status}`);if(r.status!==429&&r.status<500)break}catch(e){last=e}await new Promise(r=>setTimeout(r,350*(i+1)))}throw last||new Error("fetch failed")}
function directArab(u=""){const x=safeUrl(u);return!!x&&(x.hostname==="arabwheels.sa"||x.hostname==="www.arabwheels.sa")&&/^\/(?:en\/)?used-cars\/[^/]+-for-sale-in-[^/]+-\d+\/?$/i.test(x.pathname)}
function directSyarah(u=""){const x=safeUrl(u);return!!x&&(x.hostname==="syarah.com"||x.hostname.endsWith(".syarah.com"))&&/^\/(?:(?:en|ar)\/)?cardetail\/[^/]+-(?:used|new)-\d+\/?$/i.test(x.pathname)}
function currentArabPrice(t=""){const x=digits(t),m=x.match(/Current\s*Price[^0-9]{0,35}(?:SAR\s*)?([0-9][\d,]*)/i)||x.match(/([0-9][\d,]*)\s*SAR/i);return m?num(m[1],1000):null}
function cashSyarah(t=""){const x=digits(t),m=x.match(/Cash\s*Price\s*(?:\(\s*Includes\s*VAT\s*\))?[^0-9]{0,40}([0-9][\d,]*)\s*SAR/i)||x.match(/السعر\s*النقدي[^0-9]{0,50}([0-9][\d,]*)\s*(?:ر\.?س|ريال)/i);return m?num(m[1],1000):null}
function titleCase(s=""){return s.split("-").map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" ")}
function anchorCards(html,base,valid,source,id,condition){const raw=[];for(const m of String(html).matchAll(/<a\b([^>]*href=["'][^"']+["'][^>]*)>([\s\S]*?)<\/a>/gi)){const href=/href=["']([^"']+)["']/i.exec(m[1])?.[1],u=absolute(href,base);if(u&&valid(u))raw.push({m,u:canonical(u),i:m.index||0})}const out=[],seen=new Set();for(let i=0;i<raw.length;i++){const r=raw[i];if(seen.has(r.u))continue;seen.add(r.u);const next=raw[i+1]?.i||Math.min(String(html).length,r.i+7000),seg=String(html).slice(r.i,Math.min(next,r.i+7000)),a=strip(r.m[2]),text=`${a} ${strip(seg).slice(0,2300)}`,image=bestImage(seg,base),price=source==="ArabWheels"?currentArabPrice(text):cashSyarah(text);out.push({source,sourceType:"marketplace",seller:source,sourceStrict:true,title:a||`${titleCase(id.brand||"")} ${titleCase(id.model||"")}`.trim(),snippet:text.slice(0,700),url:r.u,brand:id.brand?titleCase(id.brand):null,model:id.model?titleCase(id.model):null,year:yearOf(text),mileage:mileageOf(text),city:cityOf(text),price,priceVerified:Boolean(price),priceSource:price?(source==="ArabWheels"?"arabwheels_source_card_price":"syarah_catalog_cash_price"):null,condition,saleVerified:true,saleEvidence:["direct_listing_url","source_model_page",price?"source_price":null].filter(Boolean),image,displayImage:image,imageVerified:Boolean(image),imageSource:image?"source_catalog":null,score:Math.min(96,85+(price?4:0)+(image?4:0)),discovery:"source_native_model_page"})}return out}
async function native(body,deep=false){const condition=body.condition==="new"?"new":"used",f=filters(body),id=idOf(body.query);if(!id.brand||!id.model)return[];const tasks=[];if((!f.seller||f.seller==="Syarah")&&(!f.sourceType||f.sourceType==="marketplace")){tasks.push((async()=>{const all=[];const pages=deep?6:2;for(let p=1;p<=pages;p++){try{const base=`https://syarah.com/en/autos/${id.brand}/${id.model}`,d=await get(p===1?base:`${base}?page=${p}`),xs=anchorCards(d.html,d.url,directSyarah,"Syarah",id,condition).filter(c=>c.condition===condition);all.push(...xs);if(p>1&&!xs.length)break}catch{break}}return all})())}if(condition==="used"&&(!f.seller||f.seller==="ArabWheels")&&(!f.sourceType||f.sourceType==="marketplace")){tasks.push((async()=>{try{const d=await get(`https://www.arabwheels.sa/en/new-cars/${id.brand}/${id.model}/`);return anchorCards(d.html,d.url,directArab,"ArabWheels",id,"used")}catch{return[]}})())}const rs=await Promise.allSettled(tasks),all=[];for(const r of rs)if(r.status==="fulfilled")all.push(...r.value);const map=new Map();for(const c of all)if(matches(c,f,condition)&&!map.has(canonical(c.url)))map.set(canonical(c.url),c);return[...map.values()].sort((a,b)=>(b.score||0)-(a.score||0))}
function merge(...groups){const map=new Map();for(const g of groups)for(const c of(g||[])){if(!c?.url||c.saleVerified!==true)continue;const k=canonical(c.url),o=map.get(k);if(!o){map.set(k,c);continue}const np=c.priceVerified&&!o.priceVerified,ni=c.imageVerified&&!o.imageVerified;map.set(k,{...o,...c,price:np?c.price:(o.price??c.price??null),priceVerified:Boolean(o.priceVerified||c.priceVerified),priceSource:np?c.priceSource:(o.priceSource||c.priceSource||null),image:ni?c.image:(o.image||c.image||null),displayImage:ni?c.displayImage:(o.displayImage||c.displayImage||null),imageVerified:Boolean(o.imageVerified||c.imageVerified),imageSource:ni?c.imageSource:(o.imageSource||c.imageSource||null)})}return[...map.values()].sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,2000)}
const counts=xs=>xs.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{});
async function upstream(path,opts={},tries=2){let last;for(let i=0;i<tries;i++){try{const r=await fetch(`http://127.0.0.1:${v21Port}${path}`,{...opts,signal:opts.signal||AbortSignal.timeout(20000)}),text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text.slice(0,300)}}if(r.ok)return{r,d};last={r,d};if(![502,503,504].includes(r.status))return last}catch(e){last={error:e}}await new Promise(r=>setTimeout(r,250*(i+1)))}if(last?.r)return last;throw last?.error||new Error("upstream unavailable")}
function ensureOverlay(id,body){let j=overlayJobs.get(id);if(j)return j;j={complete:false,listings:[],startedAt:Date.now()};overlayJobs.set(id,j);native(body,true).then(xs=>j.listings=xs).catch(()=>{}).finally(()=>j.complete=true);return j}
function combine(d,j){const listings=merge(d.listings||[],j?.listings||[]),complete=Boolean(d.complete)&&Boolean(j?.complete);return{...d,listings,counts:counts(listings),complete,marketScanComplete:complete,sourceNativeFallback:true,sourceNativeComplete:Boolean(j?.complete),answer:complete?`${listings.length} verified listings found across the completed accessible-source scan.`:`${listings.length} verified listings found so far. Delilah is still scanning connected Saudi sources.`}}
app.post("/api/search",async(req,res)=>{const body=req.body||{};try{const{r,d}=await upstream("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(body.phase==="fast"?12000:22000)});if(r.ok){if(body.phase==="fast"){if((d.listings||[]).length)return res.json(d);const add=await native(body,false).catch(()=>[]);return res.json({...d,listings:merge(d.listings||[],add).slice(0,18),counts:counts(merge(d.listings||[],add).slice(0,18)),fallback:add.length?"source_native_model_page":d.fallback})}if(d.searchId){bodyById.set(d.searchId,body);return res.json(combine(d,ensureOverlay(d.searchId,body)))}return res.json(d)}const add=await native(body,false).catch(()=>[]);if(add.length)return res.json({query:body.query,condition:body.condition==="new"?"new":"used",listings:add.slice(0,body.phase==="fast"?18:2000),counts:counts(add),phase:body.phase==="fast"?"fast":"full",partial:body.phase==="fast",complete:true,marketScanComplete:false,fallback:"source_native_after_upstream_error",upstreamError:d.error||`HTTP ${r.status}`});return res.status(r.status).json(d)}catch(e){const add=await native(body,false).catch(()=>[]);if(add.length)return res.json({query:body.query,condition:body.condition==="new"?"new":"used",listings:add.slice(0,body.phase==="fast"?18:2000),counts:counts(add),phase:body.phase==="fast"?"fast":"full",partial:body.phase==="fast",complete:true,fallback:"source_native_after_upstream_error"});return res.status(502).json({error:e?.message||"Delilah search unavailable"})}});
app.get("/api/search/progress/:id",async(req,res)=>{try{const{r,d}=await upstream(`/api/search/progress/${encodeURIComponent(req.params.id)}`,{signal:AbortSignal.timeout(10000)});if(!r.ok)return res.status(r.status).json(d);const body=bodyById.get(req.params.id),j=body?ensureOverlay(req.params.id,body):overlayJobs.get(req.params.id);return res.json(combine(d,j))}catch(e){return res.status(502).json({error:e?.message||"Search progress unavailable"})}});
app.get("/api/health",async(req,res)=>{try{const{r,d}=await upstream("/api/health",{signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error("health");return res.json({...d,edge:"inventory-v22",logic:"progressive-market-scan-v22",sourceNativeAdapters:["Syarah model catalog","ArabWheels model sale cards"],braveOptional:true,transientUpstreamRetry:true})}catch{return res.status(503).json({ok:false,edge:"inventory-v22"})}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!["host","content-length","connection"].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(","):String(v);let body;if(!["GET","HEAD"].includes(req.method)&&req.is("application/json")){body=JSON.stringify(req.body||{});headers["content-type"]="application/json"}const r=await fetch(`http://127.0.0.1:${v21Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:"manual",signal:AbortSignal.timeout(30000)}),buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!["content-length","transfer-encoding","connection"].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:"Delilah upstream unavailable"})}}
app.use(proxy);
setInterval(()=>{const now=Date.now();for(const[k,v]of nativeCache)if(now-v.at>CACHE_TTL*2)nativeCache.delete(k);for(const[k,v]of overlayJobs)if(now-v.startedAt>20*60_000)overlayJobs.delete(k);},60000).unref();
app.listen(externalPort,()=>console.log(`Delilah inventory-v22 running at http://localhost:${externalPort}`));
