import express from 'express';

const externalPort=Number(process.env.PORT||3000);
const upstreamPort=Number(process.env.DALELAH_V34_PORT||5900);
process.env.PORT=String(upstreamPort);
await import('./server-v34.js');
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:'1mb'}));
const braveKey=process.env.BRAVE_SEARCH_API_KEY||'';
const cache=new Map();
const CACHE_MS=8*60_000;

const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;|&#34;/gi,'"').replace(/\s+/g,' ').trim();
const digits=s=>String(s||'').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const norm=s=>digits(s).toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').replace(/\s+/g,' ').trim();
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`<meta[^>]+(?:property|name)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)?.[1]||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${k}["'][^>]*>`,'i').exec(html)?.[1]||null}
function absolute(v,b){try{return new URL(v,b).href}catch{return null}}
function validImage(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)&&!/(logo|favicon|icon|placeholder|avatar|banner|sprite)/i.test(u.href)}catch{return false}}
function yearOf(t=''){const m=digits(t).match(/\b(20\d{2})\b/);return m?Number(m[1]):null}
function mileageOf(t=''){const m=digits(t).match(/([0-9][\d,]{0,8})\s*(?:km|كيلو|كم)/i);return m?Number(m[1].replace(/,/g,'')):null}
function priceOf(t=''){const x=digits(t);for(const r of[/asking price\s*[:：]?\s*([0-9][\d,]{2,9})/i,/set price\s*[:：]?\s*([0-9][\d,]{2,9})/i,/([0-9][\d,]{2,9})\s*(?:sar|ر\.?س|ريال)/i,/^\s*([0-9][\d,]{2,9})\s*$/m]){const m=x.match(r);if(m){const n=Number(m[1].replace(/,/g,''));if(n>=1000&&n<=5000000)return n}}return null}
function cityOf(t=''){const x=norm(t);if(/riyadh|الرياض/.test(x))return'Riyadh';if(/jeddah|جده/.test(x))return'Jeddah';if(/dammam|الدمام/.test(x))return'Dammam';if(/khobar|الخبر/.test(x))return'Khobar';if(/makkah|مكه/.test(x))return'Makkah';if(/madinah|المدينه/.test(x))return'Madinah';if(/taif|الطايف|الطائف/.test(x))return'Taif';return null}
function conditionOf(t='',source=''){const x=norm(t);if(/\bused\b|مستعمل/.test(x))return'used';if(/\bnew\b|جديد|زيرو/.test(x))return'new';return source==='Saleh Cars'?'new':null}
function harajDirect(v=''){try{const u=new URL(v);return /(^|\.)haraj\.com\.sa$/i.test(u.hostname)&&/^\/(?:en\/)?\d{8,14}(?:\/|$)/.test(u.pathname)}catch{return false}}
function salehDirect(v=''){try{const u=new URL(v);return /(^|\.)salehcars\.com$/i.test(u.hostname)&&/^\/(?:en\/)?cars\/[a-f0-9]{20,30}\/[^/]+\/?$/i.test(u.pathname)}catch{return false}}
async function brave(query,count=10){if(!braveKey)return[];const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',query);u.searchParams.set('count',String(count));u.searchParams.set('country','sa');u.searchParams.set('search_lang','en');const r=await fetch(u,{headers:{Accept:'application/json','X-Subscription-Token':braveKey},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error(`Brave ${r.status}`);const d=await r.json();return d?.web?.results||[]}
async function fetchHtml(url){const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; DalelahSourceIndexer/1.0)',Accept:'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{html:(await r.text()).slice(0,3000000),url:r.url||url}}
function inferIdentity(title=''){const clean=String(title).replace(/\s*\|.*$/,'').trim();const y=yearOf(clean);const tokens=clean.replace(/\b20\d{2}\b/g,'').split(/\s+/).filter(Boolean);return{brand:tokens[0]||null,model:tokens.slice(1,4).join(' ')||null,year:y}}
async function exact(url,source,seed={}){const d=await fetchHtml(url);const html=d.html,text=strip(html),title=strip(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||'')||meta(html,'og:title')||seed.title||`${source} vehicle`;const identity=inferIdentity(title);const img=absolute(meta(html,'og:image')||meta(html,'twitter:image'),d.url);const price=priceOf(`${title} ${text.slice(0,7000)}`)||priceOf(seed.description||'');const condition=conditionOf(`${title} ${text.slice(0,3500)}`,source);return{source,sourceType:source==='Saleh Cars'?'independent_dealer':'marketplace',seller:source,sourceStrict:true,title:title.slice(0,220),snippet:text.slice(0,650),url:d.url,brand:identity.brand,model:identity.model,year:identity.year||yearOf(text),mileage:mileageOf(text),city:cityOf(text),price,priceVerified:Boolean(price),priceSource:price?'source_listing_page':null,condition:condition||'used',saleVerified:true,image:img&&validImage(img)?img:null,displayImage:img&&validImage(img)?img:null,imageVerified:Boolean(img&&validImage(img)),imageSource:img&&validImage(img)?'source_listing_page':null,score:92,discovery:'dedicated_source_adapter'} }
async function sourceResults(query,source){const key=`${source}|${norm(query)}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.value;const site=source==='Haraj'?'haraj.com.sa':'salehcars.com/cars';const results=await brave(`site:${site} ${query}`,12);const valid=results.filter(r=>source==='Haraj'?harajDirect(r.url):salehDirect(r.url));const out=[];let i=0;async function worker(){for(;;){const n=i++;if(n>=valid.length)return;const r=valid[n];try{out.push(await exact(r.url,source,r))}catch{const identity=inferIdentity(r.title||'');out.push({source,sourceType:source==='Saleh Cars'?'independent_dealer':'marketplace',seller:source,sourceStrict:true,title:r.title||`${source} vehicle`,snippet:r.description||'',url:r.url,brand:identity.brand,model:identity.model,year:identity.year||yearOf(r.description||''),mileage:mileageOf(r.description||''),city:cityOf(r.description||''),price:priceOf(r.description||''),priceVerified:Boolean(priceOf(r.description||'')),condition:conditionOf(`${r.title||''} ${r.description||''}`,source)||'used',saleVerified:true,image:null,displayImage:null,imageVerified:false,score:84,discovery:'brave_exact_listing'}}}}
await Promise.all(Array.from({length:Math.min(5,valid.length||1)},worker));cache.set(key,{at:Date.now(),value:out});return out}
function matches(c,intent={}){if(intent.condition&&c.condition&&intent.condition!==c.condition)return false;if(intent.minYear&&c.year&&c.year<intent.minYear)return false;if(intent.maxYear&&c.year&&c.year>intent.maxYear)return false;if(intent.maxPrice&&c.price&&c.price>intent.maxPrice)return false;if(intent.maxMileage&&c.mileage!=null&&c.mileage>intent.maxMileage)return false;if(intent.city&&c.city&&norm(c.city)!==norm(intent.city))return false;return true}
function addScore(c,intent={}){let s=70,t=norm(`${c.brand||''} ${c.model||''} ${c.title||''}`);if(intent.make&&t.includes(norm(intent.make)))s+=8;if(intent.model&&t.includes(norm(intent.model)))s+=10;if(intent.city&&c.city&&norm(c.city)===norm(intent.city))s+=3;if(intent.maxPrice&&c.price&&c.price<=intent.maxPrice)s+=3;if(c.priceVerified)s+=2;if(c.imageVerified)s+=1;return{...c,aiScore:Math.min(100,s),aiReason:c.priceVerified?'Exact source listing with verified price':'Exact source listing'} }
function merge(groups){const m=new Map();for(const g of groups)for(const c of g||[]){if(!c?.url)continue;const k=c.url.replace(/\/$/,'');const old=m.get(k);m.set(k,old?{...c,...old,image:old.image||c.image,displayImage:old.displayImage||c.displayImage,price:old.price||c.price,priceVerified:Boolean(old.priceVerified||c.priceVerified)}:c)}return[...m.values()]}
async function upstream(path,opts={}){const r=await fetch(`http://127.0.0.1:${upstreamPort}${path}`,{...opts,signal:opts.signal||AbortSignal.timeout(60000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:text.slice(0,500)}}return{r,data}}

app.post('/api/search',async(req,res)=>{const body=req.body||{};try{const {r,data}=await upstream('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)return res.status(r.status).json(data);const intent=data?.ai?.intent||data?.understanding?.aiIntent||{};const q=intent.retrievalQuery||body.query||'';let haraj=[],saleh=[];const requested=norm(body.filters?.source||intent.source||'');if(!requested||requested==='haraj')haraj=await sourceResults(q,'Haraj').catch(()=>[]);if(!requested||requested==='saleh cars'||requested==='saleh')saleh=await sourceResults(q,'Saleh Cars').catch(()=>[]);const added=[...haraj,...saleh].filter(c=>matches(c,intent)).map(c=>addScore(c,intent));const listings=merge([data.listings,added]).sort((a,b)=>(b.aiScore||b.score||0)-(a.aiScore||a.score||0));const counts=listings.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{});return res.json({...data,listings,counts,dedicatedSources:{haraj:haraj.length,salehCars:saleh.length},product:{...(data.product||{}),version:'v35',harajDirectAdapter:true,salehCarsDirectAdapter:true}})}catch(e){return res.status(502).json({error:e?.message||'Dalelah source adapters unavailable'})}});

app.get('/api/health',async(_req,res)=>{try{const {r,data}=await upstream('/api/health');if(!r.ok)return res.status(r.status).json(data);return res.json({...data,edge:'product-v35',harajDirectAdapter:true,salehCarsDirectAdapter:true,optionalBrandBrowse:true})}catch{return res.status(503).json({ok:false,edge:'product-v35'})}});
app.get('/',async(_req,res)=>{try{const r=await fetch(`http://127.0.0.1:${upstreamPort}/`,{signal:AbortSignal.timeout(10000)});let html=await r.text();html=html.replace('</body>','<script src="/hotfix-v35.js?v=1"></script></body>');res.setHeader('cache-control','no-store');return res.type('html').send(html)}catch{return res.status(502).send('Dalelah frontend unavailable')}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','content-length','connection'].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(','):String(v);let body;if(!['GET','HEAD'].includes(req.method)&&req.is('application/json')){body=JSON.stringify(req.body||{});headers['content-type']='application/json'}const r=await fetch(`http://127.0.0.1:${upstreamPort}${req.originalUrl}`,{method:req.method,headers,body,redirect:'manual',signal:AbortSignal.timeout(60000)});const buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:'Dalelah upstream unavailable'})}}
app.use(proxy);
app.listen(externalPort,()=>console.log(`Dalelah product-v35 running at http://localhost:${externalPort}`));