import express from "express";

const externalPort=Number(process.env.PORT||3000);
const v25Port=Number(process.env.DELILAH_V25_PORT||5000);
const CACHE_TTL=10*60_000;
process.env.PORT=String(v25Port);
await import("./server-v25.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const bodyById=new Map(),pageCache=new Map();

const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
function humanNumbers(s=""){let q=digits(s);q=q.replace(/(\d+(?:\.\d+)?)\s*(?:ألف|الف)(?=\s|$|ريال|ر\.?س|كم|كيلو)/gi,(_,x)=>String(Math.round(Number(x)*1000)));q=q.replace(/(\d+(?:\.\d+)?)\s*[kK](?=\s|$|SAR|ريال|ر\.?س|km)/g,(_,x)=>String(Math.round(Number(x)*1000)));return q}
function norm(s=""){return humanNumbers(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim()}
function titleCase(s=""){return String(s||'').split(/\s+/).filter(Boolean).map(w=>/^[a-z]{1,3}\d*$/i.test(w)?w.toUpperCase():w.charAt(0).toUpperCase()+w.slice(1)).join(' ')}
function canonical(v=""){try{const u=new URL(v);u.hash='';for(const k of[...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}}
function decodeHtml(s=""){return String(s||'').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function stripHtml(s=""){return decodeHtml(String(s||'')).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function abs(v,b){try{return new URL(String(v||'').replace(/&amp;/g,'&'),b).href}catch{return null}}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:property|name|itemprop)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name|itemprop)=["']${k}["'][^>]*>`,'i').exec(html);return a?decodeHtml(a[1]):null}
function money(v){const n=Number(String(v||'').replace(/[^0-9.]/g,''));return Number.isFinite(n)&&n>=1000&&n<=5_000_000?n:null}
function yearOf(t=''){const ys=[...digits(t).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(x=>Number(x[1])).filter(y=>y>=1980&&y<=2035);return ys[0]||null}
function mileageOf(t=''){const x=digits(t),m=x.match(/([0-9][\d,]{0,8})\s*(?:km|kilometers?|كيلو|كم)/i);if(!m)return null;const n=Number(m[1].replace(/,/g,''));return Number.isFinite(n)&&n>=0&&n<=1_500_000?n:null}
function isDirectSyarah(v=''){try{const u=new URL(v);return(u.hostname==='syarah.com'||u.hostname.endsWith('.syarah.com'))&&/^\/(?:(?:en|ar)\/)?cardetail\/[^/]+-(?:used|new)-\d+\/?$/i.test(u.pathname)}catch{return false}}
function sourceCondition(url=''){return /-new-\d+\/?$/i.test(url)?'new':/-used-\d+\/?$/i.test(url)?'used':null}
function imageOkay(u=''){try{const x=new URL(u);return /^https?:$/.test(x.protocol)&&!/(logo|favicon|icon|sprite|placeholder|avatar|profile|social|share|banner|badge|discount|coupon)/i.test(`${x.pathname} ${x.search}`)}catch{return false}}
function bestImage(seg,base){for(const m of String(seg).matchAll(/<(?:img|source)\b[^>]*>/gi)){const tag=m[0];for(const key of['src','data-src','data-lazy-src','data-original']){const v=new RegExp(`${key}=["']([^"']+)["']`,'i').exec(tag)?.[1],u=abs(v,base);if(u&&imageOkay(u))return u}}return null}

// Aliases improve spelling, Arabic transliteration and multi-word makes only.
// The parser does NOT depend on this table: unknown single-word makes still work generically.
const MAKE_ALIASES={
  'Alfa Romeo':['alfa romeo','الفا روميو'],'Aston Martin':['aston martin','استون مارتن'],'Land Rover':['land rover','لاند روفر'],'Range Rover':['range rover','رينج روفر'],'Rolls Royce':['rolls royce','rolls-royce','رولز رويس'],'Mercedes Benz':['mercedes benz','mercedes-benz','mercedes','مرسيدس'],'Great Wall':['great wall','gwm','جريت وول'],'Lynk & Co':['lynk co','lynk & co','لينك اند كو'],
  'Jeep':['jeep','جيب'],'Toyota':['toyota','تويوتا'],'Nissan':['nissan','نيسان'],'Lexus':['lexus','لكزس'],'BMW':['bmw','بي ام دبليو','بي ام'],'Porsche':['porsche','بورش'],'Ford':['ford','فورد'],'Lincoln':['lincoln','لينكون'],'Hyundai':['hyundai','هيونداي'],'Kia':['kia','كيا'],'Volkswagen':['volkswagen','vw','فولكس واجن','فولكس'],'Chevrolet':['chevrolet','chevy','شفروليه'],'GMC':['gmc','جي ام سي'],'Mazda':['mazda','مازدا'],'Honda':['honda','هوندا'],'Mitsubishi':['mitsubishi','ميتسوبيشي'],'Geely':['geely','جيلي'],'Changan':['changan','شانجان'],'GAC':['gac','جي ايه سي'],'MG':['mg','ام جي'],'Genesis':['genesis','جينيسيس','جينيسس'],'Jetour':['jetour','جيتور'],'Haval':['haval','هافال'],'Audi':['audi','اودي'],'Cadillac':['cadillac','كاديلاك'],'Dodge':['dodge','دودج'],'RAM':['ram','رام'],'Suzuki':['suzuki','سوزوكي'],'Isuzu':['isuzu','ايسوزو'],'Peugeot':['peugeot','بيجو'],'Renault':['renault','رينو'],'Chery':['chery','شيري'],'Hongqi':['hongqi','هونشي'],'BYD':['byd','بي واي دي'],'Tesla':['tesla','تسلا'],'Lucid':['lucid','لوسيد'],'Polestar':['polestar','بولستار'],'Volvo':['volvo','فولفو'],'Subaru':['subaru','سوبارو'],'Infiniti':['infiniti','انفينيتي'],'Acura':['acura','اكورا'],'Bentley':['bentley','بنتلي'],'Ferrari':['ferrari','فيراري'],'Lamborghini':['lamborghini','لامبورغيني'],'Maserati':['maserati','مازيراتي'],'McLaren':['mclaren','ماكلارين'],'Mini':['mini','ميني'],'Fiat':['fiat','فيات'],'Abarth':['abarth','ابارث'],'Citroen':['citroen','سيتروين'],'Opel':['opel','اوبل'],'Skoda':['skoda','سكودا'],'Seat':['seat','سيات'],'Cupra':['cupra','كوبرا'],'Dacia':['dacia','داسيا'],'JAC':['jac','جاك'],'Dongfeng':['dongfeng','دونغ فينغ'],'Exeed':['exeed','اكسيد'],'Jaecoo':['jaecoo','جايكو'],'Omoda':['omoda','اومودا'],'Tank':['tank','تانك'],'Bestune':['bestune','بيستون'],'BAIC':['baic','بايك'],'JMC':['jmc'],'Foton':['foton','فوتون'],'Maxus':['maxus','ماكسوس'],'Wuling':['wuling','وولينغ'],'Zeekr':['zeekr','زيكر'],'Nio':['nio','نيو'],'XPeng':['xpeng','اكس بنغ'],'VinFast':['vinfast','فين فاست'],'Rivian':['rivian','ريفيان'],'Lotus':['lotus','لوتس'],'Smart':['smart','سمارت'],'SsangYong':['ssangyong','سانج يونج'],'KGM':['kgm'],'Mahindra':['mahindra','ماهيندرا'],'Tata':['tata','تاتا'],'Proton':['proton','بروتون'],'Perodua':['perodua','بيرودوا']
};
const LEADING=new Set(norm('i want i need show me find search looking for looking to buy give me get me can you find please car cars vehicle vehicles سيارة سياره سيارات ابي ابغى اريد ابحث دور لي ورني عطني').split(' '));
const BOUNDARY=new Set(norm('used new second hand preowned pre owned مستعمل مستعمله مستعملة جديد جديده جديدة year years سنة سنه from to between newer older above over under below less than more max maximum minimum min budget price سعر ميزانية ميزانيه ريال sar km kilometer kilometers mileage ممشى الممشى كيلو كم in at near الرياض riyadh جدة جده jeddah الدمام dammam الخبر khobar مكة مكه makkah المدينة المدينه madinah saudi arabia ksa and or with بدون only فقط automatic manual gasoline petrol diesel hybrid electric suv sedan coupe hatchback pickup family luxury reliable clean cheap cheapest best good').split(' '));
const CITY=new Set(norm('riyadh الرياض jeddah جدة جده dammam الدمام khobar الخبر makkah مكة مكه madinah المدينة المدينه').split(' '));
function phraseIn(text,phrase){return ` ${norm(text)} `.includes(` ${norm(phrase)} `)}
function findMake(q=''){let best=null;const nq=norm(q);for(const[make,aliases]of Object.entries(MAKE_ALIASES))for(const alias of aliases){const a=norm(alias),i=` ${nq} `.indexOf(` ${a} `);if(i>=0&&(!best||a.length>best.variant.length))best={make,variant:a,aliases,index:Math.max(0,i-1)}}return best}
function isYearToken(t){const n=Number(t);return /^\d{4}$/.test(t)&&n>=1980&&n<=2035}
function cleanLeading(tokens){const out=[...tokens];while(out.length&&(LEADING.has(out[0])||BOUNDARY.has(out[0])&&!['model'].includes(out[0])))out.shift();return out}
function collectIdentityTokens(tokens){const out=[];for(let i=0;i<tokens.length;i++){const t=tokens[i],prev=tokens[i-1]||'',next=tokens[i+1]||'';if(!t)continue;if(CITY.has(t)||BOUNDARY.has(t)&&t!=='model')break;if(isYearToken(t))break;if(/^\d+(?:\.\d+)?$/.test(t)&&/^(sar|ريال|km|كيلو|كم)$/.test(next))break;if(/^(sar|ريال|km|كيلو|كم)$/.test(t))break;if(/^(under|below|over|above|max|budget|تحت|اقل|اكثر)$/.test(prev))break;out.push(t);if(out.length>=7)break}return out}
function displayModel(tokens=[]){return tokens.map(w=>/^[a-z]{1,4}\d+[a-z]*$/i.test(w)||/^\d+$/.test(w)||w.length<=3?w.toUpperCase():w.charAt(0).toUpperCase()+w.slice(1)).join(' ')}
function inferIdentity(query=''){
  const nq=norm(query),tokens=nq.split(' ').filter(Boolean),makeHit=findMake(nq);
  if(makeHit){
    const mt=makeHit.variant.split(' '),start=tokens.findIndex((_,i)=>mt.every((w,j)=>tokens[i+j]===w));
    let modelTokens=start>=0?collectIdentityTokens(tokens.slice(start+mt.length)):[];
    if(!modelTokens.length&&start>0){const before=cleanLeading(tokens.slice(0,start));modelTokens=collectIdentityTokens(before).slice(-5)}
    return{make:makeHit.make,makeVariants:[makeHit.make,...makeHit.aliases],model:modelTokens.length?displayModel(modelTokens):null,modelVariants:modelTokens.length?[modelTokens.join(' ')]:[],genericMake:false};
  }
  let core=cleanLeading(tokens),cut=core.findIndex(t=>CITY.has(t)||BOUNDARY.has(t)&&t!=='model'||isYearToken(t));if(cut>=0)core=core.slice(0,cut);
  if(!core.length)return{make:null,makeVariants:[],model:null,modelVariants:[],genericMake:false};
  const make=titleCase(core[0]),modelTokens=core.slice(1,8);
  return{make,makeVariants:[core[0]],model:modelTokens.length?displayModel(modelTokens):null,modelVariants:modelTokens.length?[modelTokens.join(' ')]:[],genericMake:true};
}
function cityOf(q=''){const x=norm(q);if(/\briyadh\b|الرياض/.test(x))return'Riyadh';if(/\bjeddah\b|جده|جدة/.test(x))return'Jeddah';if(/\bdammam\b|الدمام/.test(x))return'Dammam';if(/\bkhobar\b|الخبر/.test(x))return'Khobar';if(/\bmakkah\b|\bmecca\b|مكه|مكة/.test(x))return'Makkah';if(/\bmadinah\b|\bmedina\b|المدينه|المدينة/.test(x))return'Madinah';return null}
function universalIntent(body={}){const f=body.filters&&typeof body.filters==='object'?body.filters:{},raw=humanNumbers(String(body.query||'')),x=norm(raw),id=inferIdentity(raw),years=[...raw.matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(m=>Number(m[1])).filter(y=>y>=1980&&y<=2035);let minYear=Number(f.minYear)||null,maxYear=Number(f.maxYear)||null;const between=x.match(/(?:between|من)\s*(20\d{2})\s*(?:and|to|الى|إلى|و)\s*(20\d{2})/i);if(between){minYear=minYear||Math.min(+between[1],+between[2]);maxYear=maxYear||Math.max(+between[1],+between[2])}else if(years.length){const y=years[0];if(/(?:and above|or newer|and newer|\+|وفوق|واكثر|وأكثر|فما فوق|من موديل)/i.test(raw))minYear=minYear||y;else if(/(?:and below|or older|and older|وتحت|واقل|وأقل|حتى موديل)/i.test(raw))maxYear=maxYear||y;else minYear=minYear||y}const km=x.match(/(?:under|below|less than|max(?:imum)?|تحت|اقل|أقل)\s*(\d{2,7})\s*(?:km|كيلو|كم)/i),price=x.match(/(?:under|below|less than|max(?:imum)?|budget|تحت|اقل|أقل|ميزانيه|ميزانية)\s*(\d{4,7})(?!\s*(?:km|كيلو|كم))/i);return{query:String(body.query||''),condition:body.condition==='new'?'new':'used',brand:id.make,make:id.make,makeVariants:id.makeVariants,model:id.model,modelVariants:id.modelVariants,genericMake:id.genericMake,minYear,maxYear,maxPrice:Number(f.maxPrice)||(price?+price[1]:null),maxMileage:Number(f.maxMileage)||(km?+km[1]:null),city:String(f.city||cityOf(raw)||'').trim()||null,seller:String(f.seller||'').trim()||null,sourceType:String(f.sourceType||'').trim()||null,confidence:id.make&&id.model?0.99:id.make?0.9:0.6,universalIdentity:true}}
function listingEvidence(c={}){let path='';try{path=decodeURIComponent(new URL(c.url||'').pathname.replace(/[-_]+/g,' '))}catch{}return `${c.title||''} ${path}`}
function makeMatches(e,intent){if(!intent.make)return true;return(intent.makeVariants?.length?intent.makeVariants:[intent.make]).some(v=>phraseIn(e,v))}
function modelMatches(e,intent){if(!intent.model)return true;const vs=intent.modelVariants?.length?intent.modelVariants:[intent.model];return vs.some(v=>phraseIn(e,v))}
function universalMatch(c,intent){if(!c?.url||c.saleVerified!==true||c.condition!==intent.condition)return false;const e=listingEvidence(c);if(intent.make&&!makeMatches(e,intent))return false;if(intent.model&&!modelMatches(e,intent))return false;if(intent.minYear&&(!c.year||+c.year<intent.minYear))return false;if(intent.maxYear&&(!c.year||+c.year>intent.maxYear))return false;if(intent.maxPrice&&(!c.priceVerified||c.price==null||+c.price>intent.maxPrice))return false;if(intent.maxMileage&&(c.mileage==null||+c.mileage>intent.maxMileage))return false;if(intent.city&&norm(c.city||'')!==norm(intent.city))return false;if(intent.seller&&norm(c.seller||c.source||'')!==norm(intent.seller))return false;if(intent.sourceType&&String(c.sourceType||'')!==intent.sourceType)return false;return true}

function slugify(s=''){return norm(s).replace(/\s+/g,'-')}
function makeSlugs(intent){const xs=new Set();for(const v of intent.makeVariants||[]){const n=norm(v);if(!/[\u0600-\u06ff]/.test(n))xs.add(n.replace(/\s+/g,'-'))}if(intent.make)xs.add(slugify(intent.make));return[...xs].filter(Boolean).slice(0,4)}
function modelSlugs(intent){if(!intent.model)return[];const n=norm(intent.model),tokens=n.split(' '),xs=new Set([tokens.join('-'),tokens.join('')]);xs.add(tokens.map(t=>t.replace(/^([a-z]+)(\d+)$/i,'$1-$2')).join('-'));xs.add(tokens.map(t=>t.replace(/^(\d+)([a-z]+)$/i,'$1-$2')).join('-'));return[...xs].filter(Boolean).slice(0,5)}
async function get(url){const hit=pageCache.get(url);if(hit&&Date.now()-hit.at<CACHE_TTL)return hit.data;const r=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(7000),headers:{'User-Agent':'Mozilla/5.0 (compatible; DelilahUniversalAdapter/1.0)',Accept:'text/html,application/xhtml+xml'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data={html:(await r.text()).slice(0,3_200_000),url:r.url||url};pageCache.set(url,{at:Date.now(),data});return data}
function parseSyarahCatalog(html='',base='',intent){const raw=[];for(const m of String(html).matchAll(/<a\b([^>]*href=["'][^"']+["'][^>]*)>([\s\S]*?)<\/a>/gi)){const href=/href=["']([^"']+)["']/i.exec(m[1])?.[1],u=abs(href,base);if(u&&isDirectSyarah(u))raw.push({u:canonical(u),i:m.index||0,anchor:m[2]})}const out=[],seen=new Set();for(let i=0;i<raw.length&&out.length<40;i++){const r=raw[i];if(seen.has(r.u))continue;seen.add(r.u);const next=raw[i+1]?.i||Math.min(String(html).length,r.i+7500),seg=String(html).slice(r.i,Math.min(next,r.i+7500)),text=`${stripHtml(r.anchor)} ${stripHtml(seg).slice(0,2600)}`,condition=sourceCondition(r.u);if(condition!==intent.condition)continue;const image=bestImage(seg,base),title=stripHtml(r.anchor).slice(0,220)||`${intent.make||''} ${intent.model||''}`.trim();out.push({source:'Syarah',sourceType:'marketplace',seller:'Syarah',title,snippet:text.slice(0,700),url:r.u,condition,saleVerified:true,year:yearOf(text),mileage:mileageOf(text),image,displayImage:image,imageVerified:Boolean(image),imageSource:image?'source_catalog':null,score:94,universalNative:true})}return out}
function parseSyarahPricing(text=''){const x=digits(text).replace(/\s+/g,' ');let m=x.match(/Cash\s*Price\s*(?:\(\s*Includes\s*VAT\s*\))?[^0-9]{0,80}([0-9][\d,]*)\s*SAR(?:\s+([0-9][\d,]*)\s*SAR)?/i);if(!m)m=x.match(/السعر\s*النقدي[^0-9]{0,80}([0-9][\d,]*)\s*(?:ر\.?س|ريال)(?:\s+([0-9][\d,]*)\s*(?:ر\.?س|ريال))?/i);const discounted=m?money(m[1]):null,second=m?.[2]?money(m[2]):null,original=second&&discounted&&second>discounted?second:discounted;return{discounted,original,discountAmount:original&&discounted&&original>discounted?original-discounted:null}}
async function verifySyarah(car){if(!car||car.source!=='Syarah'||!isDirectSyarah(car.url))return car;try{const d=await get(car.url),text=stripHtml(d.html).slice(0,180000),pricing=parseSyarahPricing(text),title=stripHtml(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(d.html)?.[1]||meta(d.html,'og:title')||car.title||'').replace(/\s*\|\s*Syarah.*$/i,'').slice(0,220),image=abs(meta(d.html,'og:image'),d.url);return{...car,url:canonical(d.url),title:title||car.title,price:pricing.original||null,originalPrice:pricing.original||null,discountedPrice:pricing.discounted||null,discountAmount:pricing.discountAmount||null,priceVerified:Boolean(pricing.original),priceSource:pricing.original?'syarah_original_pre_discount_price':null,syarahExactVerified:true,image:image&&imageOkay(image)?image:car.image,displayImage:image&&imageOkay(image)?image:car.displayImage,imageVerified:Boolean(image&&imageOkay(image)||car.imageVerified),imageSource:image&&imageOkay(image)?'syarah_exact_listing_page':car.imageSource}}catch{return{...car,price:null,priceVerified:false,priceSource:null,syarahExactVerified:false}}}
async function universalNative(intent,deep=false){if(!intent.make||!intent.model)return[];const ms=makeSlugs(intent),mods=modelSlugs(intent),all=[];for(const make of ms){for(const model of mods){for(let page=1;page<=(deep?4:1);page++){try{const root=`https://syarah.com/en/autos/${make}/${model}`,d=await get(page===1?root:`${root}?page=${page}`),cars=parseSyarahCatalog(d.html,d.url,intent);all.push(...cars);if(!cars.length)break}catch{break}}if(all.length)break}if(all.length)break}const uniq=[...new Map(all.map(c=>[canonical(c.url),c])).values()].filter(c=>universalMatch(c,intent)).slice(0,deep?36:12),out=[];let cursor=0;async function worker(){for(;;){const i=cursor++;if(i>=uniq.length)return;out[i]=await verifySyarah(uniq[i])}}await Promise.all(Array.from({length:Math.min(8,uniq.length||1)},worker));return out.filter(Boolean).filter(c=>universalMatch(c,intent))}
function mergeCars(...groups){const m=new Map();for(const g of groups)for(const c of g||[]){if(!c?.url)continue;const k=canonical(c.url),o=m.get(k);if(!o){m.set(k,c);continue}const auth=Boolean(c.syarahExactVerified||/exact_listing|original_pre_discount/.test(String(c.priceSource||'')));m.set(k,{...o,...c,price:auth?c.price:(o.price??c.price??null),priceVerified:auth?Boolean(c.priceVerified):Boolean(o.priceVerified||c.priceVerified),image:c.imageVerified&&!o.imageVerified?c.image:(o.image||c.image||null),displayImage:c.imageVerified&&!o.imageVerified?c.displayImage:(o.displayImage||c.displayImage||null),imageVerified:Boolean(o.imageVerified||c.imageVerified)})}return[...m.values()]}
function explain(intent,count){const bits=[intent.condition==='new'?'New':'Used',intent.make,intent.model].filter(Boolean);if(intent.minYear&&intent.maxYear)bits.push(`${intent.minYear}–${intent.maxYear}`);else if(intent.minYear)bits.push(`${intent.minYear}+`);else if(intent.maxYear)bits.push(`≤ ${intent.maxYear}`);if(intent.maxPrice)bits.push(`≤ ${intent.maxPrice.toLocaleString('en-US')} SAR`);if(intent.maxMileage)bits.push(`≤ ${intent.maxMileage.toLocaleString('en-US')} km`);if(intent.city)bits.push(intent.city);return`Understood: ${bits.join(' · ')}. ${count} verified exact-identity listing${count===1?'':'s'} found.`}
async function finalize(d={},body={},deep=false){const intent=universalIntent(body),base=(Array.isArray(d.listings)?d.listings:[]).filter(c=>universalMatch(c,intent));let extra=[];if(intent.make&&intent.model&&(deep||!base.length))extra=await universalNative(intent,deep).catch(()=>[]);const listings=mergeCars(base,extra).filter(c=>universalMatch(c,intent));const counts=listings.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{});return{...d,listings,counts,answer:explain(intent,listings.length),understanding:intent,aiSearchUnderstanding:true,exactModelIdentity:true,universalVehicleIdentity:true,unknownMakeFallback:true,syarahOriginalPricePolicy:true,product:{...(d.product||{}),version:'v26',verifiedListings:listings.length,verifiedPrices:listings.filter(x=>x.priceVerified).length,verifiedImages:listings.filter(x=>x.imageVerified).length,sources:Object.keys(counts).length}}}
async function upstream(path,opts={}){const r=await fetch(`http://127.0.0.1:${v25Port}${path}`,{...opts,signal:opts.signal||AbortSignal.timeout(45000)}),text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text.slice(0,500)}}return{r,d}}

app.post('/api/search',async(req,res)=>{const body=req.body||{};try{const{r,d}=await upstream('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(body.phase==='fast'?22000:42000)});if(!r.ok)return res.status(r.status).json(d);if(d.searchId)bodyById.set(d.searchId,{...body,_at:Date.now()});return res.json(await finalize(d,body,body.phase!=='fast'))}catch(e){return res.status(502).json({error:e?.message||'Delilah universal search unavailable'})}});
app.get('/api/search/progress/:id',async(req,res)=>{try{const{r,d}=await upstream(`/api/search/progress/${encodeURIComponent(req.params.id)}`,{signal:AbortSignal.timeout(25000)});if(!r.ok)return res.status(r.status).json(d);const body=bodyById.get(req.params.id)||{};return res.json(await finalize(d,body,true))}catch(e){return res.status(502).json({error:e?.message||'Search progress unavailable'})}});
app.post('/api/understand',(req,res)=>res.json({ok:true,understanding:universalIntent(req.body||{}),engine:'universal-vehicle-identity-v26'}));
app.get('/api/health',async(req,res)=>{try{const{r,d}=await upstream('/api/health',{signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error('health');return res.json({...d,edge:'product-v26',logic:'universal-make-model-identity-v26',fullProduct:true,aiSearchUnderstanding:true,exactModelIdentity:true,universalVehicleIdentity:true,unknownMakeFallback:true,syarahOriginalPricePolicy:true,frontend:'product-v24'})}catch{return res.status(503).json({ok:false,edge:'product-v26'})}});
app.get('/',async(req,res)=>{try{const r=await fetch(`http://127.0.0.1:${v25Port}/`,{signal:AbortSignal.timeout(9000)}),html=await r.text();res.setHeader('cache-control','no-store');return res.type('html').send(html)}catch{return res.status(502).send('Delilah frontend unavailable')}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!['host','content-length','connection'].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(','):String(v);let body;if(!['GET','HEAD'].includes(req.method)&&req.is('application/json')){body=JSON.stringify(req.body||{});headers['content-type']='application/json'}const r=await fetch(`http://127.0.0.1:${v25Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:'manual',signal:AbortSignal.timeout(45000)}),buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v);return res.status(r.status).send(buf)}catch{return res.status(502).json({error:'Delilah upstream unavailable'})}}
app.use(proxy);
setInterval(()=>{const now=Date.now();for(const[k,b]of bodyById)if(!b?._at||now-b._at>60*60_000)bodyById.delete(k);for(const[k,v]of pageCache)if(now-v.at>CACHE_TTL*2)pageCache.delete(k)},10*60_000).unref();
app.listen(externalPort,()=>console.log(`Delilah universal product-v26 running at http://localhost:${externalPort}`));
