import express from "express";

const externalPort=Number(process.env.PORT||3000);
const v13Port=Number(process.env.DELILAH_V13_PORT||3800);
const START_PAGE=31,END_PAGE=120,REFRESH_MS=30*60_000,FETCH_TIMEOUT=7000,MAX_RESULTS=200;
const extra=new Map();
let refreshing=false,lastRefreshStarted=null,lastRefreshFinished=null,lastRefreshError=null,pagesFetched=0;

process.env.PORT=String(v13Port);
await import("./server-v13.js");
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:"1mb"}));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const digits=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
function norm(s=""){return digits(s).toLowerCase().normalize("NFKD").replace(/[\u064b-\u065f\u0670]/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^a-z0-9\u0600-\u06ff]+/g," ").replace(/\s+/g," ").trim()}
function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u:null}catch{return null}}
function absolute(v,b){try{return new URL(String(v||"").replace(/&amp;/g,"&"),b).href}catch{return null}}
function decodeHtml(s=""){return String(s).replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}
function strip(s=""){return decodeHtml(String(s)).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function directSyarah(url){try{const u=new URL(url);if(!(u.hostname==="syarah.com"||u.hostname.endsWith(".syarah.com")))return null;const m=u.pathname.match(/^\/(?:(?:en|ar)\/)?cardetail\/([^/]+)-(used|new)-(\d+)\/?$/i);return m?{slug:m[1],condition:m[2].toLowerCase(),id:m[3]}:null}catch{return null}}
function canonical(url){const d=directSyarah(url);return d?`https://syarah.com/en/cardetail/${d.slug}-${d.condition}-${d.id}`:url}
function attr(tag,name){const m=new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`,`i`).exec(tag);return m?decodeHtml(m[1]):null}
function imageOkay(url=""){const u=safeUrl(url);return !!u&&!/(logo|favicon|icon|placeholder|sprite|social|share|banner|brandmark|default[-_]?image|discount|coupon)/i.test(u.href)}
function bestImage(seg,base){const out=[];for(const m of String(seg).matchAll(/<(?:img|source)\b[^>]*>/gi)){const tag=m[0];for(const k of["src","data-src","data-lazy-src","data-original","data-image"]){const u=absolute(attr(tag,k),base);if(u&&imageOkay(u))out.push(u)}const ss=attr(tag,"srcset")||attr(tag,"data-srcset");if(ss)for(const p of ss.split(",")){const u=absolute(p.trim().split(/\s+/)[0],base);if(u&&imageOkay(u))out.push(u)}}return out.find(Boolean)||null}
function cashPrice(text=""){const t=digits(text);const m=t.match(/Cash\s*Price\s*(?:\(\s*Includes\s*VAT\s*\))?[^0-9]{0,35}([0-9][\d,]*)\s*SAR/i);if(!m)return null;const n=Number(m[1].replace(/,/g,""));return Number.isFinite(n)&&n>=1000&&n<=5_000_000?n:null}
function mileage(text=""){const t=digits(text),m=t.match(/([0-9][\d,]{0,8})\s*(?:KM|KiloMeters?)/i);if(!m)return null;const n=Number(m[1].replace(/,/g,""));return Number.isFinite(n)&&n<=1_500_000?n:null}
function city(text=""){const t=norm(text);if(/riyadh|الرياض/.test(t))return"Riyadh";if(/jeddah|جده/.test(t))return"Jeddah";if(/dammam|الدمام/.test(t))return"Dammam";if(/khobar|الخبر/.test(t))return"Khobar";if(/makkah|mecca|مكه/.test(t))return"Makkah";if(/madinah|medina|المدينه/.test(t))return"Madinah";return null}
function year(text=""){const m=digits(text).match(/\b(20\d{2})\b/),n=m?Number(m[1]):null;return n&&n>=2000&&n<=2035?n:null}
const MULTI=["land-rover","range-rover","mercedes-benz","alfa-romeo","aston-martin","great-wall","rolls-royce","lynk-and-co"];
function identity(slug=""){const low=slug.toLowerCase(),bs=MULTI.find(b=>low===b||low.startsWith(`${b}-`)),w=low.split(/[-_]+/).filter(Boolean),bw=bs?bs.split("-"):w.slice(0,1),rest=w.slice(bw.length).filter(x=>!/^20\d{2}$/.test(x));const title=a=>a.map(x=>x?x[0].toUpperCase()+x.slice(1):x).join(" ");return{brand:title(bw),model:title(rest)}}
function parseCards(html,base,page){const raw=[];for(const m of String(html).matchAll(/<a\b([^>]*href=["'][^"']+["'][^>]*)>([\s\S]*?)<\/a>/gi)){const href=/href=["']([^"']+)["']/i.exec(m[1])?.[1],url=absolute(href,base),d=directSyarah(url);if(d)raw.push({m,url,d,index:m.index||0})}const out=[],seen=new Set();for(let i=0;i<raw.length;i++){const r=raw[i];if(seen.has(r.d.id))continue;seen.add(r.d.id);const next=raw[i+1]?.index||Math.min(String(html).length,r.index+7000),seg=String(html).slice(r.index,Math.min(next,r.index+7000)),anchor=strip(r.m[2]),context=strip(seg).slice(0,2200),text=`${anchor} ${context}`.trim(),id=identity(r.d.slug);out.push({key:`${r.d.condition}:${r.d.id}`,id:r.d.id,url:canonical(r.url),condition:r.d.condition,slug:r.d.slug,title:anchor.length>4?anchor.slice(0,500):`${id.brand} ${id.model}`.trim(),brand:id.brand,model:id.model,year:year(`${r.d.slug} ${text}`),mileage:mileage(text),city:city(text),catalogPrice:cashPrice(text),image:bestImage(seg,base),text,page,indexedAt:Date.now()})}return out}
async function fetchPage(page){const u=new URL("https://syarah.com/en/autos");u.searchParams.set("page",String(page));const c=new AbortController(),t=setTimeout(()=>c.abort(),FETCH_TIMEOUT);try{const r=await fetch(u.href,{signal:c.signal,redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 (compatible; DelilahCatalogIndexer/2.0)",Accept:"text/html,application/xhtml+xml"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=(await r.text()).slice(0,3_000_000),cards=parseCards(html,r.url||u.href,page);for(const x of cards)extra.set(x.key,x);pagesFetched++;return cards.length}finally{clearTimeout(t)}}
async function refresh(){if(refreshing)return;refreshing=true;lastRefreshStarted=new Date().toISOString();lastRefreshError=null;pagesFetched=0;try{let empty=0;for(let p=START_PAGE;p<=END_PAGE;p++){let n=0;try{n=await fetchPage(p)}catch(e){lastRefreshError=`page ${p}: ${e?.message||e}`};empty=n?0:empty+1;if(p>=START_PAGE+5&&empty>=3)break;await sleep(350)}lastRefreshFinished=new Date().toISOString()}catch(e){lastRefreshError=e?.message||String(e)}finally{refreshing=false}}

const STOP=new Set(norm("ابي ابغى أبغى اريد أريد سيارة سياره سيارات cars car vehicle vehicles used new مستعمل مستعملة مستعمله جديد جديده جديدة موديل model سنة سنه years year وفوق فوق واكثر وأكثر تحت اقل أقل من الى إلى في بالرياض الرياض بجدة بجده جدة جده بالدمام الدمام السعودية السعوديه saudi arabia ksa riyadh jeddah dammam under below less than above over more than around about budget ريال sar km كيلو كم").split(" "));
function terms(q=""){return[...new Set(norm(q).split(" ").filter(t=>t.length>=2&&!STOP.has(t)&&!/^\d+$/.test(t)))].slice(0,8)}
function intent(query="",filters={}){const q=digits(query),ys=[...q.matchAll(/\b(20\d{2})\b/g)].map(x=>Number(x[1])),p=norm(q).match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{4,7})/i),km=norm(q).match(/(?:under|below|less than|تحت|اقل|أقل)\s*(\d{2,7})\s*(?:km|كم|كيلو)/i);return{terms:terms(q),minYear:Number(filters.minYear)||(ys.length?Math.min(...ys):null),maxYear:Number(filters.maxYear)||null,maxPrice:Number(filters.maxPrice)||(p?Number(p[1]):null),maxMileage:Number(filters.maxMileage)||(km?Number(km[1]):null),city:filters.city||city(q)}}
function blob(c){return norm(`${c.slug} ${c.brand} ${c.model} ${c.title} ${c.text}`)}
function match(c,i,condition){if(c.condition!==condition)return false;const b=blob(c),compact=b.replace(/\s+/g,"");if(!i.terms.every(t=>b.includes(t)||compact.includes(t.replace(/\s+/g,""))))return false;if(i.minYear&&c.year&&c.year<i.minYear)return false;if(i.maxYear&&c.year&&c.year>i.maxYear)return false;if(i.maxPrice&&c.catalogPrice&&c.catalogPrice>i.maxPrice)return false;if(i.maxMileage&&c.mileage!=null&&c.mileage>i.maxMileage)return false;if(i.city&&c.city&&c.city!==i.city)return false;return true}
function publicCard(c){return{source:"Syarah",sourceType:"marketplace",seller:"Syarah",sourceStrict:true,title:c.title,snippet:c.text.slice(0,700),url:c.url,brand:c.brand,model:c.model,year:c.year,mileage:c.mileage,city:c.city,price:null,priceVerified:false,priceSource:null,condition:c.condition,saleVerified:true,image:c.image||null,displayImage:c.image||null,imageVerified:Boolean(c.image),imageSource:c.image?"source_catalog":null,score:82,discovery:"extended_broad_catalog",catalogPage:c.page}}
function generic(body={},normalizedQuery=""){const condition=body.condition==="new"?"new":"used",filters=body.filters&&typeof body.filters==="object"?body.filters:{};if((filters.seller&&filters.seller!=="Syarah")||(filters.sourceType&&filters.sourceType!=="marketplace"))return[];const i=intent(normalizedQuery||String(body.query||""),filters);return[...extra.values()].filter(c=>match(c,i,condition)).sort((a,b)=>(Boolean(b.image)-Boolean(a.image))||(b.indexedAt-a.indexedAt)).slice(0,MAX_RESULTS).map(publicCard)}
function merge(a=[],b=[],max=MAX_RESULTS){const out=[],seen=new Set();for(const c of[...a,...b]){if(!c?.url)continue;const k=String(c.url).replace(/\/$/,"");if(seen.has(k))continue;seen.add(k);out.push(c);if(out.length>=max)break}return out}
function counts(xs=[]){return xs.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{})}
async function upstreamSearch(body){const r=await fetch(`http://127.0.0.1:${v13Port}/api/search`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body||{})}),d=await r.json().catch(()=>({error:`Upstream HTTP ${r.status}`}));return{r,d}}
app.post("/api/search",async(req,res)=>{const body=req.body||{},fast=body.phase==="fast";try{const{r,d}=await upstreamSearch(body);if(!r.ok)return res.status(r.status).json(d);const add=generic(body,d.normalizedQuery||String(body.query||"")),base=Array.isArray(d.listings)?d.listings:[],listings=merge(base,add,fast?18:MAX_RESULTS);return res.json({...d,listings,counts:counts(listings),extendedCatalogIndexed:extra.size,extendedCatalog:true})}catch(e){const add=generic(body,String(body.query||""));if(add.length)return res.json({query:body.query,condition:body.condition==="new"?"new":"used",listings:add,counts:counts(add),live:true,partial:fast,phase:fast?"fast":"full",fallback:"extended_broad_catalog",extendedCatalogIndexed:extra.size});return res.status(502).json({error:e?.message||"Delilah upstream unavailable"})}});
app.get("/api/catalog/stats",async(req,res)=>{let base={};try{const r=await fetch(`http://127.0.0.1:${v13Port}/api/catalog/stats`);if(r.ok)base=await r.json()}catch{}const vals=[...extra.values()];res.json({...base,ok:true,index:"broad-catalog-v3",baseIndexed:Number(base.indexed||0),extendedIndexed:vals.length,totalBroadIndexed:Number(base.indexed||0)+vals.length,extendedWithImages:vals.filter(c=>c.image).length,extendedPagesFetched:pagesFetched,extendedRefreshing:refreshing,extendedLastRefreshStarted:lastRefreshStarted,extendedLastRefreshFinished:lastRefreshFinished,extendedLastRefreshError:lastRefreshError,extendedSamples:vals.slice(0,10).map(c=>({title:c.title,condition:c.condition,url:c.url,page:c.page}))})});
app.get("/api/health",async(req,res)=>{try{const r=await fetch(`http://127.0.0.1:${v13Port}/api/health`),d=await r.json();res.json({...d,edge:"inventory-v14",extendedCatalog:true,extendedIndexed:extra.size,extendedRefreshing:refreshing})}catch{res.status(503).json({ok:false,edge:"inventory-v14",extendedIndexed:extra.size})}});
async function proxy(req,res){try{const headers={};for(const[k,v]of Object.entries(req.headers))if(!["host","content-length","connection"].includes(k.toLowerCase())&&v!=null)headers[k]=Array.isArray(v)?v.join(","):String(v);let body;if(!["GET","HEAD"].includes(req.method)&&req.is("application/json")){body=JSON.stringify(req.body||{});headers["content-type"]="application/json"}const r=await fetch(`http://127.0.0.1:${v13Port}${req.originalUrl}`,{method:req.method,headers,body,redirect:"manual"}),buf=Buffer.from(await r.arrayBuffer());for(const[k,v]of r.headers.entries())if(!["content-length","transfer-encoding","connection"].includes(k.toLowerCase()))res.setHeader(k,v);res.status(r.status).send(buf)}catch{res.status(502).json({error:"Delilah upstream unavailable"})}}
app.use(proxy);
app.listen(externalPort,()=>{console.log(`Delilah inventory-v14 running at http://localhost:${externalPort}`);refresh().catch(()=>{});setInterval(()=>refresh().catch(()=>{}),REFRESH_MS).unref()});
