import "dotenv/config";
import express from "express";
import crypto from "node:crypto";
import dns from "node:dns/promises";
import net from "node:net";

const app=express();
const port=process.env.PORT||3000;
const braveKey=process.env.BRAVE_SEARCH_API_KEY||"";
const MAX_RESULTS=80;
const MAX_DETAIL_FETCH=100;
const CACHE_TTL=90_000;
const BRAVE_CACHE_TTL=10*60_000;
const IMAGE_TTL=30*60_000;
const MAX_IMAGE_BYTES=8*1024*1024;
const BRAVE_GAP=1150;

const responseCache=new Map(),braveCache=new Map(),imageRegistry=new Map(),sourceHealth=new Map();
let braveTail=Promise.resolve(),braveLastAt=0;
app.use(express.json({limit:"1mb"}));
app.use(express.static("public"));

const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const norm=s=>String(s||"").replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
const arabic=s=>/[\u0600-\u06ff]/.test(String(s||""));
function safeUrl(v){try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u:null}catch{return null}}
function hostIs(h,b){h=String(h||"").toLowerCase();b=String(b||"").toLowerCase();return h===b||h.endsWith(`.${b}`)}
function canonical(v=""){const u=safeUrl(v);if(!u)return v;u.hash="";if(hostIs(u.hostname,"haraj.com.sa")&&/^\/\d{7,}(?:\/|$)/.test(u.pathname))return `https://haraj.com.sa${u.pathname}${u.search}`;return u.href}
function absolute(v,b){if(!v)return null;try{return new URL(String(v).replace(/\\u002f/gi,"/").replace(/\\\//g,"/"),b).href}catch{return null}}
function slug(s=""){return String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function direct(url,base,re){const u=safeUrl(url);return !!u&&hostIs(u.hostname,base)&&re.test(u.pathname)}
function deep(url,base,blocked=[]){const u=safeUrl(url);if(!u||!hostIs(u.hostname,base))return false;const p=u.pathname.toLowerCase().replace(/\/$/,"")||"/";if(p==="/"||blocked.some(x=>p===x||p.startsWith(`${x}/`)))return false;return p.split("/").filter(Boolean).length>=2}

const BRAND_ALIASES={jeep:"Jeep",جيب:"Jeep",toyota:"Toyota",تويوتا:"Toyota",nissan:"Nissan",نيسان:"Nissan",lexus:"Lexus",لكزس:"Lexus",mercedes:"Mercedes","mercedes-benz":"Mercedes",مرسيدس:"Mercedes",bmw:"BMW","بي ام":"BMW",porsche:"Porsche",بورش:"Porsche",ford:"Ford",فورد:"Ford",lincoln:"Lincoln",لينكون:"Lincoln",hyundai:"Hyundai",هيونداي:"Hyundai",kia:"Kia",كيا:"Kia",volkswagen:"Volkswagen",فولكس:"Volkswagen",chevrolet:"Chevrolet",شفروليه:"Chevrolet",mazda:"Mazda",مازدا:"Mazda",honda:"Honda",هوندا:"Honda",mitsubishi:"Mitsubishi",ميتسوبيشي:"Mitsubishi",geely:"Geely",جيلي:"Geely",changan:"Changan",شانجان:"Changan",gac:"GAC","جي ايه سي":"GAC",mg:"MG","ام جي":"MG",genesis:"Genesis",جينيسيس:"Genesis",jetour:"Jetour",جيتور:"Jetour",haval:"Haval",هافال:"Haval",audi:"Audi",اودي:"Audi","land rover":"Land Rover","لاند روفر":"Land Rover","range rover":"Range Rover","رينج روفر":"Range Rover",cadillac:"Cadillac",كاديلاك:"Cadillac",gmc:"GMC","جي ام سي":"GMC",dodge:"Dodge",دودج:"Dodge",suzuki:"Suzuki",سوزوكي:"Suzuki",isuzu:"Isuzu",ايسوزو:"Isuzu",peugeot:"Peugeot",بيجو:"Peugeot",renault:"Renault",رينو:"Renault",chery:"Chery",شيري:"Chery",hongqi:"Hongqi",هونشي:"Hongqi",byd:"BYD",بيوايدي:"BYD",tesla:"Tesla",تسلا:"Tesla",lucid:"Lucid",لوسيد:"Lucid"};
const MODELS=[["wrangler","Wrangler"],["رانجلر","Wrangler"],["patrol","Patrol"],["باترول","Patrol"],["land cruiser","Land Cruiser"],["لاندكروزر","Land Cruiser"],["camry","Camry"],["كامري","Camry"],["corolla","Corolla"],["كورولا","Corolla"],["yaris","Yaris"],["يارس","Yaris"],["sunny","Sunny"],["صني","Sunny"],["x5","X5"],["c200","C200"],["tucson","Tucson"],["توسان","Tucson"],["sportage","Sportage"],["سبورتاج","Sportage"],["territory","Territory"],["تيريتوري","Territory"],["tahoe","Tahoe"],["تاهو","Tahoe"],["sonata","Sonata"],["سوناتا","Sonata"],["accent","Accent"],["اكسنت","Accent"],["elantra","Elantra"],["النترا","Elantra"],["prado","Prado"],["برادو","Prado"],["fortuner","Fortuner"],["فورتشنر","Fortuner"],["explorer","Explorer"],["اكسبلورر","Explorer"],["expedition","Expedition"],["grand cherokee","Grand Cherokee"],["جراند شيروكي","Grand Cherokee"],["cayenne","Cayenne"],["كايين","Cayenne"],["tiguan","Tiguan"],["تيجوان","Tiguan"],["pegas","Pegas"],["بيجاس","Pegas"],["cerato","Cerato"],["سيراتو","Cerato"],["sorento","Sorento"],["سورينتو","Sorento"],["k5","K5"],["x70","X70"],["x50","X50"],["t2","T2"],["t1","T1"],["dashing","Dashing"],["coolray","Coolray"],["emgrand","Emgrand"],["city","City"],["civic","Civic"],["accord","Accord"],["cx-5","CX-5"],["cx5","CX-5"],["mazda 6","Mazda 6"],["arrizo 5","Arrizo 5"],["tiggo 7","Tiggo 7"],["h6","H6"],["jolion","Jolion"],["alsvin","Alsvin"],["cs35","CS35"],["cs75","CS75"]];
const MODEL_BRAND={Wrangler:"Jeep",Patrol:"Nissan","Land Cruiser":"Toyota",Camry:"Toyota",Corolla:"Toyota",Yaris:"Toyota",Sunny:"Nissan",X5:"BMW",C200:"Mercedes",Tucson:"Hyundai",Sportage:"Kia",Territory:"Ford",Tahoe:"Chevrolet",Sonata:"Hyundai",Accent:"Hyundai",Elantra:"Hyundai",Prado:"Toyota",Fortuner:"Toyota",Explorer:"Ford",Expedition:"Ford","Grand Cherokee":"Jeep",Cayenne:"Porsche",Tiguan:"Volkswagen",Pegas:"Kia",Cerato:"Kia",Sorento:"Kia",K5:"Kia",X70:"Jetour",X50:"Jetour",T1:"Jetour",T2:"Jetour",Dashing:"Jetour",Coolray:"Geely",Emgrand:"Geely",City:"Honda",Civic:"Honda",Accord:"Honda","CX-5":"Mazda","Mazda 6":"Mazda","Arrizo 5":"Chery","Tiggo 7":"Chery",H6:"Haval",Jolion:"Haval",Alsvin:"Changan",CS35:"Changan",CS75:"Changan"};
const AR_MODEL={Wrangler:"رانجلر",Patrol:"باترول","Land Cruiser":"لاندكروزر",Camry:"كامري",Corolla:"كورولا",Yaris:"يارس",Sunny:"صني",Tucson:"توسان",Sportage:"سبورتاج",Tahoe:"تاهو",Sonata:"سوناتا",Accent:"اكسنت",Elantra:"النترا",Prado:"برادو",Fortuner:"فورتشنر"};
function detectBrand(t=""){const q=norm(t).toLowerCase();for(const[k,v]of Object.entries(BRAND_ALIASES))if(q.includes(k))return v;return null}
function detectModel(t=""){const q=norm(t).toLowerCase();for(const[k,v]of MODELS)if(q.includes(k))return v;return null}
function intentFrom(query,filters={}){const q=norm(query.toLowerCase()),model=detectModel(q),brand=detectBrand(q)||MODEL_BRAND[model]||null;const i={brand,model,minYear:null,maxYear:null,maxPrice:null,maxMileage:null,city:null};const ys=[...q.matchAll(/\b(20\d{2})\b/g)].map(x=>+x[1]);if(ys.length)i.minYear=Math.min(...ys);const p=q.match(/(?:under|below|less than|تحت|اقل من|أقل من)\s*(\d{2,7})/);if(p)i.maxPrice=+p[1];const km=q.match(/(?:under|below|less than|تحت|اقل من|أقل من)\s*(\d{2,7})\s*(?:km|كم|كيلو)/);if(km)i.maxMileage=+km[1];if(/riyadh|الرياض/.test(q))i.city="Riyadh";else if(/jeddah|جدة/.test(q))i.city="Jeddah";else if(/dammam|الدمام/.test(q))i.city="Dammam";return{...i,minYear:+filters.minYear||i.minYear,maxYear:+filters.maxYear||i.maxYear,maxPrice:+filters.maxPrice||i.maxPrice,maxMileage:+filters.maxMileage||i.maxMileage,city:filters.city||i.city}}

const S=(name,type,seller,conditions,priority,baseHost,strict,isCandidate,brands=[])=>({name,type,seller,conditions,priority,baseHost,strict,isCandidate,brands});
const SOURCES=[
S("Haraj","marketplace","Haraj",["new","used"],100,"haraj.com.sa",true,u=>direct(u,"haraj.com.sa",/^\/\d{7,}(?:\/|$)/)),
S("Syarah","marketplace","Syarah",["new","used"],99,"syarah.com",true,u=>direct(u,"syarah.com",/^\/(?:(?:en|ar)\/)?cardetail\/[^/]+-\d+\/?$/i)),
S("CarSwitch Saudi","marketplace","CarSwitch Saudi",["used"],98,"carswitch.com",true,u=>{const x=safeUrl(u);if(!x||!hostIs(x.hostname,"carswitch.com"))return false;const p=x.pathname.toLowerCase().replace(/\/$/,"");return p.includes("/used-cars/")&&!/(\/search|\/used-cars)$/.test(p)&&p.split("/").filter(Boolean).length>=3}),
S("Carly","certified_used","Carly - كارلي",["new","used"],98,"halacarly.com",true,u=>direct(u,"halacarly.com",/^\/(?:en|ar)\/vehicle-details\/[^/]+\/?$/i)),
S("Saleh Cars","independent_dealer","Saleh Cars Group",["new"],97,"salehcars.com",true,u=>direct(u,"salehcars.com",/^\/(?:en\/)?cars\/[a-f0-9]{20,32}\/[^/]+\/?$/i)),
S("Motory","marketplace","Motory",["new","used"],96,"motory.com",true,u=>direct(u,"motory.com",/^\/en\/cars-for-sale\/(?:[^/]+-haraj\/)?[^/]+\/[^/]+\/20\d{2}\/\d+\/?$/i)),
S("OpenSooq","marketplace","OpenSooq",["new","used"],90,"opensooq.com",false,u=>{const x=safeUrl(u);if(!x||!hostIs(x.hostname,"opensooq.com"))return false;const p=x.pathname.toLowerCase();return !/\/reviews?(\/|$)/.test(p)&&/\/(?:ad|listing|post)\//.test(p)&&/\d{5,}/.test(p)}),
S("Key Used Cars","independent_dealer","Key Used Cars",["used"],87,"key.sa",false,u=>deep(u,"key.sa",["/en","/ar","/en/car-selling-saudi-arabia"])),
S("Toyota ALJ","official_dealer","Abdul Latif Jameel Motors",["new"],93,"toyota.com.sa",false,u=>deep(u,"toyota.com.sa",["/en","/en/vehicles"]),["Toyota"]),
S("Lexus ALJ","official_dealer","Lexus Abdul Latif Jameel",["new"],92,"lexus.com.sa",false,u=>deep(u,"lexus.com.sa",["/en"]),["Lexus"]),
S("Nissan Petromin","official_dealer","Petromin Nissan",["new"],92,"petromin-nissan.com",false,u=>deep(u,"petromin-nissan.com",["/","/vehicles"]),["Nissan"]),
S("Ford Al Jazirah","official_dealer","Al Jazirah Vehicles Agencies",["new"],91,"aljazirahford.com",false,u=>deep(u,"aljazirahford.com",["/"]),["Ford","Lincoln"]),
S("Mercedes Juffali","official_dealer","Juffali Automotive Company",["new","used"],91,"mercedes-benz-mena.com",false,u=>deep(u,"mercedes-benz-mena.com",["/ksa/en","/ksa/en/new-models","/ksa/en/buy-new"]),["Mercedes"]),
S("BMW Naghi","official_dealer","Mohamed Yousuf Naghi Motors BMW",["new","used"],91,"bmw-saudiarabia.com",false,u=>deep(u,"bmw-saudiarabia.com",["/","/models","/new-models"]),["BMW"]),
S("Kia Aljabr","official_dealer","Aljabr Kia",["new"],89,"kia.com",false,u=>deep(u,"kia.com",["/aljabr/en"]),["Kia"]),
S("Porsche SAMACO","official_dealer","SAMACO Porsche",["new","used"],90,"samaco.com.sa",false,u=>deep(u,"samaco.com.sa",["/en/porsche"]),["Porsche"]),
S("Volkswagen SAMACO","certified_used","SAMACO Volkswagen",["new","used"],88,"vw.com.sa",false,u=>deep(u,"vw.com.sa",["/"]),["Volkswagen"]),
S("Chevrolet Saudi Dealers","official_dealer","Aljomaih / Universal Motors",["new"],87,"chevroletarabia.com",false,u=>deep(u,"chevroletarabia.com",["/sa-en"]),["Chevrolet"])
];
function enabledSources(condition,intent,filters){let x=SOURCES.filter(s=>s.conditions.includes(condition));if(filters.sourceType)x=x.filter(s=>s.type===filters.sourceType);if(filters.seller)x=x.filter(s=>s.name===filters.seller);if(intent.brand)x=x.filter(s=>!s.brands.length||s.brands.some(b=>b.toLowerCase()===intent.brand.toLowerCase()));return x.sort((a,b)=>b.priority-a.priority)}

function coreTerms(intent){return[intent.brand,intent.model,intent.minYear].filter(Boolean).join(" ")}
function discoveryQuery(source,query,condition,intent){const core=coreTerms(intent)||query;switch(source.name){case"Syarah":return `"${core}" "Post Number" site:syarah.com/en/cardetail`;case"Motory":return `"${core}" "Vehicle ID" site:ksa.motory.com/en/cars-for-sale`;case"Saleh Cars":return `"${core}" "Buy Car" site:salehcars.com/cars/`;case"Haraj":return `${arabic(query)?(AR_MODEL[intent.model]||intent.model||core):core} ${intent.minYear||""} للبيع site:haraj.com.sa`;case"Carly":return `"${core}" site:halacarly.com/vehicle-details`;case"CarSwitch Saudi":return `"${core}" site:ksa.carswitch.com used car`;default:return `${core} ${condition==="used"?"used":"new"} site:${source.baseHost}`}}
function seedUrls(source,intent,condition){const out=[],b=slug(intent.brand),m=slug(intent.model),y=intent.minYear?String(intent.minYear):"";if(source.name==="Syarah"&&b&&m){out.push(`https://syarah.com/en/autos/${b}/${m}${y?`/${y}`:""}`)}if(source.name==="Motory"&&b&&m){out.push(`https://ksa.motory.com/en/cars-for-sale/${b}/${m}/${y?`${y}/`:""}`);if(intent.city)out.push(`https://ksa.motory.com/en/cars-for-sale/${slug(intent.city)}-haraj/${b}/${m}/${y?`${y}/`:""}`)}if(source.name==="Haraj"&&intent.model){const t=`${arabic(intent.model)?intent.model:(AR_MODEL[intent.model]||intent.model)}${y?` ${y}`:""}`;out.push(`https://haraj.com.sa/tags/${encodeURIComponent(t)}/`)}return out}

async function braveNow(q){const hit=braveCache.get(q);if(hit&&Date.now()-hit.at<BRAVE_CACHE_TTL)return hit.value;if(!braveKey)throw new Error("BRAVE_SEARCH_API_KEY is missing");const u=new URL("https://api.search.brave.com/res/v1/web/search");u.searchParams.set("q",q);u.searchParams.set("country","SA");u.searchParams.set("count","20");u.searchParams.set("text_decorations","false");let err;for(let a=0;a<3;a++){const c=new AbortController(),timer=setTimeout(()=>c.abort(),10000);try{const r=await fetch(u,{signal:c.signal,headers:{Accept:"application/json","Accept-Encoding":"gzip","X-Subscription-Token":braveKey}});if(r.ok){const d=await r.json(),v=d.web?.results||[];braveCache.set(q,{at:Date.now(),value:v});return v}err=new Error(`Brave ${r.status}`);if(r.status!==429&&r.status<500)throw err;const ra=Number(r.headers.get("retry-after")||0);if(ra)await sleep(Math.min(ra*1000,5000))}catch(e){err=e}finally{clearTimeout(timer)}if(a<2)await sleep(500*2**a)}throw err||new Error("Brave failed")}
function brave(q){const job=braveTail.then(async()=>{const w=Math.max(0,BRAVE_GAP-(Date.now()-braveLastAt));if(w)await sleep(w);const v=await braveNow(q);braveLastAt=Date.now();return v});braveTail=job.catch(()=>{});return job}

async function fetchHtml(url,timeout=8000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"User-Agent":"Mozilla/5.0 (compatible; DelilahCarSearch/5.0)",Accept:"text/html,application/xhtml+xml"}});if(!r.ok)return null;const ct=r.headers.get("content-type")||"";if(!ct.includes("text/html"))return null;return{url:canonical(r.url||url),html:(await r.text()).slice(0,2500000)}}catch{return null}finally{clearTimeout(timer)}}
function decode(s=""){return String(s).replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function strip(h=""){return decode(String(h).replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ")).trim()}
function meta(h,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const a=new RegExp(`<meta[^>]+(?:property|name|itemprop)=["']${k}["'][^>]+content=["']([^"']+)["']`,`i`).exec(h)||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name|itemprop)=["']${k}["']`,`i`).exec(h);return a?decode(a[1]):null}
function titleOf(h=""){const h1=strip(/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(h)?.[1]||""),og=meta(h,"og:title")||"",t=strip(/<title[^>]*>([\s\S]*?)<\/title>/i.exec(h)?.[1]||"");const candidates=[h1,og,t].filter(x=>x&& !/^20\d{2}$/.test(x.trim()));return(candidates[0]||h1||og||t).slice(0,260)}
function priceNum(v){if(v==null)return null;const n=Number(String(v).replace(/[^0-9.]/g,""));return Number.isFinite(n)&&n>=1000&&n<=5000000?n:null}
function jsonObjects(node,out=[]){if(!node)return out;if(Array.isArray(node)){for(const x of node)jsonObjects(x,out);return out}if(typeof node!=="object")return out;out.push(node);for(const v of Object.values(node))if(v&&typeof v==="object")jsonObjects(v,out);return out}
function ld(h){const out=[];for(const m of String(h).matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi))try{jsonObjects(JSON.parse(m[1]),out)}catch{}return out}
function rejectImage(u="",ctx=""){return !/^https?:/.test(u)||/(logo|favicon|icon|sprite|placeholder|default[-_]?image|brandmark|social[-_]?share|avatar|profile|whatsapp|payment|footer|header|badge|app-store|google-play)/i.test(`${u} ${ctx}`)}
function pushImg(arr,v,base,score,ctx=""){if(!v)return;for(const p of String(v).split(",").map(x=>x.trim().split(/\s+/)[0]).filter(Boolean)){const u=absolute(p,base);if(u&&!rejectImage(u,ctx))arr.push({u,score,ctx})}}
function bestImage(h,base,source){const a=[];for(const o of ld(h)){const imgs=Array.isArray(o.image)?o.image:[o.image];for(const im of imgs)if(im)pushImg(a,typeof im==="string"?im:(im.url||im.contentUrl),base,120,"vehicle jsonld")}pushImg(a,meta(h,"og:image"),base,112,"og");pushImg(a,meta(h,"twitter:image"),base,105,"twitter");for(const m of String(h).matchAll(/<(?:img|source)\b([^>]+)>/gi)){const x=m[1],alt=/(?:alt|title)=["']([^"']*)["']/i.exec(x)?.[1]||"";for(const k of["src","data-src","data-lazy-src","data-original","data-image","srcset","data-srcset"]){const v=new RegExp(`${k}=["']([^"']+)["']`,`i`).exec(x)?.[1];if(v)pushImg(a,v,base,/srcset/.test(k)?80:86,alt)}}for(const x of a){const u=safeUrl(x.u);if(!u){x.score=-1;continue}if(/(car|vehicle|gallery|listing|product|upload|media)/i.test(u.pathname))x.score+=10;if(source.name==="Syarah"&&(hostIs(u.hostname,"syarah.com")||u.hostname.includes("syarah")))x.score+=20;if(source.name==="Motory"&&(hostIs(u.hostname,"amazonaws.com")||hostIs(u.hostname,"motory.com")))x.score+=20;if(source.name==="Saleh Cars"&&(hostIs(u.hostname,"amazonaws.com")||hostIs(u.hostname,"salehcars.com")))x.score+=20}return a.sort((x,y)=>y.score-x.score)[0]?.u||null}
function anchorCandidates(h,base,source,provenance="seed"){const out=[],seen=new Set();for(const m of String(h).matchAll(/<a\b([^>]*href=["'][^"']+["'][^>]*)>([\s\S]*?)<\/a>/gi)){const href=/href=["']([^"']+)["']/i.exec(m[1])?.[1],url=canonical(absolute(href,base));if(!url||!source.isCandidate(url)||seen.has(url))continue;seen.add(url);const body=m[2],title=strip(body).slice(0,500);let image=null;const tag=/<(?:img|source)\b([^>]+)>/i.exec(body)?.[1]||"";for(const k of["src","data-src","data-lazy-src","data-original","srcset","data-srcset"]){const v=new RegExp(`${k}=["']([^"']+)["']`,`i`).exec(tag)?.[1];if(v){const x=absolute(String(v).split(",")[0].trim().split(/\s+/)[0],base);if(x&&!rejectImage(x,title)){image=x;break}}}out.push({url,title,description:title,catalogImage:image,source,provenance})}return out}
async function expandSeed(url,source){const d=await fetchHtml(url);return d?anchorCandidates(d.html,d.url,source,"seed"):[]}

async function discoverSource(source,query,condition,intent){const out=[],seen=new Set(),q=discoveryQuery(source,query,condition,intent),seedList=seedUrls(source,intent,condition);let braveErr=null;const tasks=[brave(q),...seedList.map(s=>expandSeed(s,source))];const rs=await Promise.allSettled(tasks);if(rs[0].status==="fulfilled")for(const r of rs[0].value){if(!r.url||!hostIs(safeUrl(r.url)?.hostname,source.baseHost))continue;const url=canonical(r.url);if(source.isCandidate(url)&&!seen.has(url)){seen.add(url);out.push({...r,url,source,provenance:"search"})}}else braveErr=rs[0].reason?.message||"search failed";for(const r of rs.slice(1))if(r.status==="fulfilled")for(const c of r.value)if(!seen.has(c.url)){seen.add(c.url);out.push(c)};
// one precision retry for core sources if both indexed search and deterministic seed were empty
if(!out.length&&["Syarah","Motory","Saleh Cars"].includes(source.name)){const core=coreTerms(intent)||query;const rq=source.name==="Syarah"?`"${core}" "Condition:${condition}" site:syarah.com/en/cardetail`:source.name==="Motory"?`"${core}" "Listing #" site:ksa.motory.com/en/cars-for-sale`: `"${core}" "SAR" site:salehcars.com/en/cars/`;try{for(const r of await brave(rq))if(r.url&&source.isCandidate(r.url)){const u=canonical(r.url);if(!seen.has(u)){seen.add(u);out.push({...r,url:u,source,provenance:"search_retry"})}}}catch(e){braveErr=e.message}}
sourceHealth.set(source.name,{ok:out.length>0,lastChecked:new Date().toISOString(),candidates:out.length,seeds:seedList.length,lastError:braveErr});return out.slice(0,60)}
async function discoverAll(query,condition,intent,filters){const sources=enabledSources(condition,intent,filters),runs=await Promise.allSettled(sources.map(s=>discoverSource(s,query,condition,intent)),),out=[],seen=new Set();for(const r of runs)if(r.status==="fulfilled")for(const c of r.value){const k=canonical(c.url).replace(/\/$/,"");if(!seen.has(k)){seen.add(k);out.push(c)}}return out.slice(0,220)}

const PARTS=/(قطع غيار|صدام|طرمبة|فحمات|مساعدات|شمعات|كفرات|جنط|جنوط|مكينة|قير للبيع|باب|كبوت|تيربو|راديتر|اكسسوارات|bumper|headlight|taillight|spare parts|engine part|gearbox part)/i;
function explicitCondition(t=""){const s=norm(t);let m=s.match(/Condition\s*:?\s*(New|Used)\b/i);if(m)return m[1].toLowerCase();m=s.match(/الحالة\s*:?\s*(جديد|جديدة|مستعمل|مستعملة)/i);if(m)return /جديد/.test(m[1])?"new":"used";return null}
function fields(text="",preferred=""){const t=norm(`${preferred} ${text}`),p=norm(preferred),model=detectModel(p)||detectModel(t),brand=detectBrand(p)||detectBrand(t)||MODEL_BRAND[model]||null;const ys=[...p.matchAll(/\b(20\d{2})\b/g)].map(x=>+x[1]);const ys2=[...t.matchAll(/\b(20\d{2})\b/g)].map(x=>+x[1]);const year=ys.find(y=>y>=2000&&y<=2035)||ys2.find(y=>y>=2000&&y<=2035)||null;const km=t.match(/([0-9][\d,]{0,8})\s*(?:km|kilometers?|كم|كيلو)/i),mileage=km?+km[1].replace(/,/g,""):null;const city=/riyadh|الرياض/i.test(t)?"Riyadh":/jeddah|جدة/i.test(t)?"Jeddah":/dammam|الدمام/i.test(t)?"Dammam":null;const pm=t.match(/(?:SAR|ر\.س)\s*([1-9][\d,]{3,8})|([1-9][\d,]{3,8})\s*(?:SAR|ريال|ر\.س)/i);return{brand,model,year,mileage,city,price:pm?+(pm[1]||pm[2]).replace(/,/g,""):null,explicit:explicitCondition(t),newSignal:/\bnew\b|brand new|جديد|جديدة|زيرو|صفر كيلو/i.test(t),usedSignal:/\bused\b|pre-owned|مستعمل|مستعملة|ممشى/i.test(t)}}
function conditionOf(f,requested,source){if(f.explicit)return f.explicit;if(source.conditions.length===1)return source.conditions[0];if(f.mileage===0)return"new";if(f.mileage>100)return"used";if(f.newSignal&&!f.usedSignal)return"new";if(f.usedSignal&&!f.newSignal)return"used";return requested}
function matchCar(c,i,condition){if(c.condition!==condition)return false;if(i.brand&&c.brand&&c.brand!==i.brand)return false;if(i.model&&c.model&&c.model!==i.model)return false;if(i.minYear&&c.year&&c.year<i.minYear)return false;if(i.maxYear&&c.year&&c.year>i.maxYear)return false;if(i.maxPrice&&c.price&&c.price>i.maxPrice)return false;if(i.maxMileage&&c.mileage!=null&&c.mileage>i.maxMileage)return false;if(i.city&&c.city&&c.city!==i.city)return false;return true}
function saleInspect(h,url,source){const text=strip(h).slice(0,120000),title=titleOf(h);let price=null,offer=false,vehicle=false;for(const o of ld(h)){const typ=Array.isArray(o?.["@type"])?o["@type"]:[o?.["@type"]];if(typ.filter(Boolean).some(x=>/vehicle|car|product|individualproduct/i.test(String(x))))vehicle=true;if(o.offers||typ.filter(Boolean).some(x=>/offer/i.test(String(x))))offer=true;const of=Array.isArray(o.offers)?o.offers[0]:o.offers;if(!price&&of)price=priceNum(of.price||of.lowPrice||of.highPrice);if(!price)price=priceNum(o.price)}price=price||priceNum(meta(h,"product:price:amount")||meta(h,"price"));const explicit=/(for sale|cash price|selling price|contact seller|buy car|book it now|post number|listing\s*#|vehicle id|للبيع|شراء السيارة|رقم الإعلان|السعر)/i.test(text),info=/(\/news\/|\/blog\/|\/guide\/|\/reviews?\/|brochure|press-release)/i.test(url);return{saleVerified:!info&&(source.isCandidate(url)||offer||(vehicle&&explicit)||explicit),title,text,price,image:bestImage(h,url,source)}}
async function detail(c){const d=await fetchHtml(c.url,7000);if(!d)return null;if(c.source.strict&&!c.source.isCandidate(d.url))return null;return{...saleInspect(d.html,d.url,c.source),url:d.url}}
async function mapLimit(items,n,fn){const out=new Array(items.length);let k=0;async function w(){for(;;){const i=k++;if(i>=items.length)return;out[i]=await fn(items[i],i)}}await Promise.all(Array.from({length:Math.min(n,items.length)},w));return out}
function imageHostAllowed(h,s){if(s?.baseHost&&hostIs(h,s.baseHost))return true;return["syarah.com","carswitch.com","halacarly.com","salehcars.com","motory.com","haraj.com.sa","amazonaws.com","cloudfront.net","googleusercontent.com","googleapis.com","imgix.net"].some(b=>hostIs(h,b))}
function imageToken(url,source){const u=safeUrl(url);if(!u||!imageHostAllowed(u.hostname,source))return null;const t=crypto.createHash("sha256").update(`${source.name}|${u.href}`).digest("hex").slice(0,28);imageRegistry.set(t,{url:u.href,source:source.name,at:Date.now()});return`/api/image/${t}`}
function score(c,i){let s=50;if(c.saleVerified)s+=15;if(c.imageVerified)s+=10;if(c.price)s+=5;if(c.mileage!=null)s+=4;if(c.city)s+=2;if(i.brand&&c.brand===i.brand)s+=6;if(i.model&&c.model===i.model)s+=6;if(c.sourceStrict)s+=2;return Math.min(s,99)}
async function build(candidates,requested,intent){const x=candidates.slice(0,MAX_DETAIL_FETCH),pages=await mapLimit(x,9,detail),out=[];for(let i=0;i<x.length;i++){const r=x[i],p=pages[i],directOk=r.source.strict&&r.source.isCandidate(r.url);if(!directOk&&(!p||!p.saleVerified))continue;const title=p?.title||r.title||"",combined=`${r.title||""} ${r.description||""} ${p?.text||""}`;if(r.source.name==="Haraj"&&PARTS.test(`${title} ${r.description||""}`))continue;const f=fields(combined,title);if(!f.brand&&intent.brand&&r.provenance==="seed")f.brand=intent.brand;if(!f.model&&intent.model&&r.provenance==="seed")f.model=intent.model;if(intent.model&&!f.model&&!p)continue;const image=p?.image||r.catalogImage||null,imageSource=p?.image?"listing_page":r.catalogImage?"source_catalog":null;const c={source:r.source.name,sourceType:r.source.type,seller:r.source.seller,sourceStrict:r.source.strict,title:title||r.title||[intent.brand,intent.model,f.year].filter(Boolean).join(" "),snippet:r.description||"",url:canonical(p?.url||r.url),brand:f.brand,model:f.model,year:f.year,mileage:f.mileage,city:f.city,price:p?.price||f.price||null,condition:conditionOf(f,requested,r.source),saleVerified:Boolean(directOk||p?.saleVerified),image,imageVerified:Boolean(image),imageSource};if(!matchCar(c,intent,requested))continue;c.displayImage=image?(imageToken(image,r.source)||image):null;c.score=score(c,intent);out.push(c)}const seen=new Set();return out.filter(c=>{const k=canonical(c.url).replace(/\/$/,"");if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>b.score-a.score).slice(0,MAX_RESULTS)}
function summary(q,cars,condition){if(!cars.length)return arabic(q)?`ما لقيت سيارات ${condition==="new"?"جديدة":"مستعملة"} مؤكدة تطابق طلبك حالياً.`:`I couldn't find verified ${condition} cars matching your request.`;const imgs=cars.filter(c=>c.imageVerified).length,sources=new Set(cars.map(c=>c.source)).size;return arabic(q)?`لقيت ${cars.length} سيارة حقيقية للبيع من ${sources} مصادر، ${imgs} منها بصور مرتبطة بالإعلان.`:`I found ${cars.length} real cars for sale across ${sources} sources; ${imgs} have verified listing-linked images.`}

function privateIp(ip){if(!ip)return true;if(net.isIP(ip)===4){const p=ip.split(".").map(Number);return p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||p[0]===0}const x=ip.toLowerCase();return x==="::1"||x.startsWith("fc")||x.startsWith("fd")||x.startsWith("fe80:")}
async function publicHost(h){if(/^(localhost|.*\.localhost)$/i.test(h))throw new Error("blocked");const rows=await dns.lookup(h,{all:true,verbatim:true});if(!rows.length||rows.some(r=>privateIp(r.address)))throw new Error("blocked")}

app.get("/api/health",(req,res)=>res.json({ok:true,search:Boolean(braveKey),sources:SOURCES.length,logic:"inventory-v5",maxResults:MAX_RESULTS,images:"exact listing/source-card + guarded relay"}));
app.get("/api/sources",(req,res)=>res.json({sources:SOURCES.map(({name,type,seller,brands,conditions})=>({name,type,seller,brands,conditions}))}));
app.get("/api/diagnostics",(req,res)=>res.json({ok:true,logic:"inventory-v5",responseCache:responseCache.size,braveCache:braveCache.size,imageTokens:imageRegistry.size,sources:SOURCES.map(s=>({name:s.name,...(sourceHealth.get(s.name)||{ok:null,candidates:0,seeds:0,lastChecked:null})}))}));
app.get("/api/image/:token",async(req,res)=>{const e=imageRegistry.get(req.params.token);if(!e||Date.now()-e.at>IMAGE_TTL)return res.status(404).end();const u=safeUrl(e.url),s=SOURCES.find(x=>x.name===e.source);if(!u||!s||!imageHostAllowed(u.hostname,s))return res.status(403).end();const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);try{await publicHost(u.hostname);const r=await fetch(u,{signal:c.signal,redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 (compatible; DelilahImageRelay/3.0)",Accept:"image/avif,image/webp,image/apng,image/*,*/*;q=0.8",Referer:`https://${s.baseHost}/`}});if(!r.ok)return res.status(502).end();const ct=(r.headers.get("content-type")||"").toLowerCase();if(!ct.startsWith("image/"))return res.status(415).end();const len=+(r.headers.get("content-length")||0);if(len&&len>MAX_IMAGE_BYTES)return res.status(413).end();const buf=Buffer.from(await r.arrayBuffer());if(!buf.length||buf.length>MAX_IMAGE_BYTES)return res.status(413).end();res.set({"Content-Type":ct,"Cache-Control":"public, max-age=3600, stale-while-revalidate=86400","X-Content-Type-Options":"nosniff"});res.send(buf)}catch{res.status(502).end()}finally{clearTimeout(timer)}});
app.post("/api/search",async(req,res)=>{try{const query=String(req.body?.query||"").trim();if(!query)return res.status(400).json({error:"Query is required"});if(query.length>300)return res.status(400).json({error:"Query is too long"});const condition=req.body?.condition==="new"?"new":"used",filters=req.body?.filters&&typeof req.body.filters==="object"?req.body.filters:{},key=JSON.stringify({q:query.toLowerCase(),condition,filters}),hit=responseCache.get(key);if(hit&&Date.now()-hit.at<CACHE_TTL)return res.json({...hit.value,cached:true});const intent=intentFrom(query,filters),raw=await discoverAll(query,condition,intent,filters),listings=await build(raw,condition,intent),counts=listings.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{}),value={query,condition,intent,answer:summary(query,listings,condition),listings,counts,rawCandidates:raw.length,live:true,cached:false,provider:"Delilah inventory-v5 deterministic catalogs + indexed direct listings"};responseCache.set(key,{at:Date.now(),value});for(const[k,v]of responseCache)if(Date.now()-v.at>CACHE_TTL)responseCache.delete(k);for(const[k,v]of imageRegistry)if(Date.now()-v.at>IMAGE_TTL)imageRegistry.delete(k);res.json(value)}catch(e){console.error(e);res.status(500).json({error:e.message||"Live search failed"})}});

app.listen(port,()=>console.log(`Delilah inventory-v5 running at http://localhost:${port}`));
