import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 3000);
const BRAVE_KEY = process.env.BRAVE_SEARCH_API_KEY || '';
const OPENAI_KEY = process.env.OPENAI_API_KEY || '';
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-5.6-luna';
const app = express();
const cache = new Map();
const progress = new Map();
const TTL = 8 * 60_000;

app.use(express.json({ limit: '1mb' }));
app.use(express.static(path.join(__dirname, 'public')));

const digits=s=>String(s||'').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const norm=s=>digits(s).toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').replace(/\s+/g,' ').trim();
const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim();
const canonical=v=>{try{const u=new URL(v);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}};
function years(q=''){return[...digits(q).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(m=>Number(m[1])).filter(y=>y>=1980&&y<=2035)}
function hasRange(q=''){return/(?:and above|or newer|and newer|or later|above|from|since|after|to|through|until|between|وفوق|واكثر|وأكثر|احدث|أحدث|من موديل|بعد|الى|إلى|حتى|بين)/i.test(norm(q))}
function exactYear(q=''){const y=years(q);return y.length===1&&!hasRange(q)?y[0]:null}
function yearOf(t=''){return years(t)[0]||null}
function mileageOf(t=''){const m=digits(t).match(/([0-9][\d,]{0,8})\s*(?:km|كيلو|كم)/i);return m?Number(m[1].replace(/,/g,'')):null}
function priceOf(t=''){const x=digits(t);for(const r of[/(?:price|السعر)\s*[:：]?\s*([0-9][\d,]{3,9})/i,/([0-9][\d,]{3,9})\s*(?:sar|ريال|ر\.?س)/i]){const m=x.match(r);if(m){const n=Number(m[1].replace(/,/g,''));if(n>=1000&&n<=5000000)return n}}return null}
function cityOf(t=''){const n=norm(t);if(/riyadh|الرياض/.test(n))return'Riyadh';if(/jeddah|جده/.test(n))return'Jeddah';if(/dammam|الدمام/.test(n))return'Dammam';if(/khobar|الخبر/.test(n))return'Khobar';if(/makkah|مكه/.test(n))return'Makkah';if(/madinah|المدينه/.test(n))return'Madinah';if(/taif|الطايف|الطائف/.test(n))return'Taif';return null}
function conditionOf(t='',source=''){const n=norm(t);if(/\bused\b|مستعمل/.test(n))return'used';if(/\bnew\b|جديد|زيرو/.test(n))return'new';return source==='Saleh Cars'?'new':'used'}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`<meta[^>]+(?:property|name)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)?.[1]||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${k}["'][^>]*>`,'i').exec(html)?.[1]||null}
function abs(v,b){try{return new URL(String(v||'').replace(/&amp;/g,'&'),b).href}catch{return null}}
function imageOkay(v=''){try{const u=new URL(v);return/^https?:$/.test(u.protocol)&&!/(logo|favicon|icon|placeholder|avatar|banner|sprite)/i.test(u.href)}catch{return false}}
function inferIdentity(title=''){const clean=String(title).replace(/\s*\|.*$/,'').trim(),y=yearOf(clean),tokens=clean.replace(/\b(?:19|20)\d{2}\b/g,'').split(/\s+/).filter(Boolean);return{brand:tokens[0]||null,model:tokens.slice(1,4).join(' ')||null,year:y}}
function directHaraj(v=''){try{const u=new URL(v);return/(^|\.)haraj\.com\.sa$/i.test(u.hostname)&&/^\/(?:en\/)?\d{8,14}(?:\/|$)/.test(u.pathname)}catch{return false}}
function directSaleh(v=''){try{const u=new URL(v);return/(^|\.)salehcars\.com$/i.test(u.hostname)&&/^\/(?:en\/)?cars\/[A-Za-z0-9_-]{10,40}\/[^/]+\/?$/i.test(u.pathname)}catch{return false}}
function directYalla(v=''){try{const u=new URL(v);return/(^|\.)yallamotor\.com$/i.test(u.hostname)&&/\/used-cars\//i.test(u.pathname)}catch{return false}}

async function brave(q,count=20){if(!BRAVE_KEY)return[];const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',q);u.searchParams.set('count',String(count));u.searchParams.set('country','sa');const r=await fetch(u,{headers:{Accept:'application/json','X-Subscription-Token':BRAVE_KEY},signal:AbortSignal.timeout(9000)});if(!r.ok)throw new Error(`Brave ${r.status}`);return(await r.json())?.web?.results||[]}
async function fetchHtml(url){const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Dalelah/1.1)','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{html:(await r.text()).slice(0,3000000),url:r.url||url}}
async function parseListing(url,source,seed={}){const d=await fetchHtml(url),text=strip(d.html),title=strip(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i.exec(d.html)?.[1]||'')||meta(d.html,'og:title')||seed.title||`${source} vehicle`,id=inferIdentity(title),img=abs(meta(d.html,'og:image')||meta(d.html,'twitter:image'),d.url),price=priceOf(`${title} ${text.slice(0,12000)}`)||priceOf(seed.description||'');return{source,sourceType:source==='Saleh Cars'?'independent_dealer':'marketplace',seller:source,title:title.slice(0,220),snippet:text.slice(0,700),url:canonical(d.url),brand:id.brand,model:id.model,year:id.year||yearOf(text),mileage:mileageOf(text),city:cityOf(text),price,priceVerified:Boolean(price),condition:conditionOf(`${title} ${text.slice(0,4000)}`,source),saleVerified:true,image:img&&imageOkay(img)?img:null,displayImage:img&&imageOkay(img)?img:null,imageVerified:Boolean(img&&imageOkay(img)),score:92,discovery:'v1.1_direct'}}
async function sourceSearch(query,source,count=20){const key=`${source}|${norm(query)}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL)return hit.value;const site=source==='Haraj'?'haraj.com.sa':source==='Saleh Cars'?'salehcars.com/cars':'ksa.yallamotor.com/used-cars',valid=source==='Haraj'?directHaraj:source==='Saleh Cars'?directSaleh:directYalla,rs=(await brave(`site:${site} ${query}`,count)).filter(r=>valid(r.url)),out=[];let i=0;async function worker(){for(;;){const n=i++;if(n>=rs.length)return;const r=rs[n];try{out.push(await parseListing(r.url,source,r))}catch{const id=inferIdentity(r.title||''),text=`${r.title||''} ${r.description||''}`,p=priceOf(text);out.push({source,sourceType:source==='Saleh Cars'?'independent_dealer':'marketplace',seller:source,title:r.title||`${source} vehicle`,snippet:r.description||'',url:canonical(r.url),brand:id.brand,model:id.model,year:id.year||yearOf(text),mileage:mileageOf(text),city:cityOf(text),price:p,priceVerified:Boolean(p),condition:conditionOf(text,source),saleVerified:true,image:null,displayImage:null,imageVerified:false,score:82,discovery:'v1.1_search'})}}}await Promise.all(Array.from({length:Math.min(5,rs.length||1)},worker));cache.set(key,{at:Date.now(),value:out});return out}
function merge(...groups){const m=new Map();for(const g of groups)for(const c of g||[]){if(!c?.url)continue;const k=canonical(c.url),old=m.get(k);m.set(k,old?{...c,...old,image:old.image||c.image,displayImage:old.displayImage||c.displayImage,price:old.price||c.price,priceVerified:Boolean(old.priceVerified||c.priceVerified)}:c)}return[...m.values()]}
function hardMatch(c,intent,condition,y){if(condition&&c.condition&&c.condition!==condition)return false;if(y&&c.year&&Number(c.year)!==y)return false;if(intent.minYear&&c.year&&c.year<intent.minYear)return false;if(intent.maxYear&&c.year&&c.year>intent.maxYear)return false;if(intent.maxPrice&&c.price&&c.price>intent.maxPrice)return false;if(intent.maxMileage&&c.mileage!=null&&c.mileage>intent.maxMileage)return false;if(intent.city&&c.city&&norm(c.city)!==norm(intent.city))return false;return true}
function score(c,intent,y){let s=70,t=norm(`${c.brand||''} ${c.model||''} ${c.title||''}`);if(intent.make&&t.includes(norm(intent.make)))s+=8;if(intent.model&&t.includes(norm(intent.model)))s+=10;if(y&&Number(c.year)===y)s+=8;if(c.priceVerified)s+=2;if(c.imageVerified)s+=1;return{...c,aiScore:Math.min(100,s),aiReason:y&&Number(c.year)===y?'Exact year match':c.priceVerified?'Verified source listing':'Direct source listing'}}
async function aiIntent(query,previousIntent=null){const y=exactYear(query),fallback={make:null,model:null,condition:null,city:null,minYear:y,maxYear:y,minPrice:null,maxPrice:null,maxMileage:null,bodyType:null,fuel:null,transmission:null,color:null,source:null,sellerType:null,sort:null,priorities:[],excluded:[],goal:String(query||''),retrievalQuery:String(query||'')};if(!OPENAI_KEY||!String(query||'').trim())return fallback;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${OPENAI_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,store:false,reasoning:{effort:'none'},instructions:'You are Dalelah 1.1, a Saudi car search intent parser. Interpret Arabic, English and Saudi dialect. A single bare year means that exact year unless the user explicitly specifies a range. Never invent hard constraints. Keep make, model and year in retrievalQuery.',input:JSON.stringify({query,previousIntent}),text:{format:{type:'json_schema',name:'dalelah_v11_intent',strict:true,schema:{type:'object',additionalProperties:false,properties:{make:{type:['string','null']},model:{type:['string','null']},condition:{type:['string','null'],enum:['new','used',null]},city:{type:['string','null']},minYear:{type:['integer','null']},maxYear:{type:['integer','null']},minPrice:{type:['integer','null']},maxPrice:{type:['integer','null']},maxMileage:{type:['integer','null']},bodyType:{type:['string','null']},fuel:{type:['string','null']},transmission:{type:['string','null']},color:{type:['string','null']},source:{type:['string','null']},sellerType:{type:['string','null']},sort:{type:['string','null']},priorities:{type:'array',items:{type:'string'}},excluded:{type:'array',items:{type:'string'}},goal:{type:'string'},retrievalQuery:{type:'string'}},required:['make','model','condition','city','minYear','maxYear','minPrice','maxPrice','maxMileage','bodyType','fuel','transmission','color','source','sellerType','sort','priorities','excluded','goal','retrievalQuery']}}}}),signal:AbortSignal.timeout(9000)});if(!r.ok)return fallback;const data=await r.json();let txt='';for(const item of data.output||[])for(const part of item.content||[])if(part.type==='output_text')txt=part.text;const v=txt?JSON.parse(txt):fallback;if(y){v.minYear=y;v.maxYear=y;if(!String(v.retrievalQuery||'').includes(String(y)))v.retrievalQuery=`${v.retrievalQuery||query} ${y}`.trim()}return v}catch{return fallback}}

app.post('/api/search',async(req,res)=>{const body=req.body||{},query=String(body.query||''),y=exactYear(query);try{const intent=await aiIntent(query,body.previousIntent||body.aiContext||null),condition=body.condition||intent.condition||'used',rq=intent.retrievalQuery||query,requested=norm(body.filters?.source||intent.source||''),groups=[];if(!requested||requested==='haraj')groups.push(sourceSearch(rq,'Haraj',30).catch(()=>[]));if(!requested||requested==='saleh cars'||requested==='saleh')groups.push(sourceSearch(rq,'Saleh Cars',30).catch(()=>[]));let results=merge(...await Promise.all(groups));if(y&&results.filter(c=>!c.year||Number(c.year)===y).length<8)results=merge(results,await sourceSearch(rq,'YallaMotor',30).catch(()=>[]));results=results.filter(c=>hardMatch(c,intent,condition,y)).map(c=>score(c,intent,y)).sort((a,b)=>(b.aiScore||0)-(a.aiScore||0));const counts=results.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{}),searchId=`v11-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,payload={ok:true,searchId,listings:results,counts,exactYear:y,exactYearSemantics:Boolean(y),lowResultRecovery:Boolean(y&&results.length<8),ai:{enabled:Boolean(OPENAI_KEY),model:OPENAI_KEY?OPENAI_MODEL:null,intent},understanding:{aiIntent:intent},product:{version:'1.1',standalone:true,v36Baseline:true,legacyBoot:false,optionalBrandBrowse:true,harajDirectAdapter:true,salehCarsDirectAdapter:true}};progress.set(searchId,{at:Date.now(),payload});return res.json(payload)}catch(e){return res.status(502).json({error:e?.message||'Dalelah 1.1 search unavailable'})}});
app.get('/api/search/progress/:id',(req,res)=>{const hit=progress.get(req.params.id);return hit?res.json(hit.payload):res.status(404).json({error:'Search not found'})});
app.post('/api/understand',async(req,res)=>{const intent=await aiIntent(String(req.body?.query||''),req.body?.previousIntent||null);return res.json({ok:true,ai:Boolean(OPENAI_KEY),intent,exactYear:exactYear(req.body?.query||'')})});
app.get('/api/health',(_req,res)=>res.json({ok:true,product:'Dalelah 1.1',standalone:true,v36Baseline:true,legacyBoot:false,ai:Boolean(OPENAI_KEY),brave:Boolean(BRAVE_KEY)}));
app.get('/',(_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
setInterval(()=>{const now=Date.now();for(const[k,v]of cache)if(now-v.at>TTL)cache.delete(k);for(const[k,v]of progress)if(now-v.at>60*60_000)progress.delete(k)},10*60_000).unref();
app.listen(PORT,()=>console.log(`Dalelah 1.1 standalone (v36 baseline) running at http://localhost:${PORT}`));
