import express from 'express';
import path from 'path';
import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const externalPort=Number(process.env.PORT||3000);
const legacyPort=Number(process.env.DALELAH_LEGACY_PORT||6100);
process.env.PORT=String(legacyPort);
await import('./server-v24.js');
process.env.PORT=String(externalPort);

const app=express();
app.use(express.json({limit:'1mb'}));
app.use(express.static(path.join(__dirname,'public')));

const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';
const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const BRAVE_KEY=process.env.BRAVE_SEARCH_API_KEY||'';
const CACHE_TTL=8*60_000;
const sourceCache=new Map();
const intentCache=new Map();

const digits=s=>String(s||'').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d));
const norm=s=>digits(s).toLowerCase().normalize('NFKD').replace(/[\u064b-\u065f\u0670]/g,'').replace(/[إأآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^a-z0-9\u0600-\u06ff]+/g,' ').replace(/\s+/g,' ').trim();
const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;|&#34;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim();
function explicitYears(q=''){return [...digits(q).matchAll(/\b(19\d{2}|20\d{2})\b/g)].map(m=>Number(m[1])).filter(y=>y>=1980&&y<=2035)}
function hasRangeLanguage(q=''){const n=norm(q);return /(?:and above|or newer|and newer|or later|and later|above|newer than|from|since|after|وفوق|واكثر|وأكثر|احدث|أحدث|من موديل|بعد|to|through|until|الى|إلى|حتى|بين)/i.test(n)}
function exactYearFromQuery(q=''){const ys=explicitYears(q);return ys.length===1&&!hasRangeLanguage(q)?ys[0]:null}
function directHaraj(v=''){try{const u=new URL(v);return /(^|\.)haraj\.com\.sa$/i.test(u.hostname)&&/^\/(?:en\/)?\d{8,14}(?:\/|$)/.test(u.pathname)}catch{return false}}
function directSaleh(v=''){try{const u=new URL(v);return /(^|\.)salehcars\.com$/i.test(u.hostname)&&/^\/(?:en\/)?cars\/[A-Za-z0-9_-]{10,40}\/[^/]+\/?$/i.test(u.pathname)}catch{return false}}
function directYalla(v=''){try{const u=new URL(v);return /(^|\.)yallamotor\.com$/i.test(u.hostname)&&/\/used-cars\//i.test(u.pathname)}catch{return false}}
function canonical(v=''){try{const u=new URL(v);u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid)$/i.test(k))u.searchParams.delete(k);return u.href.replace(/\/$/,'')}catch{return String(v||'').replace(/\/$/,'')}}
function meta(html,key){const k=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`<meta[^>]+(?:property|name)=["']${k}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i').exec(html)?.[1]||new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${k}["'][^>]*>`,'i').exec(html)?.[1]||null}
function absolute(v,b){try{return new URL(String(v||'').replace(/&amp;/g,'&'),b).href}catch{return null}}
function yearOf(t=''){return explicitYears(t)[0]||null}
function mileageOf(t=''){const m=digits(t).match(/([0-9][\d,]{0,8})\s*(?:km|كيلو|كم)/i);return m?Number(m[1].replace(/,/g,'')):null}
function priceOf(t=''){const x=digits(t);for(const r of[/(?:price|السعر)\s*[:：]?\s*([0-9][\d,]{3,9})/i,/([0-9][\d,]{3,9})\s*(?:sar|ريال|ر\.?س)/i]){const m=x.match(r);if(m){const n=Number(m[1].replace(/,/g,''));if(n>=1000&&n<=5000000)return n}}return null}
function cityOf(t=''){const n=norm(t);if(/riyadh|الرياض/.test(n))return'Riyadh';if(/jeddah|جده/.test(n))return'Jeddah';if(/dammam|الدمام/.test(n))return'Dammam';if(/khobar|الخبر/.test(n))return'Khobar';if(/makkah|مكه/.test(n))return'Makkah';if(/madinah|المدينه/.test(n))return'Madinah';if(/taif|الطايف|الطائف/.test(n))return'Taif';return null}
function conditionOf(t='',source=''){const n=norm(t);if(/\bused\b|مستعمل/.test(n))return'used';if(/\bnew\b|جديد|زيرو/.test(n))return'new';return source==='Saleh Cars'?'new':null}
function imageOkay(v=''){try{const u=new URL(v);return /^https?:$/.test(u.protocol)&&!/(logo|favicon|icon|placeholder|avatar|banner|sprite)/i.test(u.href)}catch{return false}}
function inferIdentity(title=''){const clean=String(title).replace(/\s*\|.*$/,'').trim();const y=yearOf(clean);const tokens=clean.replace(/\b(?:19|20)\d{2}\b/g,'').split(/\s+/).filter(Boolean);return{brand:tokens[0]||null,model:tokens.slice(1,4).join(' ')||null,year:y}}

async function legacy(pathname,opts={}){const r=await fetch(`http://127.0.0.1:${legacyPort}${pathname}`,{...opts,signal:opts.signal||AbortSignal.timeout(45000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:text.slice(0,600)}}return{r,data}}
async function brave(q,count=20){if(!BRAVE_KEY)return[];const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',q);u.searchParams.set('count',String(count));u.searchParams.set('country','sa');const r=await fetch(u,{headers:{Accept:'application/json','X-Subscription-Token':BRAVE_KEY},signal:AbortSignal.timeout(9000)});if(!r.ok)return[];const d=await r.json();return d?.web?.results||[]}
async function fetchHtml(url){const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (compatible; Dalelah/1.1)','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);return{html:(await r.text()).slice(0,3000000),url:r.url||url}}
async function exactSource(url,source,seed={}){const d=await fetchHtml(url),text=strip(d.html),title=strip(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i.exec(d.html)?.[1]||'')||meta(d.html,'og:title')||seed.title||`${source} vehicle`,id=inferIdentity(title),img=absolute(meta(d.html,'og:image')||meta(d.html,'twitter:image'),d.url),price=priceOf(`${title} ${text.slice(0,12000)}`)||priceOf(seed.description||'');return{source,sourceType:source==='Saleh Cars'?'independent_dealer':'marketplace',seller:source,sourceStrict:true,title:title.slice(0,220),snippet:text.slice(0,700),url:canonical(d.url),brand:id.brand,model:id.model,year:id.year||yearOf(text),mileage:mileageOf(text),city:cityOf(text),price,priceVerified:Boolean(price),priceSource:price?'source_listing_page':null,condition:conditionOf(`${title} ${text.slice(0,4000)}`,source)||'used',saleVerified:true,image:img&&imageOkay(img)?img:null,displayImage:img&&imageOkay(img)?img:null,imageVerified:Boolean(img&&imageOkay(img)),imageSource:img&&imageOkay(img)?'source_listing_page':null,score:92,discovery:'v1.1_direct_adapter'}}
async function sourceSearch(query,source,count=20){const key=`${source}|${norm(query)}`,hit=sourceCache.get(key);if(hit&&Date.now()-hit.at<CACHE_TTL)return hit.value;const site=source==='Haraj'?'haraj.com.sa':source==='Saleh Cars'?'salehcars.com/cars':'ksa.yallamotor.com/used-cars';const validFn=source==='Haraj'?directHaraj:source==='Saleh Cars'?directSaleh:directYalla;const rs=(await brave(`site:${site} ${query}`,count)).filter(r=>validFn(r.url));const out=[];let i=0;async function worker(){for(;;){const n=i++;if(n>=rs.length)return;const r=rs[n];try{out.push(await exactSource(r.url,source,r))}catch{const id=inferIdentity(r.title||'');const text=`${r.title||''} ${r.description||''}`;out.push({source,sourceType:source==='Saleh Cars'?'independent_dealer':'marketplace',seller:source,sourceStrict:true,title:r.title||`${source} vehicle`,snippet:r.description||'',url:canonical(r.url),brand:id.brand,model:id.model,year:id.year||yearOf(text),mileage:mileageOf(text),city:cityOf(text),price:priceOf(text),priceVerified:Boolean(priceOf(text)),condition:conditionOf(text,source)||'used',saleVerified:true,image:null,displayImage:null,imageVerified:false,score:82,discovery:'v1.1_search_fallback'})}}}
await Promise.all(Array.from({length:Math.min(5,rs.length||1)},worker));sourceCache.set(key,{at:Date.now(),value:out});return out}
function merge(...groups){const m=new Map();for(const g of groups)for(const c of g||[]){if(!c?.url)continue;const k=canonical(c.url),old=m.get(k);m.set(k,old?{...c,...old,image:old.image||c.image,displayImage:old.displayImage||c.displayImage,price:old.price||c.price,priceVerified:Boolean(old.priceVerified||c.priceVerified)}:c)}return[...m.values()]}

async function aiIntent(query,previousIntent=null){const y=exactYearFromQuery(query),fallback={make:null,model:null,condition:null,city:null,minYear:y,maxYear:y,minPrice:null,maxPrice:null,maxMileage:null,bodyType:null,fuel:null,transmission:null,color:null,source:null,sellerType:null,sort:null,priorities:[],excluded:[],goal:String(query||''),retrievalQuery:String(query||'')};if(!OPENAI_API_KEY||!String(query||'').trim())return fallback;const key=`${norm(query)}|${JSON.stringify(previousIntent||{})}`,hit=intentCache.get(key);if(hit&&Date.now()-hit.at<CACHE_TTL)return hit.value;try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,store:false,reasoning:{effort:'none'},instructions:'You are Dalelah 1.1, a Saudi car-search intent parser. Interpret Arabic, English and Saudi dialect. A single bare year such as Corolla 2013 means exact year unless the user explicitly says and above, newer, from, after, to, until or a range. Never invent hard constraints. retrievalQuery must preserve make, model and year when specified.',input:JSON.stringify({query,previousIntent}),text:{format:{type:'json_schema',name:'dalelah_intent_v11',strict:true,schema:{type:'object',additionalProperties:false,properties:{make:{type:['string','null']},model:{type:['string','null']},condition:{type:['string','null'],enum:['new','used',null]},city:{type:['string','null']},minYear:{type:['integer','null']},maxYear:{type:['integer','null']},minPrice:{type:['integer','null']},maxPrice:{type:['integer','null']},maxMileage:{type:['integer','null']},bodyType:{type:['string','null']},fuel:{type:['string','null']},transmission:{type:['string','null']},color:{type:['string','null']},source:{type:['string','null']},sellerType:{type:['string','null']},sort:{type:['string','null']},priorities:{type:'array',items:{type:'string'}},excluded:{type:'array',items:{type:'string'}},goal:{type:'string'},retrievalQuery:{type:'string'}},required:['make','model','condition','city','minYear','maxYear','minPrice','maxPrice','maxMileage','bodyType','fuel','transmission','color','source','sellerType','sort','priorities','excluded','goal','retrievalQuery']}}}}),signal:AbortSignal.timeout(9000)});if(!response.ok)return fallback;const data=await response.json();let text='';for(const item of data.output||[])for(const part of item.content||[])if(part.type==='output_text')text=part.text;const value=text?JSON.parse(text):fallback;if(y){value.minYear=y;value.maxYear=y;value.retrievalQuery=value.retrievalQuery.includes(String(y))?value.retrievalQuery:`${value.retrievalQuery} ${y}`.trim()}intentCache.set(key,{at:Date.now(),value});return value}catch{return fallback}}
function hardFilter(c,intent,condition,exactYear){if(condition&&c.condition&&c.condition!==condition)return false;if(exactYear&&c.year&&Number(c.year)!==exactYear)return false;if(intent.minYear&&c.year&&c.year<intent.minYear)return false;if(intent.maxYear&&c.year&&c.year>intent.maxYear)return false;if(intent.maxPrice&&c.price&&c.price>intent.maxPrice)return false;if(intent.maxMileage&&c.mileage!=null&&c.mileage>intent.maxMileage)return false;if(intent.city&&c.city&&norm(c.city)!==norm(intent.city))return false;return true}
function score(c,intent,exactYear){let s=70,t=norm(`${c.brand||''} ${c.model||''} ${c.title||''}`);if(intent.make&&t.includes(norm(intent.make)))s+=8;if(intent.model&&t.includes(norm(intent.model)))s+=10;if(exactYear&&Number(c.year)===exactYear)s+=8;if(c.priceVerified)s+=2;if(c.imageVerified)s+=1;return{...c,aiScore:Math.min(100,s),aiReason:exactYear&&Number(c.year)===exactYear?'Exact year match':c.priceVerified?'Verified source listing':'Direct source listing'}}

app.post('/api/search',async(req,res)=>{const body=req.body||{},query=String(body.query||''),exactYear=exactYearFromQuery(query);try{const intent=await aiIntent(query,body.previousIntent||body.aiContext||null);const condition=body.condition||intent.condition||'used';const filters={...(body.filters||{})};if(exactYear&&!filters.minYear&&!filters.maxYear){filters.minYear=exactYear;filters.maxYear=exactYear}const retrievalQuery=intent.retrievalQuery||query;let base=[];try{const {r,data}=await legacy('/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,query:retrievalQuery,condition,filters})});if(r.ok)base=Array.isArray(data.listings)?data.listings:[]}catch{}
const [haraj,saleh]=await Promise.all([sourceSearch(retrievalQuery,'Haraj',20).catch(()=>[]),sourceSearch(retrievalQuery,'Saleh Cars',20).catch(()=>[])]);let listings=merge(base,haraj,saleh).filter(c=>hardFilter(c,intent,condition,exactYear)).map(c=>score(c,intent,exactYear));let recovered=0;if(exactYear&&listings.length<8){const yalla=await sourceSearch(`${intent.make||''} ${intent.model||''} ${exactYear}`.trim(),'YallaMotor',30).catch(()=>[]);const before=listings.length;listings=merge(listings,yalla).filter(c=>hardFilter(c,intent,condition,exactYear)).map(c=>score(c,intent,exactYear));recovered=Math.max(0,listings.length-before)}listings.sort((a,b)=>(b.aiScore||b.score||0)-(a.aiScore||a.score||0));const counts=listings.reduce((a,c)=>(a[c.source]=(a[c.source]||0)+1,a),{});return res.json({query,condition,listings,counts,live:true,ai:{enabled:Boolean(OPENAI_API_KEY),model:OPENAI_API_KEY?OPENAI_MODEL:null,intent,mode:OPENAI_API_KEY?'ai-native-hybrid':'deterministic-fallback'},exactYear,lowResultRecovery:Boolean(exactYear&&listings.length<8),recoveredExactYear:recovered,product:{version:'1.1',freshArchitecture:true,optionalBrandBrowse:true,harajDirectAdapter:true,salehCarsDirectAdapter:true,exactYearDefault:true}})}catch(e){return res.status(502).json({error:e?.message||'Dalelah 1.1 search unavailable'})}});

app.get('/api/health',(_req,res)=>res.json({ok:true,edge:'dalelah-1.1',version:'1.1',freshArchitecture:true,frontend:'direct-static',aiNativeSearch:Boolean(OPENAI_API_KEY),haraj:true,salehCars:true,exactYearDefault:true}));
app.get('/',async(_req,res)=>{try{let html=await readFile(path.join(__dirname,'public','product-v24.html'),'utf8');html=html.replaceAll('Delilah','Dalelah').replace('</body>','<script src="/hotfix-v35.js?v=11"></script><script>window.DALELAH_VERSION="1.1";</script></body>');res.setHeader('cache-control','no-store');return res.type('html').send(html)}catch(e){return res.status(500).send('Dalelah 1.1 frontend load error')}});

app.listen(externalPort,()=>console.log(`Dalelah 1.1 running at http://localhost:${externalPort}`));
