const base=process.env.DELILAH_URL||'https://delilah-pm5f.onrender.com';
const cases=[
  {q:'ابي رانجلر 2022 وفوق بالرياض تحت 130000',condition:'used',min:1,model:'Wrangler'},
  {q:'Jeep Compass',condition:'used',model:'Compass'},
  {q:'ابي باترول 2022 وفوق بالرياض تحت 170000',condition:'used',min:1,model:'Patrol'},
  {q:'Toyota Camry Riyadh under 120000',condition:'used',min:1,model:'Camry'},
  {q:'Land Cruiser 2022 Riyadh',condition:'used',model:'Land Cruiser'},
  {q:'BMW X5 Riyadh',condition:'used',model:'X5'},
  {q:'Mercedes C200 Riyadh',condition:'used',model:'C200'},
  {q:'Toyota Land Cruiser 2026 Riyadh',condition:'new',model:'Land Cruiser'},
  {q:'Nissan Patrol 2026 Riyadh',condition:'new',model:'Patrol'},
  {q:'Ford Territory 2026 Saudi',condition:'new',model:'Territory'},
  {q:'Kia Sportage 2026 Jeddah',condition:'new',model:'Sportage'}
];
const timeout=ms=>AbortSignal.timeout(ms);
let pass=0,fail=0,totalCars=0,totalImages=0,relayChecks=0,relayPass=0;
const health=await fetch(`${base}/api/health`,{signal:timeout(10000)});if(!health.ok)throw new Error(`health ${health.status}`);const h=await health.json();if(!h.ok||h.edge!=='product-v25'||h.fullProduct!==true||h.aiSearchUnderstanding!==true||h.exactModelIdentity!==true||h.syarahOriginalPricePolicy!==true)throw new Error(`health config invalid: ${JSON.stringify(h)}`);console.log(`health ok; ${h.edge}; ${h.logic}`);
for(const t of cases){try{const r=await fetch(`${base}/api/search`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:t.q,condition:t.condition,filters:{},phase:'fast'}),signal:timeout(22000)});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,200)}`);const d=await r.json();if(!Array.isArray(d.listings))throw new Error('listings not array');if(t.min&&d.listings.length<t.min)throw new Error(`expected at least ${t.min}, got ${d.listings.length}`);if(t.model&&d.understanding?.model!==t.model)throw new Error(`wrong model understanding ${JSON.stringify(d.understanding)}`);const urls=new Set();let images=0;for(const c of d.listings){if(!c.url||urls.has(c.url))throw new Error(`missing/duplicate url ${c.url}`);urls.add(c.url);if(c.saleVerified!==true)throw new Error(`unverified sale ${c.url}`);if(c.condition!==t.condition)throw new Error(`condition leak ${c.url}`);if(/\/(news|blog|article|reviews?|brochure|specifications?|press-release)(\/|$)/i.test(c.url))throw new Error(`informational page leaked ${c.url}`);if(t.model){const ev=`${c.title||''} ${decodeURIComponent(c.url||'')}`.toLowerCase().replace(/[-_]+/g,' ');const want=t.model.toLowerCase().replace(/[-_]+/g,' ');if(!ev.includes(want))throw new Error(`cross-model result for ${t.model}: ${c.title} ${c.url}`)}if(c.image){if(c.imageVerified!==true)throw new Error(`unverified image ${c.url}`);images++;if(!relayChecks&&c.displayImage&&c.displayImage.startsWith('/api/image/')){relayChecks++;const ir=await fetch(`${base}${c.displayImage}`,{signal:timeout(20000)});if(!ir.ok)throw new Error(`image relay HTTP ${ir.status}`);const ct=(ir.headers.get('content-type')||'').toLowerCase();if(!ct.startsWith('image/'))throw new Error(`image relay non-image ${ct}`);relayPass++}}if(c.price!=null&&(!Number.isFinite(Number(c.price))||Number(c.price)<=0))throw new Error('invalid price');if(c.source==='Syarah'&&c.price!=null&&c.priceSource!=='syarah_original_pre_discount_price')throw new Error(`non-original Syarah price ${c.priceSource}`);if(c.mileage!=null&&(!Number.isFinite(Number(c.mileage))||Number(c.mileage)<0))throw new Error('invalid mileage')}
 totalCars+=d.listings.length;totalImages+=images;console.log(`PASS ${t.condition.padEnd(4)} | ${String(d.listings.length).padStart(3)} cars | ${String(images).padStart(3)} images | ${t.q}`);pass++}catch(e){console.error(`FAIL ${t.condition} | ${t.q} | ${e.message}`);fail++}}
console.log(`live smoke: ${pass} passed, ${fail} failed; ${totalCars} cars; ${totalImages} verified images; relay ${relayPass}/${relayChecks}`);if(relayChecks===0){console.error('FAIL no embedded image relay was exercised');fail++}if(fail>0)process.exit(1);
