import test from 'node:test';import assert from 'node:assert/strict';
import{validateValuationInput,valueVehicle}from'../lib/vehicle-valuation.js';
import{matchValuationTrims}from'../lib/valuation-trim-assist.js';
import{valuationHandoff,readValuationHandoff}from'../public/valuation-handoff.js';
const vehicle={make:'Toyota',model:'Camry',year:2020,mileageKm:100000,city:'Riyadh'},now=Date.now(),seen=new Date(now).toISOString();
const cars=Array.from({length:12},(_,i)=>({make:'Toyota',brand:'Toyota',model:'Camry',year:2020,yearVerified:true,price:70000+i*1000,priceVerified:true,mileage:70000+i*5000,trim:'GL',condition:'used',city:'Riyadh',source:i%2?'Haraj':'Syarah',title:'Toyota Camry 2020 GL',url:`https://example.com/test-only-${i}`,image:'https://example.com/photo.jpg',lastSeenAt:seen,availability:'listed'}));
const opts={now,snapshotAt:seen};
test('valuation accepts required-only Arabic and English vehicle details',()=>{const r=validateValuationInput({...vehicle,make:'تويوتا',model:'كامري',year:'٢٠٢٠',mileageKm:'١٠٠٬٠٠٠',city:'الرياض'});assert(r.ok);assert.deepEqual(r.value,vehicle);assert(validateValuationInput(vehicle).ok);});
test('valuation rejects invalid, missing and oversized input without fuzzy model substitution',()=>{for(const v of [null,[],{}, {...vehicle,model:'Not a Camry'}, {...vehicle,mileageKm:''},{...vehicle,year:2039},{...vehicle,city:'London'},{...vehicle,trim:{}},{...vehicle,trim:'a'.repeat(101)},{...vehicle,vehicleCondition:'perfect'},{...vehicle,mileageKm:-1}])assert.equal(validateValuationInput(v).ok,false);});
test('prices derive from real comparables and preserve source URLs/images',()=>{const r=valueVehicle(cars,vehicle,opts);assert(r.available);assert.equal(r.comparableCount,12);assert(r.estimatedMarketValue>=70000&&r.estimatedMarketValue<=81000);assert(r.valuationLow<=r.estimatedMarketValue&&r.valuationHigh>=r.estimatedMarketValue);assert(r.quickSaleValue<=r.estimatedMarketValue&&r.recommendedListingPrice>=r.estimatedMarketValue);assert(r.comparableListings.every(c=>cars.some(x=>x.url===c.url&&x.price===c.price&&x.image===c.image)));assert.equal(r.priceBasis,'asking-prices');});
test('same model stays strict; used, price, freshness, category sale quality are required',()=>{const bad=[{model:'Corolla'},{make:'BMW',model:'X5'},{condition:'new'},{priceVerified:false},{yearVerified:false},{availability:'sold'},{price:null},{price:0},{url:'javascript:alert(1)'},{lastSeenAt:new Date(now-40*3600000).toISOString()},{title:'Toyota Camry salvage'},{year:2016}].map((v,i)=>({...cars[0],url:`https://example.com/bad-${i}`,...v}));const r=valueVehicle(bad,vehicle,opts);assert.equal(r.comparableCount,0);assert.equal(r.estimatedMarketValue,null);});
test('insufficient evidence never fabricates a point estimate',()=>{for(const n of [0,1,2]){const r=valueVehicle(cars.slice(0,n),vehicle,opts);assert.equal(r.available,false);assert.equal(r.comparableCount,n);assert.equal(r.estimatedMarketValue,null);}});
test('exact-year pool preferred and expansion stays within two years with disclosure',()=>{const adjacent=cars.map((c,i)=>({...c,year:2021,url:c.url+'near'}));const exact=valueVehicle([...cars,...adjacent],vehicle,opts);assert.equal(exact.comparableCount,12);assert(!exact.limitations.includes('nearby-years'));const broad=valueVehicle(adjacent.slice(0,4),vehicle,opts);assert.equal(broad.available,false);assert.equal(broad.reason,'insufficient-year-evidence');assert(broad.limitations.includes('nearby-years'));assert.equal(broad.confidence,'limited');});
test('duplicate URLs/VINs do not inflate evidence, and extreme prices are excluded',()=>{const r=valueVehicle([...cars,...cars,{...cars[0],url:'https://example.com/outlier',price:900000}],vehicle,opts);assert.equal(r.comparableCount,12);assert.equal(r.outlierCount,1);assert(r.highestComparablePrice<900000);});
test('soft optional attributes do not invent a premium or eliminate inventory',()=>{const r=valueVehicle(cars,{...vehicle,vehicleCondition:'excellent',accidentHistory:'no',serviceHistory:'yes',engine:'2.5'},opts);assert(r.available);assert(r.limitations.includes('unadjusted-vehicleCondition'));assert(!r.adjustmentFactors.some(x=>x.attribute==='vehicleCondition'));});
test('unknown mileage keeps conservative evidence without made-up odometers',()=>{const r=valueVehicle(cars.map(c=>({...c,mileage:null})),vehicle,opts);assert(r.available);assert.equal(r.averageMileage,null);assert(r.limitations.includes('missing-mileage'));assert.equal(r.confidence,'medium');});
test('mileage adjustment requires observed same-trim evidence and no extrapolation',()=>{const rows=cars.map((c,i)=>({...c,mileage:50000+i*10000,price:100000-i*2000}));const r=valueVehicle(rows,vehicle,opts);assert.equal(r.adjustmentFactors.find(x=>x.attribute==='mileage').method,'observed-same-trim-regression');const outside=valueVehicle(rows,{...vehicle,mileageKm:800000},opts);assert.equal(outside.adjustmentFactors.find(x=>x.attribute==='mileage').method,'comparable-weighting');});
test('AI trim assist has no price output and rejects invented observed labels',async()=>{const env={OPENAI_API_KEY:'test-only',DALELAH_AI_MODEL:'test-model'},v={...vehicle,trim:'Arabic GL'};let called=false;const fetchImpl=async(_url,o)=>{called=true;const req=JSON.parse(o.body);assert.equal(req.model,'test-model');assert(!req.input.includes('price'));return{ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({matchingTrims:['INVENTED']})}]}]})};};const r=await matchValuationTrims(v,cars,{env,fetchImpl});assert(called);assert.equal(r.aiMode,'deterministic');assert.equal(r.aiFallback,true);});
test('AI trim assist remains optional and provider failure cannot break valuation',async()=>{let called=false;const fetchImpl=async()=>{called=true;throw Error('test timeout');};assert.equal((await matchValuationTrims(vehicle,cars,{env:{OPENAI_API_KEY:'test'},fetchImpl})).aiMode,'deterministic');assert.equal(called,false);const r=await matchValuationTrims({...vehicle,trim:'GL English'},cars,{env:{OPENAI_API_KEY:'test'},fetchImpl});assert(r.aiFallback);assert(valueVehicle(cars,vehicle,{...opts,...r}).available);});
test('valuation handoff preserves vehicle fields and expires without contact information',()=>{const r=valueVehicle(cars,{...vehicle,trim:'GL',vehicleCondition:'good'},opts);const h=valuationHandoff(r,now);assert.equal(h.fields.mileageKm,100000);assert.equal(h.fields.askingPriceSar,r.recommendedListingPrice);assert.equal(h.optional.vehicleCondition,'good');assert(!('sellerPhone'in h.fields));assert(readValuationHandoff(JSON.stringify(h),now));assert.equal(readValuationHandoff(JSON.stringify(h),now+3600001),null);});

test('AI trim assistance accepts only observed equivalent trim labels',async()=>{const r=await matchValuationTrims({...vehicle,trim:'جي ال' },cars,{env:{OPENAI_API_KEY:'test-only'},fetchImpl:async()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({matchingTrims:['GL']})}]}]})})});assert.equal(r.aiMode,'trim-assist');assert.deepEqual(r.matchingTrims,['GL']);});
test('mileage/city preference never discards all available exact-year evidence',()=>{const adjacent=cars.map(c=>({...c,year:2021,city:'Jeddah',url:c.url+'near'}));const exact=cars.slice(0,2).map(c=>({...c,mileage:250000}));const r=valueVehicle([...exact,...adjacent],{...vehicle,city:'Jeddah'},opts);assert.equal(r.exactYearCount,2);});

test('materially different comparable mileage lowers confidence and favours closer cars',()=>{const rows=[
 {mileage:85000,price:83000},{mileage:111000,price:75700},{mileage:134000,price:82500},{mileage:136000,price:77400},{mileage:138000,price:75200},{mileage:145000,price:72500}
].map((x,i)=>({...cars[i],...x,url:`https://example.com/mileage-gap-${i}`}));const r=valueVehicle(rows,{...vehicle,year:2020,mileageKm:60000},opts);assert(r.available);assert.equal(r.confidence,'limited');assert(r.limitations.includes('limited-mileage-evidence'));assert(r.estimatedMarketValue>=82500);});

test('only newer-year comparables cannot masquerade as the requested year value',()=>{const r=valueVehicle(cars.map(c=>({...c,year:2022})),vehicle,opts);assert.equal(r.available,false);assert.equal(r.reason,'insufficient-year-evidence');assert.equal(r.estimatedMarketValue,null);assert(r.comparableListings.length>0);});
