const API='https://api.massive.com';
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function safePct(a,b){return b?((a/b)-1)*100:0}function nyMinutesElapsed(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const h=+parts.find(x=>x.type==='hour')?.value||0,m=+parts.find(x=>x.type==='minute')?.value||0;return clamp((h*60+m)-(9*60+30),15,390)}
async function mget(path,params,apiKey){if(!apiKey)throw Error('MASSIVE_API_KEY missing');const u=new URL(API+path);for(const[k,v]of Object.entries(params||{}))if(v!==undefined&&v!==null)u.searchParams.set(k,String(v));u.searchParams.set('apiKey',apiKey);const r=await fetch(u,{headers:{'User-Agent':'AwaedCopilot/0.6'}});if(!r.ok)throw Error(`Massive ${r.status}`);return r.json()}
function snapshotCandidate(t){const px=t?.lastTrade?.p||t?.min?.c||t?.day?.c||0,open=t?.day?.o||0,dayV=t?.day?.v||0,prevV=t?.prevDay?.v||0,prevClose=t?.prevDay?.c||0,minV=t?.min?.v||0,dayHigh=t?.day?.h||px,dayLow=t?.day?.l||px,chg=safePct(px,prevClose||open),elapsed=nyMinutesElapsed(),expected=prevV*(elapsed/390),rvol=expected>0?dayV/expected:0,minuteBurst=prevV>0?minV/(prevV/390):0,dayRangePct=px?((dayHigh-dayLow)/px)*100:0;let score=0;if(px>=.1&&px<=15)score+=12;if(dayV>=1e6)score+=12;if(dayV>=5e6)score+=8;if(rvol>=2)score+=12;if(rvol>=5)score+=14;if(rvol>=10)score+=10;if(minuteBurst>=3)score+=8;if(chg>=5)score+=8;if(chg>=15)score+=8;if(chg>=40)score+=4;if(chg<-5)score-=8;return{symbol:t.ticker,price:px,changePct:+chg.toFixed(2),dayVolume:dayV,minuteVolume:minV,rvol:+rvol.toFixed(2),minuteBurst:+minuteBurst.toFixed(2),dayRangePct:+dayRangePct.toFixed(2),discoveryScore:clamp(Math.round(score),0,100)}}
async function fullMarketCandidates(apiKey,{minPrice=.1,maxPrice=15,minVolume=750000,limit=40}={}){const j=await mget('/v2/snapshot/locale/us/markets/stocks/tickers',{include_otc:false},apiKey),all=(j.tickers||[]).map(snapshotCandidate).filter(x=>x.price>=minPrice&&x.price<=maxPrice&&x.dayVolume>=minVolume&&x.symbol&&!x.symbol.includes('.')).sort((a,b)=>b.discoveryScore-a.discoveryScore||b.rvol-a.rvol||b.dayVolume-a.dayVolume);return all.slice(0,limit)}
const POS=['fda','approval','contract','award','partnership','acquisition','merger','positive','breakthrough','patent','order','guidance','beats','strategic','launch','clearance','phase 3','phase iii'];const NEG=['offering','dilution','reverse split','bankruptcy','delisting','investigation','lawsuit','misses','termination','default'];
function articleImpact(a,symbol){const title=String(a.title||'').toLowerCase(),published=Date.parse(a.published_utc||0),ageMin=published?Math.max(0,(Date.now()-published)/60000):99999;let score=0;if(ageMin<=15)score+=18;else if(ageMin<=60)score+=12;else if(ageMin<=180)score+=6;for(const w of POS)if(title.includes(w)){score+=8;break}for(const w of NEG)if(title.includes(w)){score-=18;break}const insight=(a.insights||[]).find(x=>String(x.ticker||'').toUpperCase()===symbol);if(insight?.sentiment==='positive')score+=8;if(insight?.sentiment==='negative')score-=12;return{title:a.title||'',url:a.article_url||'',publishedUtc:a.published_utc||null,ageMin:+ageMin.toFixed(1),sentiment:insight?.sentiment||'unknown',impact:clamp(score,-30,35)}}
async function newsPulse(apiKey,symbol){try{const j=await mget('/v2/reference/news',{ticker:symbol,order:'desc',sort:'published_utc',limit:5},apiKey),arts=(j.results||[]).map(a=>articleImpact(a,symbol));return{newsScore:clamp(arts.reduce((m,a)=>Math.max(m,a.impact),0),-30,35),articles:arts.slice(0,3)}}catch(e){return{newsScore:0,articles:[],error:e.message}}}
function breakoutScore(c,news){let s=25;s+=clamp(c.discoveryScore*.45,0,40);if(c.rvol>=5)s+=8;if(c.rvol>=10)s+=6;if(c.minuteBurst>=5)s+=8;if(c.changePct>=8&&c.changePct<=45)s+=8;if(c.changePct>80)s-=10;s+=(news?.newsScore||0);return clamp(Math.round(s),0,100)}
async function enrichCandidate(apiKey,c){const news=await newsPulse(apiKey,c.symbol),score=breakoutScore(c,news),riskPct=clamp(Math.max(3.5,c.dayRangePct*.22),3.5,12),risk=c.price*riskPct/100,stop=Math.max(.01,c.price-risk),target1=c.price+risk*1.6,target2=c.price+risk*3;return{...c,newsScore:news.newsScore,news:news.articles,breakout15mScore:score,state:score>=82?'BUY SETUP':score>=70?'HOT':score>=58?'RADAR':'COOL',validatedProbability:false,stop:+stop.toFixed(4),target1:+target1.toFixed(4),target2:+target2.toFixed(4),riskPct:+riskPct.toFixed(2)}}
async function radar(apiKey,opts={}){const base=await fullMarketCandidates(apiKey,opts),top=base.slice(0,Math.min(opts.enrichLimit||15,base.length)),enriched=[];for(const c of top)enriched.push(await enrichCandidate(apiKey,c));return enriched.sort((a,b)=>b.breakout15mScore-a.breakout15mScore)}
async function historicalBars(apiKey,symbol,from,to,multiplier=5,timespan='minute'){return mget(`/v2/aggs/ticker/${encodeURIComponent(symbol)}/range/${multiplier}/${timespan}/${from}/${to}`,{adjusted:true,sort:'asc',limit:50000},apiKey)}module.exports={radar,fullMarketCandidates,newsPulse,historicalBars,breakoutScore};
