const express=require('express');const path=require('path');const webpush=require('web-push');
const app=express(),PORT=process.env.PORT||10000;const PUB=process.env.VAPID_PUBLIC_KEY||'',PRIV=process.env.VAPID_PRIVATE_KEY||'',SUBJ=process.env.VAPID_SUBJECT||'mailto:notifications@example.com';if(PUB&&PRIV)webpush.setVapidDetails(SUBJ,PUB,PRIV);
app.use(express.json({limit:'256kb'}));app.use(express.static(path.join(__dirname,'public')));
const DEFAULT=['NVDA','TSLA','AMD','PLTR','AAPL','MSFT','AMZN','META','GOOGL','AVGO','NFLX','COIN','SOFI','TSM','QQQ'];const clients=new Map(),recent=new Map(),positions=new Map();
function clean(a){const o=[];for(const x of Array.isArray(a)?a:[]){const s=String(x||'').toUpperCase().trim();if(/^[A-Z.\-]{1,10}$/.test(s)&&!o.includes(s))o.push(s);if(o.length>=25)break}return o.length?o:DEFAULT}
function ema(v,p){if(!v.length)return 0;let e=v[0],k=2/(p+1);for(let i=1;i<v.length;i++)e=v[i]*k+e*(1-k);return e}
function rsi(v,p=14){if(v.length<=p)return 50;let g=0,l=0;for(let i=v.length-p;i<v.length;i++){const d=v[i]-v[i-1];d>=0?g+=d:l-=d}if(!l)return 100;const rs=(g/p)/(l/p);return 100-100/(1+rs)}
async function bars(sym){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?interval=5m&range=1d&includePrePost=true`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 AwaedCopilot/0.4','Accept':'application/json'}});if(!r.ok)throw Error(`Market data ${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0];if(!x)throw Error('No market data');const q=x.indicators?.quote?.[0]||{},b=[];for(let i=0;i<(x.timestamp||[]).length;i++){const c=q.close?.[i];if(typeof c!=='number')continue;b.push({c,h:q.high?.[i]??c,l:q.low?.[i]??c,v:q.volume?.[i]??0})}return{b,meta:x.meta||{}}}
function score(sym,b,meta={}){if(b.length<12)throw Error('Not enough bars yet');const c=b.map(x=>x.c),last=b.at(-1),prior=b[Math.max(0,b.length-7)],mom=(last.c/prior.c-1)*100,e9=ema(c.slice(-30),9),e21=ema(c.slice(-40),21),R=rsi(c),pb=b.slice(Math.max(0,b.length-13),-1),hi=Math.max(...pb.map(x=>x.h)),av=pb.reduce((a,x)=>a+(x.v||0),0)/Math.max(pb.length,1),vr=av>0?(last.v||0)/av:1;let s=35,why=[];if(e9>e21){s+=15;why.push('9 EMA above 21 EMA')}else{s-=10;why.push('short trend weak')}if(mom>.6){s+=15;why.push(`${mom.toFixed(2)}% short-term momentum`)}else if(mom<-.5){s-=12;why.push('negative momentum')}if(last.c>hi){s+=18;why.push('intraday breakout')}if(vr>=1.8){s+=12;why.push(`${vr.toFixed(1)}x volume expansion`)}if(R>=55&&R<=74){s+=10;why.push(`RSI ${R.toFixed(0)} supportive`)}if(R>82){s-=15;why.push('RSI very extended')}s=Math.max(0,Math.min(100,Math.round(s)));const risk=Math.max(last.c*.012,Math.abs(last.c-e21)*.8),stop=Math.max(.01,last.c-risk);return{symbol:sym,price:last.c,score:s,label:s>=78?'BUY SETUP':s>=62?'WATCH':'AVOID',momentumPct:+mom.toFixed(2),volumeRatio:+vr.toFixed(2),rsi:+R.toFixed(1),ema9:+e9.toFixed(3),ema21:+e21.toFixed(3),stop:+stop.toFixed(2),target1:+(last.c+risk*1.8).toFixed(2),target2:+(last.c+risk*3).toFixed(2),reasons:why.slice(0,4),timestamp:Date.now()}}
async function analyze(s){const{b,meta}=await bars(s);return score(s,b,meta)}async function scan(syms){const out=[];for(const s of clean(syms)){try{out.push(await analyze(s))}catch(e){out.push({symbol:s,error:e.message,score:0,label:'NO DATA'})}}return out.sort((a,b)=>(b.score||0)-(a.score||0))}
async function push(sub,p){if(!PUB||!PRIV)throw Error('Push keys not configured');return webpush.sendNotification(sub,JSON.stringify(p),{TTL:90})}const k=(ep,s)=>`${ep}|${s}`;
function exit(sig,p){if(sig.price<=p.stop)return{reason:'STOP HIT'};if(sig.price>=p.target2)return{reason:'TARGET 2 HIT'};if(sig.price>=p.target1&&!p.t1Notified)return{reason:'TARGET 1 HIT',partial:true};if((sig.score||0)<55||sig.ema9<sig.ema21||sig.momentumPct<-.5)return{reason:'MOMENTUM EXIT'};return null}
async function cycle(){if(!clients.size)return;const syms=[...new Set([...clients.values()].flatMap(c=>c.watchlist).concat([...positions.values()].map(p=>p.symbol)))].slice(0,30);if(!syms.length)return;let rs;try{rs=await scan(syms)}catch{return}const by=new Map(rs.map(x=>[x.symbol,x]));for(const[ep,c]of clients){for(const sym of c.watchlist){const sig=by.get(sym);if(!sig||sig.error)continue;const pos=positions.get(k(ep,sym));if(pos){pos.lastPrice=sig.price;pos.pnlPct=(sig.price/pos.entry-1)*100;pos.pnlUsd=(sig.price-pos.entry)*pos.shares;const ex=exit(sig,pos);if(ex){const rk=`${ep}|${sym}|${ex.reason}`,last=recent.get(rk)||0;if(Date.now()-last>10*60*1000){try{await push(c.subscription,{title:`SELL / EXIT ${sym} · ${ex.reason}`,body:`$${sig.price.toFixed(2)} · P/L ${pos.pnlPct>=0?'+':''}${pos.pnlPct.toFixed(2)}% · ${pos.pnlUsd>=0?'+':''}$${pos.pnlUsd.toFixed(2)}`,data:{url:`/?symbol=${sym}&action=sell`}});recent.set(rk,Date.now());if(ex.partial)pos.t1Notified=true;else positions.delete(k(ep,sym))}catch(e){if([404,410].includes(e.statusCode))clients.delete(ep)}}}continue}if((sig.score||0)>=c.minScore&&sig.label==='BUY SETUP'){const rk=`${ep}|${sym}|BUY`,last=recent.get(rk)||0;if(Date.now()-last>30*60*1000){try{await push(c.subscription,{title:`BUY ALERT ${sym} · ${sig.score}/100`,body:`$${sig.price.toFixed(2)} · Stop $${sig.stop.toFixed(2)} · T1 $${sig.target1.toFixed(2)} · Tap I BOUGHT after execution.`,data:{url:`/?symbol=${sym}&action=buy`}});recent.set(rk,Date.now())}catch(e){if([404,410].includes(e.statusCode))clients.delete(ep)}}}}}}
app.get('/api/status',(q,r)=>r.json({ok:true,version:'0.4.0',pushConfigured:!!(PUB&&PRIV),subscribers:clients.size,positions:positions.size,alerts:['BUY','SELL STOP','SELL TARGET','SELL MOMENTUM'],note:'SELL tracking begins only after I BOUGHT confirmation.'}));app.get('/api/vapid-public-key',(q,r)=>r.json({publicKey:PUB}));
app.post('/api/scan',async(q,r)=>{try{r.json({ok:true,results:await scan(clean(q.body?.symbols)),at:Date.now()})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.post('/api/subscribe',(q,r)=>{const s=q.body?.subscription;if(!s?.endpoint)return r.status(400).json({ok:false,error:'Missing subscription'});clients.set(s.endpoint,{subscription:s,watchlist:clean(q.body?.watchlist),minScore:Math.max(70,Math.min(95,+q.body?.minScore||78))});r.json({ok:true})});
app.post('/api/preferences',(q,r)=>{const c=clients.get(q.body?.endpoint);if(!c)return r.status(404).json({ok:false,error:'Subscription not found'});c.watchlist=clean(q.body?.watchlist);c.minScore=Math.max(70,Math.min(95,+q.body?.minScore||c.minScore));r.json({ok:true})});
app.post('/api/bought',(q,r)=>{const ep=q.body?.endpoint,sym=String(q.body?.symbol||'').toUpperCase(),entry=+q.body?.entry,shares=Math.max(1,Math.floor(+q.body?.shares||0)),stop=+q.body?.stop,t1=+q.body?.target1,t2=+q.body?.target2;if(!clients.has(ep)||!sym||!entry||!shares)return r.status(400).json({ok:false,error:'Missing confirmed trade details'});const p={symbol:sym,entry,shares,stop,target1:t1,target2:t2,openedAt:Date.now(),lastPrice:entry,pnlPct:0,pnlUsd:0,t1Notified:false};positions.set(k(ep,sym),p);r.json({ok:true,position:p})});
app.post('/api/sold',(q,r)=>{positions.delete(k(q.body?.endpoint,String(q.body?.symbol||'').toUpperCase()));r.json({ok:true})});
app.post('/api/positions',(q,r)=>{const ep=q.body?.endpoint||'';r.json({ok:true,positions:[...positions.entries()].filter(([key])=>key.startsWith(ep+'|')).map(([,p])=>p)})});
app.post('/api/test-push',async(q,r)=>{const c=clients.get(q.body?.endpoint);if(!c)return r.status(404).json({ok:false,error:'Enable notifications first'});try{await push(c.subscription,{title:'Awaed Copilot live tracking is on',body:'BUY alerts → tap I BOUGHT → live P/L → SELL alerts.',data:{url:'/'}});r.json({ok:true})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.get('/healthz',(q,r)=>r.send('ok'));app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));setInterval(cycle,60e3);setTimeout(cycle,10e3);app.listen(PORT,()=>console.log(`Awaed Copilot v0.4 listening on ${PORT}`));